### PR TITLE
Not a pull request

### PR DESCRIPTION
**Pull request by lnsanityGames**
But what is this

### CODE REVIEW

**Comment by CST1229** [comment]
magnifier.potatophant.net addon. iirc w_l rejected it, because it uses an external server.

**Comment by apple502j** [comment]
We do allow addons that use external server. We do not allow pull requests that are self-contradicting, though.

**Comment by lnsanityGames** [comment]
Closing because why is this in the master directory

**Comment by CST1229** [comment]
> 
> 
> Closing because why is this in the master directory

potatophant made it like that, not insanitygames

**Pull request closed without merging**
