### PR TITLE
Add editor-stage-left addon

### PR DESCRIPTION
**Pull request by ZenithRogue**
**Changes**

Created a new addon that allows you to display the stage on the left side, emulating Scratch 2.0

image

**Reason for changes**

People have wanted this in Scratch 3.0 since it was initially released

**Tests**

Addon has tested positively, and appears in the proper theme category
image

### CODE REVIEW

**Comment by JeffaloBob** [comment]
this looks really neat.

does it work properly with the dark mode themes?

**Comment by ZenithRogue** [comment]
You betcha
image

**Comment by ZenithRogue** [comment]
this required only minor CSS edits as you can see by looking at `stageleft.css`

**Comment by JeffaloBob** [comment]
very cool 👍

**Review by WorldLanguages — APPROVED** [review]
Looks good, will make a few changes and merge.

**Comment by WorldLanguages** [comment]
Hmm, this appears to break moving blocks from a sprite to another, are you aware of this?

**Comment by ZenithRogue** [comment]
Wacky, did not come across that in testing

**Review by WorldLanguages — CHANGES_REQUESTED** [review]
I'm going to block this PR until we find a way to fix "share the love" not working. Maybe this could be added as a "beta" addon, but I find it very likely that someone that would use this addon, would also use this broken feature pretty frequently.

**Comment by ZenithRogue** [comment]
Share the love? I'm not familiar with it

**Comment by WorldLanguages** [comment]
"Share the love" is the name for moving scripts between sprites. ST named it, not my fault :P

**Comment by ZenithRogue** [comment]
I'd like this to be added still.

It could be marked as Beta, and a disclaimer thrown on it

**Comment by WorldLanguages** [comment]
@ZenithRogue Okay, let's do that, but let's first see if someone has any ideas on how to fix this.

**Comment by ZenithRogue** [comment]
Here is a preview of the warning line:
image

**Comment by WorldLanguages** [comment]
@ZenithRogue "warn" is a nice idea I also thought about, however I'd prefer it being a `confirm()` when enabling the addon - by the point the warning is visible, the user already enabled the addon.
Please let me work on the implementation details of "warn" (do not make any new changes to the PR), I think I'll rename it and change it to what I just said (use confirm dialog).

**Comment by ZenithRogue** [comment]
I don't think the warn needs to be complicated. Simple red text in the description line is fine imo

**Comment by WorldLanguages** [comment]
@ZenithRogue But the warning would sometimes not be visible until the user turns the addon on :s

**Comment by JeffaloBob** [comment]
does the same issue happen with better3.0's implementation?

**Comment by WorldLanguages** [comment]
@JeffaloBob yes

**Comment by Hans5958** [comment]
I'm sorry to tell you, but due to my mistake on the end, I accidentally force-pushed into the master branch, closing this pull request as the result. I have reversed the changes, but I can't reopen the pull request, so you need to make another pull request for this one.

Once again, I apologize for the inconvenience that caused from my mistake.

**Comment by WorldLanguages** [comment]
@ZenithRogue, please reopen a PR to the same branch

**Pull request closed without merging**
