### PR TITLE
New warnings and notices system

### LINKED ISSUE #744: Change how warning and notice texts are added
Instead of creating two properties for them, how about creating an array of objects that cover both properties? The object includes the type and the content of the texts.

This may give multiple benefits.
- Easier implementation because you don't need to check additional properties (or other reasons perhaps?)
- Cleaner manifest because they are stored in a single array.
- Ability to add multiple warning and notice texts (probably?)
- Ability (in the source code) to add additional, separate warning text for some cases (like when it uses addon traps)

### PR DESCRIPTION
**Pull request by TheColaber**
**Resolves**

Resolves #744

**Changes**

New addon.json format...
In order to add notices or warnings it will look like this:
```json
{
  "extra": [
    {
      "type": "notice",
      "text": "Example notice.",
      "id": "exmapleID"
    },
    {
      "type": "warning",
      "text": "Example warning.",
      "id": "exmapleID"
    },
  ],
}
```

**Reason for changes**

This allows for multiple warnings and notices like this:
image

**Tests**

I need to confirm I added the notices for all the addons.
Also, someone would need to update the Wiki when this gets merged

### CODE REVIEW

**Comment by YOYITsM3M8** [comment]
If this gets accepted will I need to change the notice in my new addon? #951

**Comment by TheColaber** [comment]
Yeah

**Comment by Hans5958** [comment]
Nice, but can you put a descriptive PR title?

**Comment by WorldLanguages** [comment]
I mean, fine, but looks unnecessary? The localization code will need to be tweaked a bit for this as well.

**Comment by TheColaber** [comment]
> I mean, fine, but looks unnecessary? The localization code will need to be tweaked a bit for this as well.

How exactly?

**Comment by apple502j** [comment]
Waiting Hans for schema update. I can do l10n stuff myself

**Comment by Hans5958** [comment]
> 
> 
> Waiting Hans for schema update. I can do l10n stuff myself

I said you don't need to wait for me, smh

**Comment by WorldLanguages** [comment]
@Hans5958 Lol this is partially why I dislike PR tags, you keep adding and removing "do not merge" :P

**Comment by Hans5958** [comment]
Okay, here's something: Why is it called `extra`? Would it be more informative to do it as `info` or `extraInfo`?

**Comment by GrahamSH-LLK** [comment]
> Okay, here's something: Why is it called `extra`? Would it be more informative to do it as `info` or `extraInfo`?

Agreed. Extra is weird. Info is better.

**Comment by WorldLanguages** [comment]
Info sounds good.

**Comment by Hans5958** [comment]
Another idea: Maybe how about making it `notice` instead (since both types of it are all notices) and changing the `notice` type into something like `info` (like how `console.info()` works)

Speaking of which, I still don't know why we didn't have a less scary colors such as light blue and yellow instead of yellow and red, but that's #742.

**Comment by TheColaber** [comment]
I need a final confirmation before I spend a bit of time changing stuff..
- I should change `extra` to `info`

or

- I should change `extra` to `notice` and change the current `notice` to info

~~and maybe change the colors~~?

**Comment by apple502j** [comment]
Can't we make notice/warning an array instead?

**Comment by Hans5958** [comment]
> 
> 
> Can't we make notice/warning an array instead?

It is an array?

**Comment by Hans5958** [comment]
Another one: ID for every `info`, for translation purposes

**Comment by apple502j** [comment]
Yeah. How about:
```json
{
"warnings": [ { "id": "xxx", "content": "Lorem Ipsum!" } ]
}
```

**Comment by TheColaber** [comment]
Comment Updated, Check Above

**Comment by Hans5958** [comment]
> 
> 
> Yeah. How about:
> 
> ```json
> {
> "warnings": [ { "id": "xxx", "content": "Lorem Ipsum!" } ]
> }
> ```

Note that the PR and the issue calls for merging two of the properties into one single array, not just having both of them change into bunch of arrays.

**Comment by Hans5958** [comment]
@TheColaber - Yeah, you should add IDs. The l10n system is going to need it anyways.

**Pull request merged**
