### PR TITLE
Change colors of extension icons based on background and block color

### PR DESCRIPTION
**Pull request by mxmou**
### Changes

Updates editor dark mode and customizable block colors addons to change the colors of extension icons in the category menu. The affected icons are debugger, music, video sensing, and text to speech.

### CODE REVIEW

**Review by DNin01 — APPROVED** [review]
Nice! (You mean these, right?)
Category icons adapted to the dark background

**Review by Samq64 — APPROVED** [review]
> debugger

That icon doesn't seem to change. Everything else looks good.

**Comment by Samq64** [comment]
> It changes when the "Scratch Addons blocks" setting in `editor-theme3` is changed.

Looks good.
image

**Comment by WorldLanguages** [comment]
@mxmou Merge?

**Pull request merged**
