### PR TITLE
Small grammar fix

### PR DESCRIPTION
**Pull request by Mast3rGenius**
Grammar fix and security thing.

### CODE REVIEW

**Comment by RedGuy12** [comment]
1. The grammar is fine
2. Noreffer and noopener are not for security, it's to tell Google not to follow the link. But there's no way for google to FIND the link, much less follow it.
________________________________
From: Mast3rGenius ***@***.***>
Sent: Monday, May 3, 2021 6:19:23 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] Small grammar fix (#2366)


Grammar fix and security thing.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ScratchAddons/ScratchAddons/pull/2366

Commit Summary

  *   Fix grammar
  *   Update userscript.js

File Changes

  *   M addons-l10n/en/editor-devtools.json<https://github.com/ScratchAddons/ScratchAddons/pull/2366/files#diff-1748b451da5a9e4fe32e993e335b7c983ecf6283b88039121f00363c8f012032> (2)
  *   M addons/editor-devtools/userscript.js<https://github.com/ScratchAddons/ScratchAddons/pull/2366/files#diff-6ebfe2365649609b78dbdd6bf77bbf0caac93418c48a01599ec8b38fa3ce6699> (2)

Patch Links:

  *   https://github.com/ScratchAddons/ScratchAddons/pull/2366.patch
  *   https://github.com/ScratchAddons/ScratchAddons/pull/2366.diff

**Comment by Mast3rGenius** [comment]
The grammar is wrong and norefferer/noopener are best practice

**Comment by apple502j** [comment]
While noopener IS a security feature, it's on by default so not a priority

**Comment by GrahamSH-LLK** [comment]
The grammar _is_ wrong, as a native english speaker. I'll fix in a new PR

**Pull request closed without merging**
