### PR TITLE
SECURITY.md file changes

### PR DESCRIPTION
**Pull request by WorldLanguages**
Changes:
- Move file to `/.github` folder (GitHub accepts this)
- Update email to `security@scratchaddons.com`
- Clarify English is the preferred language for reports
- Avoid second person "you"
- Clarify that vulnerabilities may also be found in other repositories, such as the website-v2 repo
- Offer a link to the list of supported browsers
- Clarify that reports may be anonymous and that the reporter may ask to be credited

**Click to read new formatted markdown file:** https://github.com/WorldLanguages/ScratchAddons/blob/security-md-changes/.github/SECURITY.md

***

TODOs:
- [x] Update email to `security@scratchaddons.com`
- [x] Better wording
- [x] Clarify English is the preferred language for reports
- [x] Link to the repository instead of saying "this repository"
- [ ] Copy this new SECURITY.md into website-v2 docs
- [ ] Host a security.txt file with the same data (following the standard) in scratchaddons.com/.well-known/security.txt and scratchaddons.com/security.txt

### CODE REVIEW

**Comment by RedGuy12** [comment]
Can we also move CODE_OF_CONDUCT.md and CONTRIBUTING.md to .github? In my experience, GitHub can find those files fine when they are in there.

**Comment by WorldLanguages** [comment]
We'll need to fix any potential broken links, we shouldn't forget

**Comment by Hans5958** [comment]
Is this still up?

**Comment by WorldLanguages** [comment]
@Hans5958 Yep - are you asking for any particular reason?

**Comment by WorldLanguages** [comment]
You are welcome to send test emails to `security@scratchaddons.com` until December 7th.
I will be reading through every email that arrives to that address, including ones caught by the spam filter.

**Comment by WorldLanguages** [comment]
Suggested `security.txt` file:

```
Contact: mailto:security@scratchaddons.com
Expires: 2025-01-01T00:00:00.000Z
Preferred-Languages: en
Policy: https://github.com/ScratchAddons/ScratchAddons/security/policy
```

**Comment by WorldLanguages** [comment]
Thanks @lisa-wolfgang for helping with latest commit.

**Review by apple502j — APPROVED** [review]

**Comment by Hans5958** [comment]
> "The most recent release of the Scratch Addons browser extension should be secure..."

This seems a little bit presumptuous. A reason of having these kind of security policies is that there could be a time where we found out that it is not as secure as we think. I would prefer a more toned-down variation such as "is known to be secure", or change/remove the word "secure" into something.

**Comment by WorldLanguages** [comment]
> > The most recent release of the Scratch Addons browser extension should be secure...
> 
> This seems a little bit presumptuous. A reason of having these kind of security policies is that there could be a time where we found out that it is not as secure as we think. I would prefer a more toned-down variation such as "is known to be secure", or change/remove the word "secure" into something.

By "should", I intended to indicate obligation, not expectation. Maybe I should have used "must" instead.

**Comment by Hans5958** [comment]
I forgot the word should is there. Maybe it's fine for now, but you may change it I guess.

**Comment by RedGuy12** [comment]
"Must" makes it sound like it's the users' job.

**Comment by WorldLanguages** [comment]
> I forgot the word should is there. Maybe it's fine for now, but you may change it I guess.

I will keep it as "should" for now, unless 2 native English speakers can agree on a better word.

**Comment by WorldLanguages** [comment]
TODO: commit https://github.com/ScratchAddons/ScratchAddons/pull/5307/commits/270dba75ca7b83cfbc4f42ae3820c3ce0aac767c removed paragraph separation

**Comment by BroJac5246** [comment]
> > I forgot the word should is there. Maybe it's fine for now, but you may change it I guess.
> 
> I will keep it as "should" for now, unless 2 native English speakers can agree on a better word.
My take as a native English speaker:

"Must be" implies a guarantee that SA is secure, which we obviously can't claim.

"Should" doesn't exactly convey responsibility (because of the context), but it still fits with the surrounding text and could definitely be kept if nothing better is found.

We could outright state that it is SA's responsibility for SA to be secure, but that brings us back to the issue with "must".

**Ultimately, however, the correct choice comes down to the meaning that we want to convey**, which would obviously change the wording:
- If we want to simply state that newer versions of SA are likely to be more secure, then "should" as we currently have it will work fine.
- If we want to convey that SA _has a responsibility_ to keep the extension secure, then I'd rephrase the paragraph (or create a new one) that basically states that SA will attempt to be secure, but things may slip through.

**Review by Samq64 — APPROVED** [review]

**Comment by WorldLanguages** [comment]
Waiting for Hans pending review

**Comment by Hans5958** [comment]
So, no changes on the said wording?

**Review by apple502j — CHANGES_REQUESTED** [review]
Blocking merge, see above

**Comment by WorldLanguages** [comment]
> So, no changes on the said wording?

I thought you said it was fine, but I'll see how it could be rephrased

**Review by apple502j — APPROVED** [review]

**Review by TheColaber — APPROVED** [review]

**Comment by Hans5958** [comment]
Okay, then. This can be changed later.

**Pull request merged**
