### PR TITLE
Editor Hotkeys Addon

### PR DESCRIPTION
**Pull request by TheColaber**
**Changes**

Allows you to set your hotkeys in the settings and use them in the editor.
Note:

**Reason for changes**

Convenienciness

**Tests**

Works on chrome.

### CODE REVIEW

**Comment by GrahamSH-LLK** [comment]
_Awesome!_ That looks great!

**Comment by TheColaber** [comment]
> _Awesome!_ That looks great!

Thanks. If there are any other hotkey settings you guys think there should be, tell me.

**Comment by GrahamSH-LLK** [comment]
Are you getting console errors? I am...

**Comment by TheColaber** [comment]
> Are you getting console errors? I am...

No... when doing what?

**Comment by GrahamSH-LLK** [comment]
Also, the input needs some work. When I did Ctrl + Shift + u, I got Ctrl + Shift + PROCESSu (it's already a hotkey). Similar things happen with Ctrl + Shift + (number). Shift makes the numbers change into symbols

**Comment by TheColaber** [comment]
> Also, the input needs some work. When I did Ctrl + Shift + u, I got Ctrl + Shift + PROCESSu (it's already a hotkey). Similar things happen with Ctrl + Shift + (number). Shift makes the numbers change into symbols

"PROCESSu"??

**Comment by GrahamSH-LLK** [comment]
> "PROCESSu"??

It's the unicode input key, I have no idea.

**Comment by TheColaber** [comment]
@GrahamSH-LLK Can you try again to find if there are any bugs now? Also, Idk how you got PROCESSu... Maybe it may work now??

**Comment by TheColaber** [comment]
@GrahamSH-LLK Also, this new code is untested, I'm pretty sure the settings will work, but not so sure that the new settings will work with the new code for the editor.

**Comment by TheColaber** [comment]
@WorldLanguages Review?

**Comment by WorldLanguages** [comment]
@TheColaber As I said in another issue, you're not supposed to add new manifest properties or add new capabilities to the settings page without creating an issue first.

**Comment by TheColaber** [comment]
> @TheColaber As I said in another issue, you're not supposed to add new manifest properties or add new capabilities to the settings page without creating an issue first.

ok. Can you close this and I'll make two separate ones?

**Comment by GrahamSH-LLK** [comment]
> ok. Can you close this and I'll make two separate ones?

An issue, not a PR.

**Comment by TheColaber** [comment]
> > ok. Can you close this and I'll make two separate ones?
> 
> An issue, not a PR.

Ah, ok. I'll do that later.

**Comment by WorldLanguages** [comment]
@TheColaber Please open an issue explaining the new proposed `"key"` setting type, and make a new PR that only adds support for it, without adding any addons (you can reuse the code from this PR!). After that one is merged, we can discuss a better hotkey addon, and how it should play with griffpatch's developer tools hotkeys.

**Comment by TheColaber** [comment]
Alright.

**Pull request closed without merging**
