### PR TITLE
Add `user-select: none` and `draggable=false` to some elements in the extension UI

### PR DESCRIPTION
**Pull request by mxmou**
### Changes

Popup after pressing Ctrl+A on v1.38.2:
image

After this PR:
image

Longer blocks of text, such as addon descriptions on the settings page and comments in the Messaging popup, can still be selected. `draggable="false"` was added to all images except the screenshot on the Permissions page.

### Tests

Tested on Edge and Firefox.

### CODE REVIEW

**Comment by Samq64** [comment]
I think addon names and maybe also setting names should stay selectable.

**Comment by Samq64** [comment]
Is there a way to make all SVGs non-draggable by default?

**Comment by mxmou** [comment]
> Is there a way to make all SVGs non-draggable by default?

I don't think so - Chrome supports the non-standard CSS property `-webkit-user-drag` but there's no equivalent in Firefox. Inline SVGs are non-draggable by default and it's also easier to change their color in light mode, but switching to those would be more complex than adding the draggable attribute to every icon.

**Review by WorldLanguages — APPROVED** [review]
Untested

**Comment by DNin01** [comment]
> > Is there a way to make all SVGs non-draggable by default?
> 
> I don't think so - Chrome supports the non-standard CSS property `-webkit-user-drag` but there's no equivalent in Firefox. Inline SVGs are non-draggable by default and it's also easier to change their color in light mode, but switching to those would be more complex than adding the draggable attribute to every icon.

Would using inline SVGs be viable with a build step?

**Comment by hueychen27** [comment]
How about the version and the "Scratch Addons" name be selectable too?

**Comment by mxmou** [comment]
@WorldLanguages Do you think this could be merged for v1.40 or v1.41? Also #4656, which has been open for over two years and there haven't been any objections.

**Comment by Samq64** [comment]
Could the version number in the popup header and game titles stay selectable?

**Comment by mxmou** [comment]
> Could the version number in the popup header and game titles stay selectable?

Being able to copy the version number can be useful, but I'm not sure about cloud game titles. Project titles in the Messaging tab have always been unselectable.

**Review by Samq64 — APPROVED** [review]

**Pull request merged**
