### PR TITLE
Create CHANGELOG.md

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
This adds a changelog.md re #463

### CODE REVIEW

**Review by wgyt735yt — APPROVED** [review]
This changelog looks great, and everything looks right.

**Comment by Explosion-Scratch** [comment]
Nice! Thanks!

**Comment by WorldLanguages** [comment]
I do not like the idea of a changelog.md, I'd still like to have release notes within "releases" and with this file it would have to get duplicated

**Comment by Hans5958** [comment]
> 
> 
> I do not like the idea of a changelog.md, I'd still like to have release notes within "releases" and with this file it would have to get duplicated

I agree. I also don't like we have another page on the website because the GitHub releases page is already tidy enough for users to see.

By the way, go to #463?

**Comment by GrahamSH-LLK** [comment]
I'm closing this for now.

**Pull request closed without merging**
