### PR TITLE
Combine bugfixes into one addon

### LINKED ISSUE #2562: Remove addons that just fix bugs
### Is your request related to a problem? Please describe.

There are currently at least two addons that just fix Scratch issues: "Do not automatically run duplicated blocks" and "Fix broken SVG uploads", and there used to be a Load more scrolling fix addon. Scratch has many bugs so adding addons for all of them would make the number of addons very large.

### Describe the solution you'd like

Either of the following:

* Remove addons that only contain bug fixes and no additional functionality.
* Make an addon that is enabled by default and contains multiple bug fixes instead of creating a different addon for every bug.

### PR DESCRIPTION
**Pull request by lisa-wolfgang**
Resolves #2562

### Changes

"Fix broken SVG uploads" and "Do not automatically run duplicated blocks" have been combined into "Fix Scratch bugs". This new addon is recommended and enabled by default.

### Reason for changes

~~Because Maximouse said so~~ To have all bugfixes in one convenient location and to make it easier to add new bugfixes in the future

### Tests

Both of the imported addons seem to still work properly.

### Some considerations

- If this is merged into v1.15.0, it could be unclear that a new bugfix (duplicated blocks) was added as well.
- There are only two bugfixes right now, which looks a little pathetic. However, this would provide a framework for future bugfixes to be added.
- Although the addon as a whole is enabled by default, any bugfixes added in future updates wouldn't necessarily be enabled by default. Remember that addon options also have default settings, so we can set this for each individual bugfix. However, users might expect any future bugfixes added to be enabled by default due to the nature of the addon.

### CODE REVIEW

**Comment by RedGuy12** [comment]
This needed more discussion...
________________________________
From: lisa-wolfgang ***@***.***>
Sent: Saturday, May 22, 2021 9:41:10 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] Combine bugfixes into one addon (#2568)


Resolves #2562<https://github.com/ScratchAddons/ScratchAddons/issues/2562>

Changes

"Fix broken SVG uploads" and "Do not automatically run duplicated blocks" have been combined into "Fix Scratch bugs". This new addon is recommended and enabled by default.

Reason for changes

Because Maximouse said so To have all bugfixes in one convenient location and to make it easier to add new bugfixes in the future

Tests

Both of the imported addons seem to still work properly.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ScratchAddons/ScratchAddons/pull/2568

Commit Summary

  *   Combine bugfixes into one addon
  *   Format code

File Changes

  *   M addons/addons.json<https://github.com/ScratchAddons/ScratchAddons/pull/2568/files#diff-bb33cb076f6d0e3d6cfe187036954a1ca81e6bf0b7f141f578f4805426fa48e7> (3)
  *   A addons/bugfixes/addon.json<https://github.com/ScratchAddons/ScratchAddons/pull/2568/files#diff-977f4620158ce9ff87f78af4fd5d8bdc5d79d9e87e8befbfbc85a4b7b163d6fd> (45)
  *   R addons/bugfixes/fix-pasted-scripts.js<https://github.com/ScratchAddons/ScratchAddons/pull/2568/files#diff-4e9863a2297bb82466fb97217645dd9a55760eb353b4293bb07791a1f893b734> (11)
  *   R addons/bugfixes/fix-uploaded-svgs.js<https://github.com/ScratchAddons/ScratchAddons/pull/2568/files#diff-62af5d42768d074725cef78e18fa3038958cd6a1ee9e33a092025261600e719b> (2)
  *   D addons/fix-pasted-scripts/addon.json<https://github.com/ScratchAddons/ScratchAddons/pull/2568/files#diff-6c2892cd9ff7dadf85d3ff064eeab9614019a5670ad15bff792c5e372f37443a> (30)
  *   D addons/fix-uploaded-svgs/addon.json<https://github.com/ScratchAddons/ScratchAddons/pull/2568/files#diff-3893773c1feab20eddc19935f6b0df645ac6705a5fffddf2c5d43d516551aa67> (15)

Patch Links:

  *   https://github.com/ScratchAddons/ScratchAddons/pull/2568.patch
  *   https://github.com/ScratchAddons/ScratchAddons/pull/2568.diff

**Comment by lisa-wolfgang** [comment]
We can continue to discuss here.

**Comment by WorldLanguages** [comment]
Maybe for v1.16.0

**Comment by lisa-wolfgang** [comment]
I just added a fix for comment dragging that worked when I made it, but it doesn't appear to work now because my computer is sluggish and needs to be restarted. It could be that the addon is loading faster than the `vm.editingTarget`, as indicated by the console error.

**Comment by WorldLanguages** [comment]
I'm closing this for now I guess. IMO they should be separate addons until we add a way to have a help modal in individual settings, otherwise we can't provide enough context to the user on what's being fixed (this would remove all mentions to Affinity Designer)
Small bug fixes could be merged an addon like this, but these aren't small bugs I'd say.

**Comment by lisa-wolfgang** [comment]
Perhaps a new tag for bugfix addons would be better?

**Comment by Secret-chest** [comment]
> Perhaps a new tag for bugfix addons would be better?

@lisa-wolfgang Yes, definitely. I think it is better to let the user choose bugfixes, intsead of all bugfixes or no bugfixes.

**Pull request closed without merging**
