### PR TITLE
Fix a couple bugs from #4810

### PR DESCRIPTION
**Pull request by Samq64**
Fixes https://github.com/ScratchAddons/ScratchAddons/pull/4930#issuecomment-1200446217 and incorrect icon preload path. Tested on Chromium 103.

### CODE REVIEW

**Comment by mxmou** [comment]
Ideally the solution would be consistent with buttons, which #4930 changed back to orange.

**Comment by Samq64** [comment]
> Ideally the solution would be consistent with buttons, which #4930 changed back to orange.

They're now consistently orange.

**Comment by OregSamSas** [comment]
I think it's better to have it as blue in beta versions, but then it seems I'm the only one who's thinking like this.

**Review by apple502j — APPROVED** [review]

**Comment by mxmou** [comment]
> I think it's better to have it as blue in beta versions, but then it seems I'm the only one who's thinking like this.

I don't think the exact color is very important, it just has to be the same for inputs and buttons.

**Review by mxmou — APPROVED** [review]

**Pull request merged**
