### PR TITLE
Fix some RTL bugs in webpages

### PR DESCRIPTION
**Pull request by mxmou**
### Changes

Fixes incorrect RTL styles.

### Reason for changes

The Arabic translation might be added soon. (#5254)

### Tests

Tested by adding English to `rtl-list.js`.

### CODE REVIEW

**Review by apple502j — APPROVED** [review]

**Comment by WorldLanguages** [comment]
Note that, technically, we shouldn't be using `margin-inline-start` because it won't work in Chrome 80-87.
But supporting RTL in modern Chrome is more important than inexistent margins in old Chrome, which few people use.

Here's how the settings page (rtl-fixes branch) looks in Chrome 80, in case you're curious (the checkboxes look good in Chrome 84+ however):
image

**Review by WorldLanguages — APPROVED** [review]

**Comment by RedGuy12** [comment]
Related: `document.body.dir` is set without regard to `rtl-list.js`'s values:
https://github.com/ScratchAddons/ScratchAddons/blob/48106c8599fca407ded70aeb073085cd7b6b655a/webpages/set-lang.js#L4

**Comment by WorldLanguages** [comment]
@RedGuy12 False alarm - look at the implementation for getDirection. It works as intended.

**Comment by mxmou** [comment]
> Note that, technically, we shouldn't be using `margin-inline-start` because it won't work in Chrome 80-87. But supporting RTL in modern Chrome is more important than inexistent margins in old Chrome, which few people use.
> 
> Here's how the settings page (rtl-fixes branch) looks in Chrome 80, in case you're curious (the checkboxes look good in Chrome 84+ however)

Would adding prefixed versions of the properties (`-webkit-margin-start` and `-webkit-margin-end` for margins, `-webkit-appearance` for checkboxes) fix that?

**Comment by WorldLanguages** [comment]
> Would adding prefixed versions of the properties (`-webkit-margin-start` and `-webkit-margin-end` for margins, `-webkit-appearance` for checkboxes) fix that?

Good idea, forgot those existed.
Not worth it, because we'll need to drop many Chrome versions after updating to MV3 anyway.

**Comment by WorldLanguages** [comment]
This can be merged, right?

**Pull request merged**
