### PR TITLE
Changes to `editor-theme3/addon.json`

### PR DESCRIPTION
**Pull request by WorldLanguages**
### Changes

- Remove credits to unreachable developer.
- Add info note clarifying what an "insertion marker" is.

### CODE REVIEW

**Comment by WorldLanguages** [comment]
cc @sfederici

**Comment by Samq64** [comment]
I wonder if anyone can think of an easier to understand term so the note isn't necessary?

**Comment by WorldLanguages** [comment]
It can be moved to a "setting description" later.

**Review by Samq64 — APPROVED** [review]

**Review by TheColaber — APPROVED** [review]

**Comment by mxmou** [comment]
> I wonder if anyone can think of an easier to understand term so the note isn't necessary?

I don't think there's a commonly used name for this feature (other than "insertion marker", which is used by the developers).

**Pull request merged**
