### PR TITLE
Stage left button order (#3937)

### LINKED ISSUE #3937: New addon: reverse stage button order
### Is your request related to a problem? Please describe.

Scratch 2.0 addons are almost complete, but we need this

### Describe the solution you'd like

Change the stage button order to be like Scratch 2.0 (green flag on the right, full screen on the left)

### Describe alternatives you've considered

None

### PR DESCRIPTION
**Pull request by Norbiros**
Resolves #3937
Updates this PR: #2010

### Changes

Add feature that [TheColaber](https://github.com/ScratchAddons/ScratchAddons/pull/2010#issuecomment-821754505) proposed to WL's PR. 

### Tests

Everything works great - Firefox 95.
Screenshot from 2022-05-30 18-51-04

### Other

I know that @mxmou is assigned to that PR, but I already did [it](https://github.com/ScratchAddons/ScratchAddons/pull/2010#issuecomment-821754505).
Also, I don't know if that should work like that, but this functionality affects project even if you are not in the editor.

### CODE REVIEW

**Comment by mxmou** [comment]
This is useful even if the stage is not on the left so I think it should be a new addon.

**Comment by WorldLanguages** [comment]
@mxmou Could you elaborate on why? For RTL reasons?

**Comment by Secret-chest** [comment]
> @mxmou Could you elaborate on why? For RTL reasons? 

Scratch 1.4 had them flipped too but the stage was on the right

**Comment by mxmou** [comment]
> @mxmou Could you elaborate on why? For RTL reasons?

Mainly because this addon affects the project page but editor-stage-left does not. @Secret-chest is right about Scratch 1.4 too.

**Pull request closed without merging**
