### PR TITLE
Fix forum-quote-code-beautifier tag

### LINKED ISSUE #988: Forum quote/code block beautifier is in editor addons
**Describe the bug**

The forum quote/code block beautifier addon is in the "scratch editor features" section of the extension settings. 

**To Reproduce**

1. Go to the scratch addons settings
2. Click on 'Scratch editor features'
3. Scroll down to 'Customized quotes & code blocks on forums'
5. Alternatively, try to find it in "scratch website features" or "themes".

**Expected behavior**

The "Customized quotes & code blocks on forums" should not be in the editor section, and should be in either website features or themes.

**Screenshots**

image

**Device (please complete the following information):**

- OS: windows 10
- Browser: chrome 87
- Version: scratch addons 1.5.0-prerelease

**Additional context**

n/a

### PR DESCRIPTION
**Pull request by apple502j**
Resolves #988

### CODE REVIEW

**Comment by GrahamSH-LLK** [comment]
I think this isn't a full fix. Our logic is obviously broken if it does _this_. Forums != editor!

**Comment by apple502j** [comment]
@GrahamSH-LLK All addons need at least one of the three tags. This should have been in the schema.

**Comment by pufferfish101007** [comment]
@apple502j If it's one of those **three** tags that is required, the wiki needs updating, as at the moment is says that one out of `community` and `editor` is required, and you can include one or more optional tags out of `theme` and a few others - theme should be one of the required options.

**Comment by WorldLanguages** [comment]
> All addons need at least one of the three tags

Two tags, actually. Adding "theme" does change the category, and also shows a tag "for website" or "for editor" depending on those other tags.

**Pull request merged**
