### PR TITLE
Remove sourceMap from Comlink

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
Since the sourceMap doesn't exist at this location (it's not even in the repo!), this is 100% unneccesary.
It also removes a warning because there's no missing source map.

### CODE REVIEW

**Comment by WorldLanguages** [comment]
Don't we want to use the library as-is? We'd be modifying it by doing this

**Comment by TheColaber** [comment]
Didn't you convert it from ts to js anyway?

**Comment by GrahamSH-LLK** [comment]
> Didn't you convert it from ts to js anyway?

No, that was comlink-extension.

> Don't we want to use the library as-is? We'd be modifying it by doing this

Yes, BUT this adds a warning in the console whenever SA is enabled.

**Comment by WorldLanguages** [comment]
> Yes, BUT this adds a warning in the console whenever SA is enabled.

Then let's add an empty source map file so that it won't complain :P

**Comment by GrahamSH-LLK** [comment]
> > Yes, BUT this adds a warning in the console whenever SA is enabled.
> 
> Then let's add an empty source map file so that it won't complain :P

I'm just gonna add the actual one.

**Comment by RedGuy12** [comment]
> > > Yes, BUT this adds a warning in the console whenever SA is enabled.
> > 
> > 
> > Then let's add an empty source map file so that it won't complain :P
> 
> I'm just gonna add the actual one.

that references other files that aren't in the repo tho...wouldn't devtools complain about that

**Comment by WorldLanguages** [comment]
Exactly, at that point an empty source map would be better

**Comment by GrahamSH-LLK** [comment]
> Exactly, at that point an empty source map would be better

Yes, but I bet devtools will complain about that!

**Comment by apple502j** [comment]
People need to learn to ignore warnings.

**Comment by WorldLanguages** [comment]
> Yes, but I bet devtools will complain about that!

Have you tested if it does...?

**Pull request closed without merging**
