### PR TITLE
Rename hide-signatures

### PR DESCRIPTION
**Pull request by DNin01**
I'm not totally sure why it had to be "Hide signatures _on_ forums".

### CODE REVIEW

**Comment by WorldLanguages** [comment]
Looks like the addon author initially named it `Hide signatures in forums` (pretty much the same): https://github.com/FunctionalMetatable/ScratchAddons/commit/1b376084e2a14a5ee4126fb80f20573f00ca9fc4#diff-71564b07538b4c97f01941d973083a8cd693c5e8881bc3f3480e9a1a00ca42b5R2

**Comment by mxmou** [comment]
"Hide forum signatures" still isn't a noun. "Hidden forum signatures" or "Forum signature hiding" would be, but in this case it's more important that the name is easy to understand.

**Comment by BroJac5246** [comment]
> "Hide forum signatures" still isn't a noun. "Hidden forum signatures" or "Forum signature hiding" would be, but in this case it's more important that the name is easy to understand.

I agree, it's more important to be concise.

**Review by BroJac5246 — APPROVED** [review]

**Comment by WorldLanguages** [comment]
@mxmou To clarify, you aren't opposed to this change, right? In that case, I would go ahead with merging this.

**Comment by WorldLanguages** [comment]
If #6009 is implemented, we could rename this to simply `Hide signatures`.

**Comment by mxmou** [comment]
> @mxmou To clarify, you aren't opposed to this change, right? In that case, I would go ahead with merging this.

I like the change, I just didn't understand the original explanation.

**Review by WorldLanguages — APPROVED** [review]

**Comment by WorldLanguages** [comment]
How on earth did this break Prettier?

**Pull request merged**
