### PR TITLE
Cat Blocks!

### PR DESCRIPTION
**Pull request by TheColaber**
**Changes**

Addon that changes blocks to cat blocks!

**Reason for changes**

People love 'em!

**Tests**

Works on chrome!

// Todo: added blinking and ear folding

### CODE REVIEW

**Comment by Cool-Scratcher** [comment]
Wow, that sounds like an amazing feature :D I'd love to see it!

**Comment by GrahamSH-LLK** [comment]
Because this was generated from your master branch, which has those changes.

**Comment by GrahamSH-LLK** [comment]
Also, this needs more padding. 
image

**Comment by TheColaber** [comment]
> Also, this needs more padding.
> image

Oh yeah... one sec...

**Comment by GrahamSH-LLK** [comment]
> > Also, this needs more padding.
> > image
> 
> Oh yeah... one sec...

34 minutes later:

**Comment by TheColaber** [comment]
> > > Also, this needs more padding.
> > > image
> > 
> > 
> > Oh yeah... one sec...
> 
> 34 minutes later:

I realized it was an SVG and needs to use translate, not margin, padding... lol... it's hard stuff.

**Comment by TheColaber** [comment]
I wasn't able to do it... If anyone wants to try, they can.

**Comment by WorldLanguages** [comment]
Can you please remove changes to other unrelated addons.

**Comment by TheColaber** [comment]
> Can you please remove changes to other unrelated addons.

Maybe because I did changes to the main branch it hooked on... How do you remove them?

**Comment by RedGuy12** [comment]
resolves #143

**Comment by MasimbaTheHuman** [comment]
> resolves #143

Are you even authorized to do that?

**Comment by RedGuy12** [comment]
idk
________________________________

**Review by MasimbaTheHuman — APPROVED** [review]

**Pull request merged**
