### PR TITLE
Cloud games open in new tab

### LINKED ISSUE #496: Ability to open the cloud games in a new tab from within the cloud games addon
**Is your feature request related to a problem? Please describe.**

You can't directly open the cloud games in a new tab from within the cloud games addon.

**Describe the solution you'd like**

Add a button that allows opening the cloud games in a new tab.

### PR DESCRIPTION
**Pull request by BoomerScratch**
**Resolves**

Resolves #496 

**Reason for changes**

So you can directly open the cloud games from the addon.

**Tests**

Tested with developer mode. However, the text turns blue. Is that okay?

### CODE REVIEW

**Comment by BoomerScratch** [comment]
#500 🎉
<sub>Do squash merge again

**Comment by WorldLanguages** [comment]
> However, the text turns blue. Is that okay?

Please keep it white

**Comment by Hans5958** [comment]
How about making it underlined on hover?

**Review by WorldLanguages — APPROVED** [review]

**Comment by Hans5958** [comment]
Bruh ghosted

**Comment by WorldLanguages** [comment]
@Hans5958 It appeared to be underlined on hover, unless I misunderstood

**Comment by GrahamSH-LLK** [comment]
🎉 #500!

**Comment by YOYITsM3M8** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉
#500 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by Explosion-Scratch** [comment]
Yay!!!

**Pull request merged**
