### PR TITLE
Custom block arg switching

### LINKED ISSUE #557: Allow right-clicking a function parameter call (in the function's definition) to replace it with a dropdown, like variables.
I'm not sure how it would work when it's in a block of code floating outside of the function, it could possibly allow selection of parameters from all functions, but it would be an improvement over having to drag another one in.

### PR DESCRIPTION
**Pull request by pufferfish101007**
Resolves #557

### Changes

Adds an option to block-switching to replace custom block args. Options are off (no arg switching), only in custom block definitions, and all (every arg can be replaced with any other arg anywhere). Note that boolean and string/num args can't be switched between.

### Reason for changes

'Tis useful and easy.

### Tests

Tested on chrome.

### Additional notes

The settings probably need a change of wording.

### CODE REVIEW

**Comment by GarboMuffin** [comment]
merge https://github.com/pufferfish101007/ScratchAddons/pull/4 and I approve

**Comment by WorldLanguages** [comment]
> The settings probably need a change of wording.

Can you explain what the difference between "only in custom block definitions" and "all" is? I haven't tested this and I can't seem to be able to figure out without trying it out.

**Comment by pufferfish101007** [comment]
> merge [pufferfish101007#4](https://github.com/pufferfish101007/ScratchAddons/pull/4) and I approve

Merged, thanks.

> > The settings probably need a change of wording.
> 
> Can you explain what the difference between "only in custom block definitions" and "all" is? I haven't tested this and I can't seem to be able to figure out without trying it out.

I'll show you some screenshots. In each one, I've circled the block that's been right-clicked.
- "only in custom block definitions":
Screenshot_20210816-101657_Browser
Screenshot_20210816-101344_Browser
Screenshot_20210816-101249_Browser
- "all": 
Screenshot_20210816-102100_Browser
Screenshot_20210816-102026_Browser
Screenshot_20210816-102003_Browser


Basically in definition only mode, you'll only get the switch menu when the arg is in a custom block definition and belongs to that custom block. In all mode, you can switch any arg to any other arg of the same type (in the same sprite), regardless of where in the code it is.

**Comment by WorldLanguages** [comment]
Oof, that's something complex to explain...

**Comment by WorldLanguages** [comment]
Okay, settings name is longer, but it's easier to dismiss now because checkbox and mode are separate.

image

**Review by WorldLanguages — APPROVED** [review]

**Comment by pufferfish101007** [comment]
> Okay, settings name is longer, but it's easier to dismiss now because checkbox and mode are separate.
> 
> image

Coolio, thanks :D

**Comment by RedGuy12** [comment]
I was thinking "only trigger in custom blocks" for the setting name

Too late now lol



________________________________

**Pull request merged**
