### PR TITLE
Add custom style for checkboxes

### LINKED ISSUE #763: Edge Setting Switches always look disabled!
**Describe the bug**

For every checkbox they look disabled

**To Reproduce**

1. Go to Settings on Edge
2. Click on Enable an addon that has a checkbox

**Expected behavior**

To look blue like in chrome

**Screenshots**

image

### PR DESCRIPTION
**Pull request by mxmou**
**Resolves**

Resolves #763 

**Changes**

Adds CSS to override the browser's default checkbox appearance, based on Chrome's styling but using the same colors as the "recommended" tag. I hope I added the icon correctly.

**Reason for changes**

Settings should look the same in all browsers.

**Tests**

Tested manually in Chrome in Firefox.

### CODE REVIEW

**Comment by areeq0325** [comment]
Tested on Edge, the boxes are grey.
image

**Comment by areeq0325** [comment]
Definitely not blue.

**Comment by WorldLanguages** [comment]
Oh.

**Comment by TheColaber** [comment]
So this has done nothing?

**Comment by mxmou** [comment]
> So this has done nothing?

It does change the checkboxes in Firefox. But I don't know what's wrong with Edge.

**Comment by WorldLanguages** [comment]
> It does change the checkboxes in Firefox. But I don't know what's wrong with Edge.

Wow, so it changes in Firefox, but not in Chromium Edge?

**Comment by mxmou** [comment]
> > It does change the checkboxes in Firefox. But I don't know what's wrong with Edge.
> 
> Wow, so it changes in Firefox, but not in Chromium Edge?

I just tested it on Edge and it works.
@areeq0325 Are you sure you tested on the latest development version?

**Comment by areeq0325** [comment]
image
image

**Comment by mxmou** [comment]
@areeq0325 Thanks for the screenshot. The version where this is fixed will be 1.4.0.

**Comment by WorldLanguages** [comment]
@areeq0325 Yeah, we only have real releases every 2 weeks. If you want to have the real latest version all the time, clone this repo and git pull master once in a while.

**Comment by areeq0325** [comment]
image
Blue confirmed. Thanks.

**Comment by GrahamSH-LLK** [comment]
> image
> Blue confirmed.

Nice! Of course, we've tested, but it's great to see that it's working out in the wild!

**Pull request merged**
