### PR TITLE
Check marks for Scratch Team members

### PR DESCRIPTION
**Pull request by YandeMC**
### Changes
give scratch team verification checkmarks instead of asterisks
image
image

### Reason for changes

some people might not understand the asterisks meaning so replacing it with a checkmark will help them know they are st

### Tests

tested on oprea gx

some things are still buggy and the images are in a seperate repo

### CODE REVIEW

**Comment by YandeMC** [comment]
also [this was from a discord suggestion](https://discord.com/channels/806602307750985799/1063028603077525546)

**Comment by WorldLanguages** [comment]
We need a GitHub issue first.

**Comment by mxmou** [comment]
> some people might not understand the asterisks meaning so replacing it with a checkmark will help them know they are st

I think it would be better to suggest this change to the Scratch developers. Most Scratch Addons users probably already know enough about Scratch to understand what the asterisk means.

**Comment by BroJac5246** [comment]
Also is this PR a draft?

**Comment by YandeMC** [comment]
> Also is this PR a draft?

no

**Comment by WorldLanguages** [comment]
Closing as issue #6148 has also been closed.

**Comment by YandeMC** [comment]
most of the addon.json errors were me copying the json from another addon and forgetting to change stuff

>The image already exists in the folder, why link to it externally?

I couldn't figure out how to do that but entirely my fault for not researching more (I tried to do `./st.png`)

as for the popular users, I planned to add it but the question of "what counts as popular?" came up and I decided to leave it out last minute without deleting any part of the code and the addon description that mentions that

 I made this pr way too early and I should've tested and researched more and cleaned up some stuff up before making this pr

thanks for your time, I might redo this with all the feedback.

**Pull request closed without merging**
