### PR TITLE
Clean signature expand button

### PR DESCRIPTION
**Pull request by ZenithRogue**
**Resolves**

Reimplements #370, clearing up messy code, and making it more aesthetically pleasing/less obtrusive

**Changes**

Placed expand button in post footer

image

Signatures can now be collapsed
image

**Tests**

When logged out, the button still appears properly
image

Button will not appear if the post does not contain a signature

### CODE REVIEW

**Comment by GrahamSH-LLK** [comment]
Personally, I actually like the button where it is. I don't think that that area represents the purpose well. That groups it with Report and Quote, which aren't anywhere close to it's intended purpose. Maybe you could implement this as a different setting on the switch?

**Comment by JeffaloBob** [comment]
> Personally, I actually like the button where it is. I don't think that that area represents the purpose well. That groups it with Report and Quote, which aren't anywhere close to it's intended purpose. Maybe you could implement this as a different setting on the switch?

i don't.

it's currently part of the post content body which is kinda odd.

i really like this implementation better

**Comment by ZenithRogue** [comment]
Bruh, why did you hit me with a do not merge? This implementation is much cleaner and completely unobtrusive.

**Comment by GrahamSH-LLK** [comment]
See #385

**Comment by GrahamSH-LLK** [comment]
I gave up, because you guys obviously like the other spot better.

**Comment by ZenithRogue** [comment]
@GrahamSH-LLK I added your script as a selectable option
image

**Comment by GrahamSH-LLK** [comment]
Ok!

**Review by GrahamSH-LLK — COMMENTED** [review]
Looks good!

**Comment by WorldLanguages** [comment]
Lol try not to start an argument over the placement of a button :P

**Comment by Explosion-Scratch** [comment]
Lol which one is default? XD

**Comment by GrahamSH-LLK** [comment]
Footer. Fixed now.

**Pull request merged**
