### PR TITLE
Remove some addons

### PR DESCRIPTION
**Pull request by WorldLanguages**
@NoobTracker, for the v1.0.0 release we'll be removing beta addons. Don't worry, our external players addon will return some day in some way or another, we hope someone in the community can improve it. Modifying stuff in the project page isn't that easy.

### CODE REVIEW

**Comment by WorldLanguages** [comment]
@Hans5958 Want to take a look at why schema validation fails? There's no urgency to merge this so feel free to investigate.

**Comment by JeffaloBob** [comment]
can we get an f in comments for all 3 of these addons?

f

**Comment by NoobTracker** [comment]
I guess it would be enough to just remove some settings and only have links and it would work.

**Comment by Hans5958** [comment]
> 
> 
> @Hans5958 Want to take a look at why schema validation fails? There's no urgency to merge this so feel free to investigate.

It's because the empty fields. Read #284.

**Pull request merged**
