### PR TITLE
More links: Add waitForElement for project pages

### LINKED ISSUE #308: "More links" addon not working properly when loading project in editor mode
I've also noticed it doesn't work on player mode in some weird cases, it's a timing based issue.
We should likely use `addon.tab.waitForElement`.

### PR DESCRIPTION
**Pull request by Hans5958**
This PR adds `waitForElement` on project pages, due to the nature on the editor.

This pull request resolves #308.

This fix should have worked, theoretically.

### CODE REVIEW

**Comment by WorldLanguages** [comment]
This is better but I think you'll also need to use `while(true) {}` here, since you can go inside the editor, then outside.

**Comment by Hans5958** [comment]
Okay, so I re-read the issue and forgot to consider the editor that will remove the links again, way back before @WorldLanguages said it. I have tried to implement it, but there are some issues.

For some reason, I got "memory leaks" that causes the browse become unresponsive. I have identified that the issue is from the `document.querySelector`, but that just leave me wondering how come that could be the cause.

The "memory leaks" happen on Firefox, but I'm not sure if it will happen in Chrome. Could someone test this and try to fix the issue?

**Comment by WorldLanguages** [comment]
Oh wow Windows started to swap... After some testing it appears to be linkify, commenting exactly the lines calling it fixed the issue.

**Comment by Hans5958** [comment]
> 
> 
> Oh wow Windows started to swap... After some testing it appears to be linkify, commenting exactly the lines calling it fixed the issue.

I don't think so. As I said earlier, the problem lies when it executes `document.querySelector()`. The Linkify part appears to be fine, but I have no way of testing it because I don't have the elements to run it for.

**Comment by WorldLanguages** [comment]
@Hans5958 Did you comment both instances of `linkify()`? I also commented the one that linkifies comments.

**Comment by Hans5958** [comment]
> 
> 
> @Hans5958 Did you comment both instances of `linkify()`? I also commented the one that linkifies comments.

Yes. Heck, I even only run `querySelector` and it's still laggy.

**Comment by Hans5958** [comment]
Seems the issue is fixed on #622. Will test it later.

**Comment by GrahamSH-LLK** [comment]
Should I close this?

**Comment by Hans5958** [comment]
Keep it open

**Comment by Hans5958** [comment]
Right, I finally got it working. Not sure how I achieve this, but it works now. I also got time to simplify the code by implementing the new features on the API.

**Review by WorldLanguages — APPROVED** [review]

**Pull request merged**
