### PR TITLE
my-ocular: filter out newlines

### LINKED ISSUE #4643: New lines on Ocular Statuses causes interference with the profile UI
With 2.0 -> 3.0 enabled
image

and without
image

[profile](https://scratch.mit.edu/users/9gr/)

Not really a bug, but if we're able to filter out new lines it'd be much better.

### PR DESCRIPTION
**Pull request by Weredime**
Resolves #4643

### Changes
Filters out newlines from fetched ocular statuses.

### Tests
Firefox Developer

### CODE REVIEW

**Comment by apple502j** [comment]
I think white-space: nowrap is better.

**Comment by Chiroyce1** [comment]
> I think white-space: nowrap is better.

Postpercent [uses](https://postpercent.rirurin.com/users/Chiroyce) `white-space: pre`, is there a major difference?

**Comment by apple502j** [comment]
pre preserves multiple whitespaces I think.

**Comment by Weredime** [comment]
> I think white-space: nowrap is better.

@apple502j `white-space: nowrap` does not work

**Comment by apple502j** [comment]
Ah, it is a `<br>` tag, makes sense.

**Pull request merged**
