### PR TITLE
Setting to change the green color of the forums

### LINKED ISSUE #1092: Option to change the green color of the forums
**Describe the new addon**
There would be an option to customize the green color on the 3.0 forums that is at the header and at the top of all posts. Its the part that has the search and says "Discuss Scratch".

### PR DESCRIPTION
**Pull request by TheColaber**
**Resolves**

Resolves #1092

**Changes**

Added New setting

**Tests**

Works

### CODE REVIEW

**Comment by RedGuy12** [comment]
Dark mode darkens the color. you might want to add a fix for that
________________________________

**Comment by TheColaber** [comment]
There is not really a fix for that so I recommend you just tweak the color. Unless I add a setting for darkmode to enable/disable banner darkening, but darkmode should make things darker.

**Comment by RedGuy12** [comment]
I mean https://github.com/ScratchAddons/ScratchAddons/blob/4d26cbf27fe33b7a63b30333bed5d3755916a666/addons/dark-www/experimental_forums.css#L26#L20 overrides this

**Comment by mxmou** [comment]
This doesn't work when dark mode is enabled. Please don't add settings like this until #657 is done for website dark mode.

**Pull request closed without merging**
