### PR TITLE
Auto-reply

### PR DESCRIPTION
**Pull request by CodeGuy92**
My addon thing.

### CODE REVIEW

**Comment by WorldLanguages** [comment]
I think this was rejected previously
Probably fits better as its own browser extension

**Comment by FunctionalMetatable** [comment]
.. or a bookmarklet

**Comment by CodeGuy92** [comment]
> I think this was rejected previously

I don't think it was... From what i remember, you blacklisted me from the repo.

**Comment by WorldLanguages** [comment]
I meant it was rejected but the addon was made by someone else. I can't remember who it was tho

**Comment by CodeGuy92** [comment]
> I meant it was rejected but the addon was made by someone else. I can't remember who it was tho

It was.. this guy right here. Me.
I deleted my old account and created another one because my old account was really messy.

If you're going to blacklist me again, well...

**Comment by CodeGuy92** [comment]
> I meant it was rejected but the addon was made by someone else. I can't remember who it was tho

Do you have a link to prove this, tho?

**Comment by mxmou** [comment]
> > I meant it was rejected but the addon was made by someone else. I can't remember who it was tho
> 
> Do you have a link to prove this, tho?

I think it was actually made by you: #1596

**Comment by CodeGuy92** [comment]
> > > I meant it was rejected but the addon was made by someone else. I can't remember who it was tho
> > 
> > 
> > Do you have a link to prove this, tho?
> 
> I think it was actually made by you: #1596

Yes. But this is a _draft_, i'm just adding some more stuff and then mark it as "ready for review".

**Comment by TheColaber** [comment]
Ideally we only keep draft prs here for prs that do big changes to the settings page and to big addon updates. This is especially good for others to list ideas in the PR while it's being developed, and also for others to commit changes. This addon doesn't need a pr to be worked on.

**Comment by CodeGuy92** [comment]
ok i give up

**Pull request closed without merging**
