### PR TITLE
Revert "Scratch Avocados (April Fools)"

### PR DESCRIPTION
**Pull request by apple502j**
Reverts #4436

### CODE REVIEW

**Comment by WorldLanguages** [comment]
#4404 should be reverted too

**Comment by WorldLanguages** [comment]
#4404 should be reverted too

**Comment by RIMOPA** [comment]
> #4404 should be reverted too

I think It would be useful for the easter egg addon that returns the modes (if it is added)

**Comment by mxmou** [comment]
> > #4404 should be reverted too
> 
> I think It would be useful for the easter egg addon that returns the modes (if it is added)

An addon would be very different from Scratch's implementation.

**Pull request merged**
