### PR TITLE
Add links to issues/prs on changelog

### PR DESCRIPTION
**Pull request by TheColaber**
**Changes**

Links added for PRs and issues mentioned

**Reason for changes**

It's more convenient for the devs

### CODE REVIEW

**Review by GrahamSH-LLK — APPROVED** [review]
Looks good!

**Review by wgyt735yt — APPROVED** [review]
This looks great. The links are nice to have :)

**Comment by WorldLanguages** [comment]
Any objections? @Hans5958

**Review by Hans5958 — APPROVED** [review]
I have none. Just go for it.

**Pull request merged**
