### PR TITLE
Addon Storage API

### LINKED ISSUE #1950: addon.settings.set
Some addons have setting menus that they create when you are in the scratch editor (ex. onion skinning). Could we add a setter to the addon object to save changes users may have made in those setting menus? I ask this mainly because it is a feature that I would like to be able to use for my keyboard editor addon.

example usage:
```js
addon.settings.set("option name", "value")
```

may also need something to get possible options of a setting:
```js
addon.settings.getOptions("option name")
//returns options array or type of option (ex. number or string)
```

### PR DESCRIPTION
**Pull request by nexensys**
Resolves #1950
*although it is still a somewhat different thing*

### Changes

Added the addon storage api:
`addon.storage`
  |- `local`
  |     |- `get: Promise<any>`
  |     |- `set: Promise<void>`
  |- `sync` 
  |     |- `get: Promise<any>`
  |     |- `set: Promise<void>`
`addon.storage`, `addon.storage.local`, and `addon.storage.sync` all extend Listenable and have change events fired
`addon.storage` catches change events from both `addon.storage.local` and `addon.storage.sync`.

This API is essentially a reorganized version of the `chrome.storage` api, but addons are unable to interfere with each other.

### Reason for changes

There are multiple addons that currently use `localStorage` to store preferences and other data, and would benefit from the `addon.storage.local` API:
- `animated-thumb`
- `dango-rain`
- `message-filters`

Addons that create a UI element could also benefit from this API, allowing setting changes to sync across tabs (via the `change` events) or even across browsers using `addon.storage.sync`, preventing users from needing to start from scratch with these settings which switching browsers or computers (The current sync features only store changes to settings in the manifest, not those in the addon's separate UI).

Not only does this provide more opportunities for addon developers, it can also reduce the messy aspect of string-based storage using `localStorage`.

This could also be merged with the `addon.settings.set` feature that has been discussed previously for similar effect.

@WorldLanguages Pinging you so that you see. Ping whoever you want to discuss with.

### CODE REVIEW

**Comment by WorldLanguages** [comment]
> Can we try to rush this so that I can merge #5219 with `paint-snap`?

I don't think it's a good idea to intentionally block a new addon PR, and make it depend on a new SA API that doesn't exist yet. Couldn't this new addon work just like onion-skinning in the meantime (default settings on SA settings, and allow them to be changed per editor session)

**Comment by ErrorGamer2000** [comment]
> > Can we try to rush this so that I can merge #5219 with `paint-snap`?
> 
> I don't think it's a good idea to intentionally block a new addon PR, and make it depend on a new SA API that doesn't exist yet. Couldn't this new addon work just like onion-skinning in the meantime (default settings on SA settings, and allow them to be changed per editor session)

@WorldLanguages It could, it does, and I'm not actually blocking the PR. I am simply saying that it would be nice to be able to just put them both together, rather than make a second pr to add it later. I was only saying that the grid aspect should wait.

**Comment by WorldLanguages** [comment]
@ErrorGamer2000 I haven't looked deeply into the paint-snap PR, I assume "grid aspect" means a specific feature from the addon, independent from other features, which could be delayed until we add the storage API (but not all other features from the addon)? Is that what you mean?

**Comment by ErrorGamer2000** [comment]
@WorldLanguages Yes, exactly.

**Pull request closed without merging**
