### PR TITLE
v1.19 update notification

### PR DESCRIPTION
**Pull request by WorldLanguages**
New YouTube video ID coming in a few days

image

### CODE REVIEW

**Comment by FunctionalMetatable** [comment]
#3333 🎉

**Comment by RedGuy12** [comment]
> The new \"name scripts **before** placing in backpack\" addon asks you to name scripts **after** you drag them into the backpack

before or after?


also "hide delete button" is very out of context. the addon name should probably be changed to "hide **sprite** delete button"

**Comment by WorldLanguages** [comment]
> before or after?

After being dragged but before it's actually placed in it :P

> also "hide delete button" is very out of context. the addon name should probably be changed to "hide sprite delete button"

Not sure about that, naming addons differently in the notification is weird (translators might get confused). And it also hides delete buttons for costumes, backdrops and sounds.

**Comment by RedGuy12** [comment]
> After being dragged but before it's actually placed in it :P

Should be consistent



> Not sure about that, naming addons differently in the notification is weird (translators might get confused).

I meant change the addon.json too.



> And it also hides delete buttons for costumes, backdrops and sounds.

Ah, maybe "hide editor delete buttons"

**Pull request merged**
