### PR TITLE
New addon: hide-delete-button

### PR DESCRIPTION
**Pull request by apple502j**
This adds a new addon, hide-delete-button. This is one of the addons where manifests are larger than the actual style... Implements https://discord.com/channels/806602307750985799/806609030935740477/871486900261752943

### CODE REVIEW

**Comment by WorldLanguages** [comment]
Waiting for #3261 to be merged

**Comment by WorldLanguages** [comment]
@mxmou Ugh having no minor tag/group makes addons like this weird IMO

**Comment by apple502j** [comment]
@WorldLanguages This addon is very useful - if the problem is that we don't have a category, then we can make one about sprite management.

**Comment by WorldLanguages** [comment]
> This addon is very useful

I'm missing something then, how is it useful? "Confirm sprite deletion" seems superior?

**Comment by WorldLanguages** [comment]
Hmm does that addon ask if sure when deleting costumes or sounds?

**Comment by apple502j** [comment]
Confirmations are annoying - sure, it's less annoying than losing sprites, but is annoying when a popup appears out of nowhere. Plus it only works for sprites, not other assets.

**Pull request merged**
