### PR TITLE
Fix code blocks inside quotes

### PR DESCRIPTION
**Pull request by mxmou**
See https://github.com/ScratchAddons/ScratchAddons/issues/3946#issuecomment-998325469

### CODE REVIEW

**Comment by WorldLanguages** [comment]
Is this supposed to remove the zebra stripping?

**Comment by WorldLanguages** [comment]
@mxmou I don't think I can see any visual difference this PR would affect.

**Comment by RedGuy12** [comment]
@WorldLanguages code blocks inside of quotes had white background

**Comment by WorldLanguages** [comment]
@RedGuy12 I wasn't able to reproduce that, can you share a screenshot?

**Comment by mxmou** [comment]
On master:
image
With this change:
image

**Pull request merged**
