### PR TITLE
Expand Button for Full Siggy

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
**Changes**

Adds new script for expand button instead of all full signatures.
**Reason for changes**

Cause the option to expand individual signatures is cool.

### CODE REVIEW

**Comment by GrahamSH-LLK** [comment]
@WorldLanguages

**Comment by WorldLanguages** [comment]
With this PR in a way we get into a problem I knew someday would happen - by changing a "boolean" setting to a "checkbox", you'd be losing the previous choice by the user.
By doing this the settings page would kinda break, since the previous value for the setting `"signature"` was `true` or `false`, and none of those options are available.
If the user doesn't select any of them, the `addon.settings` API would still return a boolean, so you could support previous settings! But there's no way to do `addon.settings.set` yet, so you can't actually *migrate* settings.

**Comment by GrahamSH-LLK** [comment]
Also, I realized that I used userstyle code for userscripts. Why can't we do the same thing userstyles do? (Settings match) It could be optional. Plus, to work around the other problem, I'm just going to change the id to "signatureswitch". If they had disabled it, it would be enabled again, but the new default is much less annoying and would be much less likely to be disabled.

**Comment by GrahamSH-LLK** [comment]
Don't merge, just found a bug.

**Review by WorldLanguages — APPROVED** [review]

**Pull request merged**
