### PR TITLE
Confirm sprite/sound/costume delete

### LINKED ISSUE #4822: Add an option to prompt for audio deletion

### PR DESCRIPTION
**Pull request by Norbiros**
Resolves #4822

### Changes

I removed remove-sprite-confirm addon, and changed hide-delete-button (I added new feature - you can select between "hide delete button" [works the same], and "confirm action" [asks for confirmation])

Screenshot from 2022-07-18 10-33-07

### Tests

Firefox 98 - everything works fine

### ToDo
- [ ] Change addon's name and description
- [ ] Add update note
- [ ] Confirmations in popup
- [ ] Maybe split into two addons (if not implement both option)

### CODE REVIEW

**Comment by Secret-chest** [comment]
What if you want both?

**Comment by Norbiros** [comment]
If it is hidden, you can't click it, so it can't show confirm popup.

**Comment by mxmou** [comment]
> If it is hidden, you can't click it, so it can't show confirm popup.

The delete option in the context menu also has a confirmation if that addon is enabled.

**Comment by Secret-chest** [comment]
> What if you want both?

@mxmou @Norbiros

**Comment by Secret-chest** [comment]
Also, I want to hide the delete button on everything, but only have a confirmation on sprites. This creates waaaay more problems than it solves.

**Comment by Norbiros** [comment]
> > What if you want both?
> 
> @mxmou @Norbiros

I can implement both option,but It doesn't fix issue from your next comment. Maybe we should split this add-on? (1. remove delete button 2. confirms objects delete) It can be easier to change from user perspective (you don't have 6 settings in one add-on).

**Comment by Secret-chest** [comment]
> > > What if you want both?
> > 
> > 
> > @mxmou @Norbiros
> 
> I can implement new option "both", but It doesn't fix issue from your next comment ([#4848 (comment)](https://github.com/ScratchAddons/ScratchAddons/pull/4848#issuecomment-1188594353)). Maybe we should split this add-on to `remove delete button` and `confirm objects delete`. It can be easier to change from user perspective (you don't have 7 settings in one add-on). What do you think @mxmou and @Secret-chest?

Well,

> This creates waaaay more problems than it solves.

So they should be split apart.

**Comment by WorldLanguages** [comment]
I'm not sure if it makes sense to merge a theme with an editor addon. Hiding a UI element is different from adding a confirmation prompt.

**Comment by Norbiros** [comment]
Closing after further discussion with W_L on dc, soon I gonna make new PR.

**Pull request closed without merging**
