### PR TITLE
Reporter wall thickness / Flat Hats

### PR DESCRIPTION
**Pull request by TheYande**
### Resolves
prevents super chonky reporters taking up space (below is probably overexaggerating but i encounter this problem alot) 
image

### Changes

add the setting to custom block shape.

image
Flat Hats! (from discord suggestion i made [https://discord.com/channels/806602307750985799/1043655310792982619](url) )

### Reason for changes

big blocks take up space and could possibly cover up other scripts

### Tests

Tested on OperaGX

### CODE REVIEW

**Comment by WorldLanguages** [comment]
Can you create an issue first so that we can discuss the feature idea?

**Comment by WorldLanguages** [comment]
@YandeMC We also need a separate issue for the flat hats.

**Comment by YandeMC** [comment]
apperently renaming a branch deletes the branch

**Review by YandeMC — COMMENTED** [review]
your code sucks yande

**Comment by callumjt** [comment]
> your code sucks yande

yk i would say something funny but im not funny so i wont

**Comment by CubesterYT** [comment]
> Author

yande I ❤️‍🔥 your code

**Comment by YandeMC** [comment]
aaaaaa wrong branch again omg

**Comment by TheColaber** [comment]
the branch got messed up, but the idea is still cool, ill make an issue for this

**Pull request closed without merging**
