### PR TITLE
Turn popup iframes into vue components

### LINKED ISSUE #1316: Zooming into addon popup messes up iframe in browser popup
**Describe the bug**

When visiting an addon popup in a new tab and zooming in, the size of the iframe gets very small. Once you go to a new tab and open it there, the bug goes away. This bug is not a big priority really...

**To Reproduce**

1. Go to an addon poup in a new tab.
2. Zoom in!
3. Look at the popup's iframe
4. See how small it gets

**Expected behavior**

For the iframe to be the same height has 100% zoom.

**Screenshots**

image

**Additional context**

This is due to the height CSS variable being set to something smaller making the iframes, in turn, get small too.
Before:
image
After:
image

### LINKED ISSUE #2593: Weird popup styling issues in Chrome, just sometimes
Appears to be a Chrome bug, not ours. Going to devtools, unchecking any style near the affected area, then rechecking it, appears to make it return to normal. So Chrome is probably not rerendering/recalculating/whatever when it should.
Screenshots were taken by clicking the popup icon many times until the issue appeared

Text wrapping in navbar
image

Tab padding inexistent
image

### LINKED ISSUE #2959: window.Vue, Sora, and HTML lang automatically available
Moved from #1234

> window.Vue and Sora automatically available
No need for addons to set the HTML lang (could be set by the extension popup)
---
> We can simply make fullscreen popups become fullscreen iframes ¯\\(ツ)/¯

### PR DESCRIPTION
**Pull request by TheColaber**
Resolves #2959
Resolves #1316 
Resolves #2593

### Changes

todo

### Todo
- [x] fullscreen
- [x] settings page
- [x] new light mode style feature
- [x] scrollbar :(
- [x] rm stuff

### Reason for changes

to resolve stuff

### Tests

todo

### CODE REVIEW

**Comment by mxmou** [comment]
Bug that requires refactoring the load-vue-components library: popups can affect each other using CSS, which causes too much padding in the cloud-games popup.

**Comment by TheColaber** [comment]
> Bug that requires refactoring the load-vue-components library: popups can affect each other using CSS, which causes too much padding in the cloud-games popup.

Just a bizarre thought, but could we somehow put the component and it's styles in a shadow root? Is that even possible? Otherwise, the other 2 options I see are something like https://vue-loader.vuejs.org/guide/scoped-css.html or change all of the css.

**Comment by WorldLanguages** [comment]
Shadow root probably makes most sense

**Comment by TheColaber** [comment]
update: shadow root doesn't work the way I thought it would and that's not an option... what to do...

**Comment by mxmou** [comment]
> update: shadow root doesn't work the way I thought it would and that's not an option... what to do...

I already fixed the CSS issue by setting `media="not all"` on unnecessary styles.

**Comment by TheColaber** [comment]
@mxmou maybe im having trouble understanding, but doesn't that disable that style? I'm trying to get the css for the settings page to work in the popup without it messing up the popup's other styles.

**Comment by mxmou** [comment]
> @mxmou maybe im having trouble understanding, but doesn't that disable that style? I'm trying to get the css for the settings page to work in the popup without it messing up the popup's other styles.

Add the attribute initially and remove it when switching to the addons tab. That's what I did with the other popups' styles.

**Comment by RedGuy12** [comment]
Wouldn't just "disabled" be easier to understand?


________________________________

**Comment by TheColaber** [comment]
@mxmou the settings page and all of it's component styles is not an addon, which is the problem I'm trying to solve.

**Comment by TheColaber** [comment]
@mxmou I think commit 1340d8a5925340f6c6b6a115ef549327b9b8f9a3 breaks fullscreen, but epic work :)

**Comment by mxmou** [comment]
> Edit: Oh btw... does this mean we no longer need to use the `--height` and `--width` variables anymore? I thought those were added because of the iframes.

They were added because `100vw` and `100vh` aren't the actual minimum and maximum heights of the popup, so preventing it from overflowing is difficult (and still not done on Firefox). if removing them is possible, it's probably easier without the iframes.

**Comment by mxmou** [comment]
Why did you remove categories.css? style.css should be split (in a CSS refactor, not here) instead of adding more things to it.

**Comment by TheColaber** [comment]
It was just a one selector file so I thought it might as well be part of style.css

**Review by mxmou — DISMISSED** [review]

**Comment by WorldLanguages** [comment]
This PR is a giant monstrosity, but maybe it can get merged for v1.21.0

**Comment by TheColaber** [comment]
I'm very confused on how these got here...
image

**Comment by mxmou** [comment]
> I'm very confused on how these got here... image

[This commit](https://github.com/ScratchAddons/ScratchAddons/commit/ed423f38c992fceffdaa53fd5aaab3f54648f412)

I'm not sure why "origin/master" would be piw-piw's fork though.

**Comment by lisa-wolfgang** [comment]
"World_Languages! Why aren't you paying attention to my infrastructure proposal?!" Count Colander shrieked as he shoved the doors to the throne room. They flew open and slammed against the wall with the loud, echoing sound of wood on stone.

"Colander, I have told you that I will look at it later," the king replied from his gem-encrusted spa bed as Apple placed cucumbers over his eyes. "Apple! I told you to stop with the cucumbers! I need to keep close watch on you, and I can't do that if you keep putting those filthy vegetables on my face." Apple grunted and visibly rolled their eyes before taking the cucumbers off.

The count had heard this excuse before. "But World_Languages! This is *important*! These infrastructure changes will allow us to distribute addons much more efficiently in the future, and we'll be able to renovate the entire town square! Just look at its current condition!"

The king turned his head enough to glance out the window onto the town square, where there was a large mound of dirt sitting in the middle, but most of the citizens of the kingdom obliviously walked around it, over it, or into it.

"Eh, it looks fine to me. It can wait."

"But it HAS been waiting! It has been ready for months! In fact, I will give the go-ahead myself if you don't listen to me!"

"Ugh," World_Languages muttered as he rolled off of the spa bed. "Apple, please replace this mattress. It is too comfortable for me to watch you!" The king then led the count out of the throne room.

"Colander, you are privileged to be in the presence of such a wise and benevolent leader," the king remarked as the two passed a mustachioed portrait of griffpatch. "Let me impart a piece of my wisdom onto you. See, any good addon or infrastructure change is like a bottle of fine-aged grape juice."

"Grape juice? Not--"

"I'm still a minor, silly Colander. As I was saying, a bottle of fine-aged grape juice has been left sitting for years. The contents have rotted and become completely useless due to the passage of time. Then, Apple can do the one thing he's good for -- fixing things I don't want to deal with. After that, it is perfectly processed and ready for distribution."

"But World_Languages! Why don't you just look over the proposal yourself?"

The king chuckled. "Colander, isn't this a lovely wall? I do say, Maximouse's taste in castle decor is excellent."

"But World_Languages, you didn't answer my qu--"

"Colander, I want to show you this," the king bellowed as he walked ahead to a closet in the corner. He opened a drawer and pulled out a dull, shriveled-up, spoiled addon. "This is my prized possession -- the reverse stage button addon."

"It... it looks... ummm... great!" the count stammered, as to insult the king was to commit treason.

"I know... she's a real beauty, isn't she? I call her Cheryl," the king crooned. The addon convulsed and dripped some sort of goop onto the count's boot. "And she's getting finer by the second! Although this goop is kind of annoying. Maybe I'll have to call in Garbo to wrangle this one. But I'll worry about that later. See, Colander, I even procrastinate on my most prized creations."

"But World_Languages, didn't you tell Lisa that you're supposed to be a *model of decisiveness* for the feeble-minded citizens? How are you being a model of decisiveness when you procrastinate everything?"

"Ah, Colander, I am afraid that I must return to the throne room now. All this exercise has made me quite tired, and I need another spa session to rejuvenate me. Good day!"

Before the count could utter another word, the king stuffed in his "do not disturb" earplugs and whistled as he returned to the throne room.

"That dictator really gets on my nerves sometimes!" Count Colander thought angrily. Then he stormed back to his quarters.

A couple months later, the king summoned the count to the throne room.
"Colander! Great news! I have reviewed your proposal!"

"REALLY?!" the count shrieked in excitement.

"Yes! I must say, it is quite the monstrosity. Almost as monstrous as my sweet little Cheryl. But we can maybe give it the go-ahead for the next distribution cycle."

"Excellent! Thank you for giving my proposal the attention it deserves!"

Filled with joy and satisfaction, the count returned to his quarters. The king, however, eventually decided that the proposal "needed some more time to age," so he held it back once again. The count didn't notice and proceeded to completely forget that he was going to give the go-ahead for his own proposal.

The End

---

Epilogue (back a couple months again)

World_Languages strolled along happily as he returned from Cheryl's closet to the throne room. "That unfortunate soul thinks that his agenda is more important than mine. Well, I will not let his lack of experience cloud my mind," he thought to himself as he opened the doors to the throne room. He walked over to his spa bed, savoring the thought of well-deserved relaxation, and began to sink into it--
"WHAT THE?!?" the king exclaimed as he felt small, hard, rod-like lumps underneath him. He jumped up and ripped off the cover to reveal that it was stuffed with cucumbers. Apple snickered and snuck out of the room quietly as steam flew out of the king's beet-red ears.

**Comment by Samq64** [comment]
Colander

**Comment by RedGuy12** [comment]
it’s a meme from the discord server where colaber is called colander

**Comment by Samq64** [comment]
> it’s a meme from the discord server where colaber is called colander

I didn't know that because I don't use Discord.

**Comment by Samq64** [comment]
It's been 7 months...

**Comment by lisa-wolfgang** [comment]
This PR may not be our highest priority at the moment (MV3 is) but it's at least worth a re-evaluation.

Since almost a year's worth of conflicts has accumulated at this point, I'm thinking the best approach is to close this PR, then open fresh ones with the same/similar changes, but in smaller chunks. We could create an issue to track everything that needs to be converted. Merging individual PRs would be a lot more palatable than reviewing an entirety of 43 changed files, and small PRs are a lot less likely to get forgotten about.

Another option is to focus efforts on the new settings page design, but we still aren't far enough into the decision-making process to know the extent of the changes that will end up being made. A large majority of the work in this PR may still apply. We also have no timetable for a potential redesign -- it might not end up happening at all -- so waiting on its release would likely further delay the resolution of the issues addressed by this PR.

@TheColaber As the author of this PR, what do you think would be the best course of action?

**Comment by WorldLanguages** [comment]
Keep in mind, transitioning to MV3 might force us to add a build step, so we would probably directly change popups to Vue 3 components all at once, instead of transitioning first to Vue 1 components and then to Vue 3 components. I can't officially confirm yet that a build step will be strictly necessary, however.
Also, even if MV3 does not require a build step, we might decide to build our webpages anyway, so we would probably use Vue 3 here.

**Pull request closed without merging**
