### PR TITLE
Scratch Blocks can't scroll

### LINKED ISSUE #3684: 3.0 forum Scratchblocks addon messes up Full Areas "Show scroll for forum Scratchblocks"
### Description

The 3.0 forum scratchblocks addon makes the scroll bar from `full-areas` disappear on the forum scratchblocks.
### Repoduction steps

1. Turn on these addons with these settings:
image
image
2. Go to a forum post with wide scratchblocks like [this one](https://scratch.mit.edu/discuss/post/5714902/)
3. See that the scroll bar is missing

### Expected behaviour

A horizontal scroll bar should appear below the blocks.

### Actual behaviour

There is no scroll bar.

### Screenshots

The missing scrollbar:
image
The scrollbar shows up with the 3.0 scratchblocks addon off:
image

### Environment

- Browser:  Firefox 92. I know, it's out of date, but this bug's been here since a few firefox versions.
- Scratch Addons version:  1.21.1
- Operating system:  Windows 10

### PR DESCRIPTION
**Pull request by Norbiros**
Resolves #3684

### Changes

When you have long code like this https://scratch.mit.edu/discuss/topic/577749/?page=1#post-6010695 you couldn't see it... Using scratchblocks addon.

### CODE REVIEW

**Comment by CST1229** [comment]
I think you should add the 3.0 blocks scrolling CSS to `full-signature` instead of adding it by default in `scratchblocks`.

**Comment by Norbiros** [comment]
Okay @CST1229, but I found 2 problems:
- class like this don't exists, I don't know if it must be something other than class or id, but I couldn't find it with `CRT+F` in html of page, or code...
- how I can add style to it? By looking for class name?
- and if I understand correctly this `full-signature` must be above blocks - but I can't find it:
Screenshot from 2022-02-06 16-19-03

**Comment by kccuber-scratch** [comment]
Resolves #3684

**Comment by CST1229** [comment]
> Okay @CST1229, but I found 2 problems:
> 
>     * class like this don't exists, I don't know if it must be something other than class or id, but I couldn't find it with `CRT+F` in html of page, or code...
> 
>     * how I can add style to it? By looking for class name?
> 
>     * and if I understand correctly this `full-signature` must be above blocks - but I can't find it:
>       Screenshot from 2022-02-06 16-19-03

`full-signature` is not a class, it's an addon (more specifically, Show full areas).

**Comment by Norbiros** [comment]
Okay... 
I will implement this but i found problem. IDK if it is on my computer or global problem, but when you clone newest version of this repository - scratch blocks 3, and style - don't work on forums page. Normally it works but this 2 addons don't work on this page. Can someone test it? **I don't create issue, because i don't know if it is global problem**

**Comment by apple502j** [comment]
Please don't set styles via JavaScript. You should use CSS instead. (Plus, this PR looks like wip, so closing)

**Comment by lisa-wolfgang** [comment]
@apple502j Don't close PRs simply because they're WIP.

**Comment by Norbiros** [comment]
Thanks @lisa-wolfgang, but I removed this branch when this PR was closed...
I can't restore it now (to much time). I will create new pull request, and new branch.

**Pull request closed without merging**
