### PR TITLE
Improve Scratch 2.0 → 3.0 addon

### LINKED ISSUE #642: Scratch 2.0 → 3.0: Profile comments don't look like project comments
### Problem one:
 On the secondary account Speedblocks, it says that the people I follow are "Studios I'm Following (0)" and that my followers are "Studios I Curate (0)".

### Problem Two:
Profile comments don't look like project comments.

### LINKED ISSUE #1092: Option to change the green color of the forums
**Describe the new addon**
There would be an option to customize the green color on the 3.0 forums that is at the header and at the top of all posts. Its the part that has the search and says "Discuss Scratch".

### LINKED ISSUE #1699: Scratch 2.0→3.0 shows vertical overflow in comments (zalgo text)
Example: https://scratch.mit.edu/users/Chiroyce/#comments-125081052
Vanilla Scratch does not show the overflow.
Low prio ¯\\_(ツ)_/¯

### LINKED ISSUE #3136: Change CSS of My-stuff + 2.0 - 3.0
### Describe the solution you'd like

Like ST has changed up the studios, SA should change up the my-stuff to match the theme. Need I say more?

### LINKED ISSUE #3733: Fix Buttons in Scratch 3.0 page addon
### Is your request related to a problem? Please describe.
 the buttons look like:
 
image
whereas vanilla 3.0 looks like:
image

### Describe the solution you'd like

make the button look like:
image

### Describe alternatives you've considered
None except having oddly styled buttons

### PR DESCRIPTION
**Pull request by mxmou**
Resolves #642
Resolves #1699
Resolves #3136
Resolves #1092
Resolves #3733
Related to #3072

### Changes

* Changes the border radius of most buttons to 8px to match scratch-www.
* Makes most white buttons either blue or gray
* Makes the footer and profile comments much more similar to their scratch-www equivalents. (Is there a good way to make the avatar outlines affected by the addon for customizing them?)
* Improves the top part of the profile page:
image
image
* Replaces the outdated box design of forum posts with scratch-www style comment bubbles:
image
* scratch-www style pagination
* Replaces weird navigation in My Stuff and Account Settings with this:
image
* Makes the pages that appear when clicking various "View All" links more similar to the search page.
* Changes the user-id addon slightly and adds dynamic enable/disable to it.
* Makes loading spinners look like the scratch-www ones.

### Reason for changes

Consistency with scratch-www

### Tests

To make testing loading spinners easier:
* Comments: go to https://scratch.mit.edu/users/gdpr0000001/
* My Stuff: block the request to /site-api/projects/all/​
* posting a comment, following/unfollowing a forum topic: create a network throttling profile with maximum latency.

### CODE REVIEW

**Comment by RedGuy12** [comment]
The forum posts look off. And why remove the navigation we have now?

**Comment by WorldLanguages** [comment]
> Replaces the outdated box design of forum posts with scratch-www style comment bubbles:

I don't think forumers will like this one.

**Comment by mxmou** [comment]
> Also validate addon manifest is failing

I think that's because the schema doesn't include `"type": "map"` (added in #3950) yet.

**Comment by lisa-wolfgang** [comment]
If we're going for consistency with scratch-www, the My Stuff and Account Settings categories should stay horizontal (like the studio tabs) and there shouldn't be so much space between the forum author and the post bubble.

**Comment by RedGuy12** [comment]
I've had a chance to look closer at this.
image
This empty space needs to be removed.

image
And this should be moved out of the bubble.

image
graham made this, pls add

**Comment by mxmou** [comment]
> If we're going for consistency with scratch-www, the My Stuff and Account Settings categories should stay horizontal (like the studio tabs) ...

Yes, horizontal tabs would look even more consistent with scratch-www, but I don't think changing the way things are arranged is a good way to achieve that - the tabs themselves are more important. I tried to avoid changing the layout too much in other places too.

> ... and there shouldn't be so much space between the forum author and the post bubble.

> This empty space needs to be removed.

I don't want to break the formatting of posts. That means their width can't be changed, so there needs to be empty space somewhere. I could try to make it more balanced though:
image

> And this should be moved out of the bubble.

I don't think so - the Quote button has a similar function to the comment reply button, which is inside the bubble.

> graham made this, pls add

I'm not sure if that looks weird to me because I'm used to seeing square quotes or because it's actually weird, but it does.

I think nested comment bubbles would look better (at least if the quotes aren't used for formatting):
image

**Comment by mxmou** [comment]
> > Replaces the outdated box design of forum posts with scratch-www style comment bubbles:
> 
> I don't think forumers will like this one.

I don't think all forumers will dislike it either. Should it be optional?

**Comment by CST1229** [comment]
> > > Replaces the outdated box design of forum posts with scratch-www style comment bubbles:
> > 
> > 
> > I don't think forumers will like this one.
> 
> I don't think all forumers will dislike it either. Should it be optional?

Yes.

**Comment by WorldLanguages** [comment]
> I don't think all forumers will dislike it either. Should it be optional?

It could be a toggle in the scratchr2 addon, or even a separate addon is fine IMO.

**Comment by RedGuy12** [comment]
Resolves #1092 as well

**Comment by Secret-chest** [comment]
> Resolves #642
> Resolves #1699
> Resolves #3136
> Resolves #3733
> Related to #3072
> 
> ### Changes
> 
> * Changes the border radius of most buttons to 8px to match scratch-www.
> * Makes most white buttons either blue or gray
> * Makes the footer and profile comments much more similar to their scratch-www equivalents. (Is there a good way to make the avatar outlines affected by the addon for customizing them?
Finally!
> * Improves the top part of the profile page
> image
> image
Nice
> * Replaces the outdated box design of forum posts with scratch-www style comment bubbles:
> image
They should be tabs, not pill buttons.
> * Makes the pages that appear when clicking various "View All" links more similar to the search page.
Nice.
> * Changes the user-id addon slightly and adds dynamic enable/disable to it.
Ok
> * Makes loading spinners look like the scratch-www ones.
> 
Nice
> ### Reason for changes
> 
> Consistency with scratch-www
> 
> ### Tests
> 
> To make testing loading spinners easier:
> * Comments: go to https://scratch.mit.edu/users/gdpr0000001/
> * My Stuff: block the request to /site-api/projects/all/​
> * posting a comment, following/unfollowing a forum topic: create a network throttling profile with maximum latency.

**Comment by mxmou** [comment]
> > I don't think all forumers will dislike it either. Should it be optional?
> 
> It could be a toggle in the scratchr2 addon, or even a separate addon is fine IMO.

Disabled by default?

**Comment by WorldLanguages** [comment]
> Disabled by default?

Yeah imo

**Comment by mxmou** [comment]
Forum posts now look like this by default:
image

**Comment by WorldLanguages** [comment]
Beautiful

image

Let's hope users like this update lol

**Comment by lisa-wolfgang** [comment]
I wonder how many users will think that Scratch officially updated all their pages 😅

**Comment by WorldLanguages** [comment]
Feedback:

> Alright I'm not gonna waste any time. I don't like the new updates for the 2.0 > 3.0 option. specifically the "My Stuff" page looks so much worse with the tabs on the sides being circles and the projects being spaced out not only looks bad, but makes things more annoying to click on since now you have to click on a specific area. Specifically the tabs on the left of all the projects, now you have to click on where the text is which is far more annoying then the big and blocky tab. And I don't want to use the 2.0 look since I don't like how that looks at all. I really only wish for that part of the update to be reverted

By: `BigJeff2006/Jeffinator`

**Comment by mxmou** [comment]
I'm not sure what "projects being spaced out" refers to - there was already space between projects before this PR. Increasing the click target of tabs is possible though.

**Comment by WorldLanguages** [comment]
Feedback: 

> Hey there, I just recently enabled the Scratch 2.0 → 3.0 addon. In the scratch forum in a section like "Help with scripts", there is, right above and below the list of latest and pinned topics, a pagination menu. With the Scratch 2.0 → 3.0 addon enabled, borders appear around the items in the pagination menu.
I think that those borders are to close to the items that they're surrounding. I suggest that to deal with the problem maybe the padding is changed from "0 5px", to "5px 10px" or something else that looks good, but not crammed.
Thank you!

**Comment by mxmou** [comment]
5px 10px would look like this:
image
image

I prefer the smaller padding because the rest of the forums UI is quite compact.

**Comment by DNin01** [comment]
Maybe the padding could be increased wherever it generally has enough space to fit and would look good next to other elements on the same page.

**Pull request merged**
