### PR TITLE
Add jsdoc to everything

### PR DESCRIPTION
**Pull request by apple502j**
- Adds JSDoc
- Removes `Tab.getScratchVM` - dead code and doesn't work anyway.
- Adds `msg.locale` for background scripts for consistency

### CODE REVIEW

**Comment by Hans5958** [comment]
Is this different than https://github.com/ScratchAddons/ScratchAddons/tree/jsdoc-ify?

**Comment by apple502j** [comment]
This PR just adds normal JSDoc. It does nothing to obfuscate the internal class names used.

**Comment by apple502j** [comment]
Closing for now

**Review by WorldLanguages — APPROVED** [review]

**Comment by WorldLanguages** [comment]
I can confirm this resolves #541 in Visual Studio Code. Simply add this comment on the first line of the file (content scripts):
`/** @typedef {import("../../addon-api/content-script/typedef.js").UserscriptUtilities} UserscriptUtilities @param {UserscriptUtilities} */`

**Pull request merged**
