### PR TITLE
Old love/favorite icons

### PR DESCRIPTION
**Pull request by illogicalapple**
Reverts the new icons back to the old ones, as many people have been complaining about the new, colorblind-friendly ones.

### Reason for changes

Lots of people are complaining the new icons are weird, so including it in an addon would probably make sense because  colorblind people don't have to turn the addon on.

### Tests

This has been tested and seems to work perfectly.
image

### CODE REVIEW

**Comment by mxmou** [comment]
The ST is still working on more accessibility improvements (for example LLK/scratch-www#7306). I don't think it makes sense to provide an option to revert every single minor change.

**Comment by illogicalapple** [comment]
> The ST is still working on more accessibility improvements (for example LLK/scratch-www#7306). I don't think it makes sense to provide an option to revert every single minor change.

Your argument makes sense, but it still really annoys me when I see that weird black border. I'm not sure about other people, but seeing as the project about this literally got top loved, I think lots of people would benefit from this addon.

**Comment by illogicalapple** [comment]
> > The ST is still working on more accessibility improvements (for example [LLK/scratch-www#7306](https://github.com/LLK/scratch-www/pull/7306)). I don't think it makes sense to provide an option to revert every single minor change.
> 
> Your argument makes sense, but it still really annoys me when I see that weird black border. I'm not completely sure about other people, but seeing as the project about this literally got top loved, I think lots of people would benefit from this addon.

Besides, with new things like that I could just rename the addon to some other thing and make it handle all of those changes.

**Comment by DNin01** [comment]
This is a relatively small-ish detail and a really small change at scale, and if I were applying to my own website, I feel like it wouldn't deserve its own on/off switch, and there are going to be more changes like these in the future. I also don't think having these new icon designs hurt the website that much for being the only option - I know the majority of people won't mind them (much less than the high contrast blocks, anyway). That's just how these icons are.

This small change also has a big effect for accessibility, and it's a really, really good in-between, too. If this were how it looked for the past 10 years, I don't think anyone would mind.

I'm neutral on this option, but I understand the incentive.

**Comment by illogicalapple** [comment]
> This is a relatively small-ish detail and a really small change at scale, and if I were applying to my own website, I feel like it wouldn't deserve its own on/off switch, and there are going to be more changes like these in the future. I also don't think having these new icon designs hurt the website that much for being the only option - I know the majority of people won't mind them (much less than the high contrast blocks, anyway). That's just how these icons are.
> 
> This small change also has a big effect for accessibility, and it's a really, really good in-between, too. If this were how it looked for the past 10 years, I don't think anyone would mind.
> 
> I'm neutral on this option, but I understand the incentive.

Just mentioning, look at my screenshot above, that's on the project that complains about the change; people do mind.

**Comment by DNin01** [comment]
> > This is a relatively small-ish detail and a really small change at scale, and if I were applying to my own website, I feel like it wouldn't deserve its own on/off switch, and there are going to be more changes like these in the future. I also don't think having these new icon designs hurt the website that much for being the only option - I know the majority of people won't mind them (much less than the high contrast blocks, anyway). That's just how these icons are.
> > This small change also has a big effect for accessibility, and it's a really, really good in-between, too. If this were how it looked for the past 10 years, I don't think anyone would mind.
> > I'm neutral on this option, but I understand the incentive.
> 
> Just mentioning, look at my screenshot above, that's on the project that complains about the change; people do mind.

There will always be people who mind. I'm just saying that I know the majority of people will be fine with the change.

**Comment by BroJac5246** [comment]
Originally I supported this, but I think it's too small of a change, and Scratch has clearly implicitly announced that more changes will happen. Because of this, I no longer think this addon should be added. We can't add a features to revert every change, and we'll get used to the new icons soon. Change is hard, but accessibility is infinitely more important.

**Comment by WorldLanguages** [comment]
> Lots of people are complaining the new icons are weird

It would be useful to have some links. We can check back in a few weeks if people are still complaining. If that's the case we should consider adding this addon even if we aren't fully convinced.

**Comment by DNin01** [comment]
> > Lots of people are complaining the new icons are weird
> 
> It would be useful to have some links. We can check back in a few weeks if people are still complaining. If that's the case we should consider adding this addon even if we aren't fully convinced.

Key word: consider -- sounds okay to me.

**Comment by WorldLanguages** [comment]
@illogicalapple How has it been? Have you been running this addon locally or did you get used to the new accessible icons?

Anyone else reading this have any opinions to share?

**Comment by illogicalapple** [comment]
> @illogicalapple How has it been? Have you been running this addon locally or did you get used to the new accessible icons?
> 
> Anyone else reading this have any opinions to share?

I still think the new icons look icky, but haven't been using scratch all that much. I mostly just stay in the editor where there haven't been any changes I've noticed.

**Comment by WorldLanguages** [comment]
I'm closing this PR.
If anyone reading is interested on this new addon/feature, please open an issue with the "new addon" template and link to this PR.  This PR was opened without any linked issue, so it needs to be created.

**Pull request closed without merging**
