### PR TITLE
editor-comment-previews: re-add featured tag

### PR DESCRIPTION
**Pull request by lisa-wolfgang**
Once upon a time, there was a lush, green land with a kingdom named Scratch Addons, ruled by the noble and mighty World_Languages and his wise advisor, Apple, from the comfort of the lavish GitHub Castle. The land was blessed with a rich and mysterious resource, known to mortals as "addons." World_Languages distributed the addons to the people, which brought joy to all the land. Some addons were very fine in quality, bringing greater joy and therefore the most popular choices, and some had lesser importance, bringing lesser joy and therefore often picked over.

One day, it was a bright and sunny day in the kingdom. The birds were chirping, and the air was fresher than ever. The kingdom was in a golden age, with the land plentiful in new and rich addons. The people were happy. The council was happy. Even the king was happy... well, Apple was getting on his nerves as usual, but that's not important. Everyone was happy.

As the sun rose to the peak of the pearly blue sky, the hero of our story, Lisa (a member of World_Language's council) embarked on a routine addon-gathering quest. Quaking at the thought of entering Scratch-Source-Code Jungle for the second day in a row, Lisa decided to wander randomly through the forest. Strolling under a sun-pierced canopy, the hero suddenly noticed a strange disturbance in the vicinity. Investigating further, he discovered an addon of great riches -- one that had the ability to manipulate the time-space continuum of Scratch editor comments.

Delighted by this discovery, Lisa promptly returned to the castle to inform the king of the most excellent news. The king, however, had been tainted by the prosperity of the kingdom, becoming spoiled and arrogant.

"Oh, *come on*," he bellowed from atop his gleaming throne. As usual in those days, he was not pleased. "ANOTHER good addon? And nobody even requested it. I mean yes, but no. That's it. It's going in the *others* category." He said the word "others" like they belonged in some kind of dumpster.

Lisa was shocked. "What is the meaning of this? Is there any specific reason?"

"Well, yes, but it's kinda bad... Lisa, we have too many good addons in this release."

Lisa was shocked yet again. "What do you mean 'too many'?"

"Lisa, I am happy with the amount of fine-quality addons I am distributing this cycle. I fear that our feeble-minded citizens cannot handle more than four of them at once. It could cause riots in the streets, or worse, Apple could get a promotion." Apple, listening from the corner, grunted disapprovingly. The king continued, "Lisa, we can move the addon from the *others* bin next distribution cycle."

Lisa was shocked to the point of electrocution. "But the addon will spoil by then! People only care about the freshest addons. Only peasants look in the others bin!"

"It is too late, Lisa. I have already made up my mind, and as leader of Scratch Addons, I must be a model of decisiveness for the feeble-minded citizens. Do not worry. We are currently researching a revolutionary machine that will rejuvenate addons! Right, research team?"
He turned his head to the research team, who was drawing a fake mustache on a picture of griffpatch's face, and looked away as quickly as he could.
"It's fine, it's all under control. *My* control."

"But your highn--"

"No."

With the verdict settled -- because to challenge the king was to commit treason -- Lisa begrudgingly departed from the throne room.

The next day, King World_Languages ordered the Chrom Committee to distribute the new addons. The Committee still had a shortage of funding for horses, so they loaded the addons onto a cart pulled by turtles. One day later, the turtles made it out of the castle, and it took another two days to make it to the addon market. The citizens of the kingdom burst into joy as they saw all the new fine-quality addons that were ripe for the taking, and the others bin, as expected, was largely ignored.

The head of the official newspaper of the kingdom, CoolScratcher, caught wind of the plight that had befallen the addon. In the next issue, he criticized the king's decision to put the editor comment preview addon in the others bin. People read the paper and thought, "Huh, cool addon. Yeah, shoulda been featured." Then they went back to their blissful, oblivious daily lives.

Our hero, after having read the paper, returned to the castle to confront the king once again.

"Lisa! Great news! We will move the addon to the fine-quality bin next distribution cycle!"

Lisa replied cheerfully, "Lol okay!"

Both the king and our hero completely forgot about the entire fine-quality addon scandal.

The End

---

Epilogue

It was a dark and stormy night in GitHub Castle, and the halls were filled with a tense aura. After yet another day of getting on the king's nerves, Apple decided that they were fed up with their subordinate treatment. So they decided to commit a tiny act of rebellion. Apple discovered a minor display issue on the addon marketplace's bulletin board and advised the king to release a fix as soon as possible. But the dictator was feeling lazy, and the last thing he wanted to do was actually address a months-old issue, so he replied, "Oh, the bulletin is messy and it's an old problem anyway, let's put it off some more." Then Apple did the unthinkable: they went ahead and sent bulletin maintenance without World_Language's direct approval.

The next day, when the king saw the atrocious treason that Apple had committed, their internal reaction was that of great rage. "How dare they rebel against the order! Against my control!" However, the king was feeling lazy, and the last thing he wanted to do that day was deal with the complications of treason against his own advisor, so he merely glared at them, rolled his eyes, and said, "Ugh. Fine, Apple."

The council burst into laughter and continued all afternoon.

### CODE REVIEW

**Comment by TheColaber** [comment]
lol

**Comment by FunctionalMetatable** [comment]
> Only peasants look in the others bin!

oh no all my addons were in the others bin aaa

**Comment by Samq64** [comment]
This PR's description is a first.

> Only peasants look in the others bin!

I always look in the others bin and buy most of the add-ons there unless it's something I obviously won't use. If I don't end up liking it or using it, I just sell it.

**Comment by RedGuy12** [comment]
~~peasant~~

**Comment by GrahamSH-LLK** [comment]
> > Only peasants look in the others bin!
> 
> oh no all my addons were in the others bin aaa

One of my addons is in the underground bin that you have to dance and sing to get to.

**Comment by CST1229** [comment]
> 
> 
> > Only peasants look in the others bin!
> 
> oh no all my addons were in the others bin aaa

Both of my addons are in the fine-quality bin 😎

**Comment by WorldLanguages** [comment]
oh god this is fantastic

**Comment by Cool-Scratcher** [comment]
Why was my role so small?!?! Couldn't I have been, like, the hero's savior?? but no! I had to be a newspaper guy. Ugh.

Great story lol. Maybe we can do a funny scratchaddons arg or something 👀

**Comment by lisa-wolfgang** [comment]
> Why was my role so small?!?! Couldn't I have been, like, the hero's savior?? but no! I had to be a newspaper guy. Ugh.

@Cool-Scratcher At least you weren't the guy whose face was being drawn on 😄

**Comment by CST1229** [comment]
> 
> 
> Why was my role so small?!?! Couldn't I have been, like, the hero's savior?? but no! I had to be a newspaper guy. Ugh.
> 

I mean, it does kinda reflect your real role as mainly the update video guy.

**Comment by Cool-Scratcher** [comment]
> > Why was my role so small?!?! Couldn't I have been, like, the hero's savior?? but no! I had to be a newspaper guy. Ugh.
> 
> @Cool-Scratcher At least you weren't the guy whose face was being drawn on 😄

Good point.

**Comment by Cool-Scratcher** [comment]
> I mean, it does kinda reflect your real role as mainly the update video guy. 
ik it was a joke lol

WL merge this pr

**Comment by rirurin** [comment]
yo sa lore
hype

**Pull request merged**
