### PR TITLE
Localize everything

### LINKED ISSUE #480: Localize addons (NOTE: All PRs are on hold!)
It's likely too early to focus on this, but I want to create the issue. It would be nice if addon titles, descriptions, warnings, setting names, etc. could be localized. There could also be an `addon.i18n` API or similar, in order to get localized strings from userscripts or popups.

### LINKED ISSUE #703: Console log will be flooded on Firefox
**Describe the bug**
Console log gets flooded by 297 SA logs describing "messages from background", at least on Firefox.

**To Reproduce**
Open new tab (for example, front page) then open console.

**Expected behavior**
No (or a few) debug messages

**Device (please complete the following information):**
win10, firefox82.0.3

**Additional context**
Log:
[flooded log.txt](https://github.com/ScratchAddons/ScratchAddons/files/5516947/flooded.log.txt)

### LINKED ISSUE #727: Fix wrong HTML on DevTools
image

### LINKED ISSUE #750: Clicking version number opens two tabs
Open popup
Find the version number
Click
It opens two tabs
Because both href and event handler does the thing

### PR DESCRIPTION
**Pull request by apple502j**
**Resolves**
Resolves #480
Resolves #727 
Resolves #750 

**Changes**
Many changes. Ask me for details.

**Reason for changes**
Obvious

### CODE REVIEW

**Comment by pufferfish101007** [comment]
Are the addon tags localised?

**Comment by Hans5958** [comment]
Isn't it bad to change the JSON so it almost empty, when you can do, you know, put the English strings there as the baseline/default and then use the other language translations when it is needed/existed?

**Comment by YOYITsM3M8** [comment]
Umm lol

**Comment by GrahamSH-LLK** [comment]
On the subject of translation, should we use something like Crowdin? It would lower the annoyance of having a million "localization prs." Just a thought...

**Comment by apple502j** [comment]
@pufferfish101007 They are, on Settings page (addon JSON is untouched)

**Comment by apple502j** [comment]
@Hans5958 Old ones still work, I just replaced all because this is what the PR's purpose is.

**Comment by WorldLanguages** [comment]
> Isn't it bad to change the manifest so it is almost empty, when you can do, you know, put the English strings there as the baseline/default and then replace those with the translation of another language when it is needed/existed?
Just telling so it is still easy to implement new addons without an hassle of adding the translation files, but still able to be translated in a later time.

I got confused by this, but what you mentioned is actually what the PR does. If you don't specify `null` in the manifest for a property, it uses what you specified.

**Comment by Hans5958** [comment]
> 
> 
> @Hans5958 Old ones still work, I just replaced all because this is what the PR's purpose is.

No, what I meant is to keep the English names and descriptions on the manifest, whilst the other languages can go to the addons-l10n pages

**Comment by Hans5958** [comment]
@WorldLanguages @apple502j please respond

**Comment by apple502j** [comment]
In case we use the platforms like Transifex or Crowdin, having the source translation as a separate file helps when setting up the stuff.

**Comment by Hans5958** [comment]
I'd still rather having the strings also on the manifest.json, and have the "en" only as a reference for the translation tool only.

**Comment by WorldLanguages** [comment]
@Hans5958 So you're saying you want all English localizations to be duplicated?

**Comment by WorldLanguages** [comment]
> I don't want to have the bars higher because people needed to consider another thing.

People only need to consider this if they consider localization as well. We won't reject addons because they aren't ready to be localized. We will do the work ourselves, or keep it unlocalized.

**Comment by Hans5958** [comment]
Yes. I think this makes it easier for outsiders to develop without minding the business of the l10n, and it's just an easy duplication* to set it up for translation. I could go up and make a CI of this so if we need it

Except if there are conflicts, probably also modify the translation pages so the language tool knows if that needs to be updated, if that''s a thing.

**Comment by Hans5958** [comment]
Also, opt- instead of settings-. Come on, another refactor?

oslA, it's interesting when you do dashes to separate "level1-level2-level3", instead of "level1/level2/level3" (I don't know, and hope this is intended)

**Review by WorldLanguages — CHANGES_REQUESTED** [review]
My final say for the current state of this PR
1) Instead of `@opt-`, I'd prefer something like `@settings`. So `discuss-button/@opt-name-removeIdeasBtn` would now be `discuss-button/@settings/removeIdeasBtn`. (BTW: why is the addon ID at the beginning even necessary? It's on the name of the json file)
2) I agree with @Hans5958 on the fact English localization should be in `addon.json`. For a potential GUI based translation service, we could make a script that automates a pseudo-localization-file for English, so that we can get working localization files for other languages. This would mean there would be no `null`s over manifests.
3) I'm not sure about the current state of giving addon scripts both a `msg` and `safeMsg` function. IMO, we should pass an `l10n` object with both functions on it.
4) My current browser language is `en-US`, so I get lots of console errors in the background because it's attempting to get localizations for `en-US`, and we only have them for `en`. IMO it should stop looking for translations if `_general.json` isn't found. Alternatively, we could have a language-codes.json file of some sort. (This is not a big deal, since it's normal to see errors raise from the "inject-css-asap" code often, but the lesser errors the better)

**Comment by WorldLanguages** [comment]
Regarding 2, just an idea: we should probably have another repo for translations, then "merge" those into this one before each release. That repo could also handle the translation of strings present on the extension web stores, like descriptions, and maybe screenshots, so that translators can help with those the same way they translate extension strings.

**Comment by Hans5958** [comment]
I don't think a second repo is needed as if we used a translation tool we can set up an integration for it. But, you can do it just in case we need it IG.

**Comment by GrahamSH-LLK** [comment]
> I don't think a second repo is needed as if we used a translation tool we can set up an integration for it. But, you can do it just in case we need it IG.

Agreed.

**Review by WorldLanguages — APPROVED** [review]
1) Was partially solved, but fine, I guess you have programming reasons to keep it like this
2) Solved
3) Wasn't solved but fine
4) Wasn't solved, but can be fixed later normally since it's not a addon developer facing change

**Comment by WorldLanguages** [comment]
@Hans5958 I'll merge this tomorrow, please comment now if you have something to say after the new changes.

**Comment by Hans5958** [comment]
Another one. Just wanted to point out that there are some setting id that uses underscore and ones that uses dashes? Probably equalize them (or maybe use camelCase)?

**Comment by WorldLanguages** [comment]
IMO we should just make the syntax `addon-id/@settings-names/settingId_or_id`

**Comment by Hans5958** [comment]
BTW, @mxmou just merged #699 without the permission. Probably also make changes for them?

**Comment by apple502j** [comment]
@Hans5958 @WorldLanguages  Messages are snake-case, unless it's a setting message (which requires changing setting ID - no thanks)

**Comment by Hans5958** [comment]
I have did necessary changes with the manifest. Just merge master and it should be green.

**Comment by Hans5958** [comment]
* not counting the library property

**Pull request merged**
