### PR TITLE
Remove forum-time-zones and image-uploader

### LINKED ISSUE #2426: "Use local timezone on forums" doesn't work in the "last edited" section
**Describe the bug**

"Use local timezone on forums" addon doesn't convert the "last edited" section to the user's timezone.

**To Reproduce**

1. Go to a forum post that has been edited with the "Use local timezone on forums" addon enabled **(Make sure your timezone is different from scratch's timezone!)**
2. See that the hour shown in the "last edited" section isn't converted to your timezone.

**Expected behavior**

The "last edited" section should also be converted to the user's timezone.

**Screenshots**

Screenshot 2021-05-07 183923

("Azi" and "Astăzi" translate to "Today" in romanian, if you are wondering)

**Device (please complete the following information):**

- OS: [e.g. Windows 10]
- Browser [e.g. chromium (opera GX)]
- Version [e.g. lastest]

**Additional context**

My timezone shows that at the moment of writing (and making the screenshot), it was almost 19:00 (If that helps you somehow XD).

### LINKED ISSUE #2698: "Use local timezone on forums" should adjust dates in "Last Post" listings, too
### Is your request related to a problem? Please describe.

Ideally, the "use local timezone on forums" addon would make timestamps consistent across the whole site. There are a few places it currently doesn't, including a subforum/category/topic list's "Last Post" column.

### Describe the solution you'd like

Make 'em consistent! Adjust dates/times in the Last Post column the same way as for other areas where timestamps show up.

### Describe alternatives you've considered

One alternative is to leave the timestamps exactly as is, inconsistent across the site. This is good for ~~discord~~ chaos and mayhem reasons, which is definitely always a worthwhile factor to consider. :shipit:

### Additional context

See also #2426 for another timestamp this addon doesn't adjust ("last edited" timestamps).

### LINKED ISSUE #6004: image-uploader displays multiple "Uploading..." messages
### Description

When uploading multiple images in quick succession with `image-uploader`, multiple "Uploading..." messages appear. Only the most recent one will get removed when uploading is done.

### Steps to reproduce

1. Copy an image to your clipboard.
2. Go to some forum topic where you can post.
3. Press `Ctrl`+`V` in quick succession.

### Demonstration(s) and additional context

A demonstration of six Uploading... messages at the same time.

### Environment

Browser: Microsoft Edge 114.0.1807.6 (Official build) dev (64-bit) 
Scratch Addons version: 1.31.2
Operating system: Windows 11

### LINKED ISSUE #6911: `forum-time-zones` no longer works
### Description

`forum-time-zones` doesn't work.

### Steps to reproduce

1. Enable `forum-time-zones`
2. Go to a post

### Demonstration(s) and additional context

This is because the mobile forums, which was used by the addon, no longer exist. To fix this, the way the addon works has to be changed.

### Environment

Browser: Edge 119
Scratch Addons version: 1.35.1
Operating system: Windows

### LINKED ISSUE #6913: image links created by `image-uploader` are blocked by the updated forum filter
### Description

So after the 4-5 days of forum downtime, there seem to be a lot of changes to the post filter, which in turn blocks posting image links created by the `image-uploader` addon.
https://github.com/ScratchAddons/ScratchAddons/blob/f595f3b0f97ca50b8fc18f17674e7105c6e6b696/addons/image-uploader/userscript.js#L139

### Steps to reproduce

1. Try to post with an image uploaded using the `image-uploader` addon

image

*I know this isn't a bug caused by SA, but the functionality of this addon has been hindered.*

### PR DESCRIPTION
**Pull request by Samq64**
Resolves #6911
Resolves #6913
Closes #2426
Closes #2698
Closes #6004

### Changes

Removes the `forum-time-zones` and `image-uploader` addons.

### Reason for changes

They've been broken for 8 months.

### Tests

Tested briefly on Chromium.

### CODE REVIEW

**Review by WorldLanguages — APPROVED** [review]
Should add these IDs here https://scratchaddons.com/docs/develop/getting-started/creating-an-addon/#creating-the-addon-folder

**Comment by WorldLanguages** [comment]
It's scary to delete addons so if we could get more approvals it would be great 😪

**Review by mxmou — APPROVED** [review]

**Comment by Samq64** [comment]
Do the non-English files in addons-l10n also need to be removed?

**Comment by WorldLanguages** [comment]
> Do the non-English files in addons-l10n also need to be removed?

In theory they should get removed automatically.

**Pull request merged**
