### PR TITLE
Line breaks in comments

### LINKED ISSUE #207: [New addon] Recover '\n' in comments
**Describe the new addon**

So you know that line breaks are impossible in comments? No, not really. They get somehow represented as a space, but acutally they still have the character code 10 instead of 32 like a regular space. I really don't know why they're not displayed since they're still there but I think that we should be able to somehow recover them.

I found that out by accident when I looked at some stuff I can do with comments. Every comment ends with a '\n' and that really confused me. So I made some more test and it seems like I'm right.

**Link to the new addon**

Doesn't exist.

~~Oh, btw, could that be enabled by default as a fix?~~

### PR DESCRIPTION
**Pull request by NoobTracker**
**Resolves**

It's just neat to see line breaks in comments.

Resolves #207 

**Changes**

I just added the addon.

**Reason for changes**

Reasons.

**Tests**

It works I guess.

Why has this problems with auto merging? Edit: Whatever it was, now it's gone.

### CODE REVIEW

**Comment by NoobTracker** [comment]
So now the question is if it's a fix ...

**Comment by NoobTracker** [comment]
Stopstopstopstop that completely messes up comment chains.

**Comment by NoobTracker** [comment]
Okay I think I know how to solve the problem.

**Comment by NoobTracker** [comment]
Do you think that it makes sense to have this as a beta that only works for 3.0 pages?

**Comment by NoobTracker** [comment]
Wow I really have serious problems: Links (@ mentions) are removed by using textContent and since I can't use innerHTML that's kinda not so neat.

**Comment by NoobTracker** [comment]
So now I realized that the 3.0 version could work as a beta. It would add a new line to every single comment at the end but it would add the line breaks. But that's kinda pointless ....

**Comment by NoobTracker** [comment]
Okay. I really have no clue how to find out where all those links are because I don't know how to find out which part of a textContent string is in a child and I dunno what to do. @JeffaloBob do you have an idea?

**Comment by JeffaloBob** [comment]
ask @WorldLanguages they are very smart

**Comment by mxmou** [comment]
> Okay. I really have no clue how to find out where all those links are because I don't know how to find out which part of a textContent string is in a child and I dunno what to do. @JeffaloBob do you have an idea?

I don't think you can do that with just `textContent`. You should somehow iterate over the elements and text nodes.

**Comment by NoobTracker** [comment]
What are text nodes?

**Comment by BoomerScratch** [comment]
@NoobTracker 
```javascript
document.createTextNode("Hello World");
```
Basically, elements/nodes without tags: only text.

**Comment by NoobTracker** [comment]
Ah okay. So
`<span id="thisissomethingyoushouldntforgetandalsokeepshortokayijustfailed">This is the first text node? <div> this is something else </div> and this again another text node?</span>`

**Comment by tb148** [comment]
I resolved the merge conflict.

**Comment by Explosion-Scratch** [comment]
This _could_ be the 100th closed PR...

**Comment by NoobTracker** [comment]
How awesome.

**Comment by BoomerScratch** [comment]
Resolved another merge conflict.

**Comment by JeffaloBob** [comment]
does it work?

**Comment by NoobTracker** [comment]
No, not at all.

**Comment by NoobTracker** [comment]
At least not how it should. It removes a lot of stuff including links and it messes up the reply stuff.

**Comment by towerofnix** [comment]
@NoobTracker I tried reworking your code, I think it works pretty well (haven't tested on migrated scratch-www (i.e. project) pages though): NoobTracker/ScratchAddons#1

**Comment by NoobTracker** [comment]
Great!

**Comment by NoobTracker** [comment]
Okay now the question is: Is this a fix?

**Comment by NoobTracker** [comment]
Okay, now it actually works! @towerofnix can you quickly add yourself to the credits?

**Comment by towerofnix** [comment]
@NoobTracker sure, done: NoobTracker/ScratchAddons#2

**Comment by NoobTracker** [comment]
Project pages work, but it seems like it's sometimes broken or does nothing at all besides displaying the line breaks. But so far it didn't hide any text, just didn't remove the whitespace properly.

**Comment by towerofnix** [comment]
Did you make any modifications to the code on your machine to get it to work on project pages? Right now it just doesn't do anything for me (testing [here](https://scratch.mit.edu/projects/402624338/)).

**Comment by towerofnix** [comment]
(Oh apparently this breaks newly appended replies, oops gotta check that)

**Comment by NoobTracker** [comment]
Ah okay probably it's that. I forgot to say that it only effects replies.

**Comment by NoobTracker** [comment]
Could this be merged as beta? 95% of it work.

**Comment by WorldLanguages** [comment]
@NoobTracker, can you clarify what's currently missing on this addon for it to be considered 100% complete?

**Comment by NoobTracker** [comment]
@WorldLanguages This is the problem:


> 
> 
> (Oh apparently this breaks newly appended replies, oops gotta check that)

I also noticed that my old script that just alerts the content of a comment doesn't do anything when you reply to something and don't refresh the page.

**Comment by NoobTracker** [comment]
Probably we just need to change the selector a little bit but since I'm currently banned, I can't reply to things so can't test some stuff.

**Comment by Hans5958** [comment]
I'm sorry to tell you, but due to my mistake on the end, I accidentally force-pushed into the master branch, closing this pull request as the result. I have reversed the changes, but I can't reopen the pull request, so you need to make another pull request for this one.

Once again, I apologize for the inconvenience that caused from my mistake.

**Comment by NoobTracker** [comment]
Not a huge problem. It currently doesn't work anyway, at least not as good as I hoped. As soon as I'm unbanned (probably not in the next 5 days or so) I'll test some stuff with the comments and what happens and which selectors are used when you reply.

**Pull request closed without merging**
