### PR TITLE
Iconfont

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
I did the impossible - I turned most of the SVGs into an icon font.
----
In seriousness:
- I skipped the popup b/c I didn't want conflicts from the popup PR, I'm going to wait for it to be merged
- I haven't finished a few other items

### Why this is helpful:
Right now, many of our icons look warped because we are using ``filter: brightness()`` to color them. Using an icon font allows us to easily color them with `` color: color``. It also allows us to use any icon, without downloading it.

### CODE REVIEW

**Comment by Hans5958** [comment]
By the way, have you guys considered using `fill: [color]`?

**Comment by GrahamSH-LLK** [comment]
> By the way, have you guys considered using `fill: [color]` on the SVG?
It doesn't work on non inline svgs.

**Comment by WorldLanguages** [comment]
Instead of using an icon font, let's use better CSS that does not make SVGs look pixelated.

**Comment by GrahamSH-LLK** [comment]
> Instead of using an icon font, let's use better CSS that does not make SVGs look pixelated.

In progress.

**Pull request closed without merging**
