### PR TITLE
Editor Tab Customizability 

### PR DESCRIPTION
**Pull request by YandeMC**
### Changes
- Show only the icon on the tab.
- Turn the tabs into nice looking chips!
(both are toggleable) 

https://user-images.githubusercontent.com/113806118/229309736-dada6b95-e71a-4875-95f0-d9d8b03e6dc3.mp4

sorry for windows not recording the extention popup

### CODE REVIEW

**Comment by Samq64** [comment]
Related:  #4018, #5761, #5840

**Comment by StioStudio** [comment]
This should be put together with my compact buttons. The name of it should probably just be "compact buttons" like what I allready have

**Comment by DNin01** [comment]
StioStudio means this PR: https://github.com/ScratchAddons/ScratchAddons/pull/5840

**Comment by Secret-chest** [comment]
Why are you turning everything into chips?

**Comment by WorldLanguages** [comment]
@YandeMC Congrats on your first(?) addon!

**Comment by WorldLanguages** [comment]
> Related: #4018, #5761, #5840

I'm pretty sure the "only show icon" feature of this PR would better belong in one of those PRs, instead of a separate new addon.

Turning the tabs into "chips" looks like over-customization. We suggest users write their own Stylus userstyles at that point.

**Comment by WorldLanguages** [comment]
In my opinion the "only show icon" feature should be a togglable setting for #4018

**Comment by YandeMC** [comment]
Thanks for the feedback! yeah ill do that.

> Congrats on your first(?) addon!
yup this is my first!

**Pull request closed without merging**
