### PR TITLE
folders: use context menu API

### LINKED ISSUE #3468: Refactor folders addon context menu
I forgot that addon had a dynamic context menu - that'll be hard to do using the new API. Should we just keep using the good ol' way?

### PR DESCRIPTION
**Pull request by apple502j**
Resolves #3468

### CODE REVIEW

**Comment by WorldLanguages** [comment]
@GarboMuffin Can you review?

**Comment by GarboMuffin** [comment]
Found a small bug: right click folder > rename > cancel causes the folder to open/close. Otherwise this seems to work fine

**Comment by apple502j** [comment]
@GarboMuffin fixed (click event was propagating)

**Comment by WorldLanguages** [comment]
TODO: fix initialize being called before document.body is defined

**Pull request merged**
