### PR TITLE
Add dynamic enable and disable to popup addons

### PR DESCRIPTION
**Pull request by TheColaber**
It resolves nothing, it's just good to know that these are dynamic enable and disable already since they have persistent scripts/popups

### CODE REVIEW

**Review by RedGuy12 — APPROVED** [review]

**Review by apple502j — APPROVED** [review]

**Comment by WorldLanguages** [comment]
Well, this kinda made dynamicEnable and dynamicDisable lose their meaning 🤔

**Comment by TheColaber** [comment]
> Well, this kinda made dynamicEnable and dynamicDisable lose their meaning 🤔 

Doesn't it mean that these addons can be dynamically enabled and disabled?

**Comment by WorldLanguages** [comment]
Dynamic enabling/disabling only makes sense for userscripts and userstyles.
Addons that don't have any of these two don't have any dinamicity we can toggle. Addon popups are dynamic by design, and can't be made non-dynamic.
So adding these properties to these addons is weird, but ok, I guess it's fine...

**Comment by Samq64** [comment]
> Dynamic enabling/disabling only makes sense for userscripts and userstyles. Addons that don't have any of these two don't have any dinamicity we can toggle. Addon popups are dynamic by design, and can't be made non-dynamic. So adding these properties to these addons is weird, but ok, I guess it's fine...

I think they should be true by default and tell new contributors to set them to false for their first addon, that way we can get rid of 2 lines from almost every addon.json.

**Comment by WorldLanguages** [comment]
@Samq64 The default can't be `true`, since userscripts need extra code for dynamic disable to work. Addons need to opt-in into dynamic disable

**Comment by Weredime** [comment]
Bug: When you open `scratch-messaging` in a new tab and disable it, it still works.

**Comment by TheColaber** [comment]
I don't think it should stop working there, that would be weird. As long as you can't access in the pop up, it isn't considered disabled.

**Pull request merged**
