### PR TITLE
Faster, Better Forum User Count

### PR DESCRIPTION
**Pull request by TheColaber**
**Changes**

Faster, Better Forum User Count...

- Doesn't run on complete
- Shows Count for newly posted posts.

### CODE REVIEW

**Review by WorldLanguages — CHANGES_REQUESTED** [review]
Why did you change forum.js on this PR? The problem appears to be solved already.

**Comment by TheColaber** [comment]
> Why did you change forum.js on this PR? The problem appears to be solved already.

Yeah, you told me to make this one when the other got merged so you could see the differance.

**Comment by WorldLanguages** [comment]
@TheColaber Can you link to when I said that?

**Comment by TheColaber** [comment]
https://github.com/ScratchAddons/ScratchAddons/pull/733#issuecomment-726368776

**Comment by WorldLanguages** [comment]
Oh ok. No worries. @mxmou solved the issue in that PR already. Can you make this PR only keep the change to runAtComplete?

**Comment by TheColaber** [comment]
> Oh ok. No worries. @mxmou solved the issue in that PR already. Can you make this PR only keep the change to runAtComplete?

But what about new posts and posts that haven't loaded yet?

**Comment by WorldLanguages** [comment]
Ohh ok. Keep that. But also keep mxmou's code that adds "posts" after the count.

**Comment by TheColaber** [comment]
> Ohh ok. Keep that. But also keep mxmou's code that adds "posts" after the count.

That wasn't nessaray because the code only runs on posts that have a "+" in it.

**Review by WorldLanguages — APPROVED** [review]

**Pull request merged**
