### PR TITLE
Support studio promotions

### LINKED ISSUE #676: Scratch Messaging and Notifier: support studio promotions
These 2 messaging related addons do not support studio promotion messages yet. They should.

### PR DESCRIPTION
**Pull request by mxmou**
**Resolves**

Resolves #676 

**Changes**

Adds support for studio promotion messages to Scratch Messaging and Scratch Notifier.

**Reason for changes**

#676

**Tests**

Not properly tested.

### CODE REVIEW

**Review by MasimbaTheHuman — COMMENTED** [review]
hmm... promoting would be nice.

**Comment by WorldLanguages** [comment]
This PR will likely conflict with #753

**Comment by mxmou** [comment]
@WorldLanguages That's true. Should I wait until #753 is merged and then resolve the conflicts?

**Comment by WorldLanguages** [comment]
@mxmou Yes

**Comment by WorldLanguages** [comment]
@mxmou Please resolve the conflicts

**Comment by WorldLanguages** [comment]
Closing this, if anyone wants to fix this please open another PR

**Pull request closed without merging**
