### PR TITLE
addon.storage

### LINKED ISSUE #1653: addon.storage API
Would be nice for future addons...

### PR DESCRIPTION
**Pull request by RedGuy12**
# New `addon.storage` API

## Resolves

Resolves #1653 

## Changes

Added new API. The new properties in `manifest.json` are required so 1. I can import from a file that has helper functions and 2. so I can send messages to the background page from the new class.

## Reason for changes

why not

## Tests

yes

## API Documentation

The new API features two methods: `addon.storage.get` and `addon.storage.set`. Both are available in userscripts and background scripts.

### `addon.storage.get(key, mode)`
`key`: Key set with `addon.storage.set` Type string. No need to specify the perfix used internally.
`mode`: Mode used with `addon.storage.set` Type string of value `sync`, `local`, or `cookie`.

### `addon.storage.set(key, value, set)`
`key`: Key for retrieving values with `addon.storage.get` Type string. Will be prefixed with `addon-name/` internally.
`value`: Value to save. Any type.
`mode`: Mode of saving. Type string of value `sync`, `local`, or `cookie`. `sync` will save in `chrome.storage.sync`, `local` in `chrome.storage.local`, and `cookie` in `chrome.cookie`.

### CODE REVIEW

**Comment by TheColaber** [comment]
The whole point was not to use scratch's cookies...

**Comment by RedGuy12** [comment]
> The whole point was not to use scratch's cookies...

i can remove the `cookie` mode, that's the only mode that uses cookies

i made it so sensitive info can be stored (like session ids for an account-switching addon I'm making)

**Comment by TheColaber** [comment]
Why can't you just use `document.cookie` then?

**Comment by TheColaber** [comment]
whoops

**Comment by RedGuy12** [comment]
> Why can't you just use `document.cookie` then?

you could, but when you're communicating between userscripts and background scripts (and popups after #1234) it gets kinda complicated. sometimes use `document.cookie` which is a bit of a pain as it's just a long string of text, sometimes `chrome.cookie` which uses promises, etc, etc, etc.

**Comment by TheColaber** [comment]
iirc the only reason we wanted addon.storage was to store something in the extensions so it's in all devices, not just one. We weren't planning on storing sensitive data. I cannot agree that it is hard to mess with document.cookies. See https://www.w3schools.com/js/js_cookies.asp.

**Comment by RedGuy12** [comment]
> iirc the only reason we wanted addon.storage was to store something in the extensions so it's in all devices, not just one. We weren't planning on storing sensitive data. I cannot agree that it is a pain to mess with document.cookies. See [w3schools.com/js/js_cookies.asp](https://www.w3schools.com/js/js_cookies.asp).

so you're saying we should only have the `sync` mode?

**Comment by TheColaber** [comment]
I am saying, that this is not the API that was asked... this one modifies document.cookies (which already means that this can't be done for persistent scripts and popups). Reread this post again for more details. https://github.com/ScratchAddons/ScratchAddons/issues/1653#issuecomment-784266011

**Comment by RedGuy12** [comment]
> I am saying, that this is not the API that was asked... this one modifies document.cookies (which already means that this can't be done for persistent scripts and popups). Reread this post again for more details. [#1653 (comment)](https://github.com/ScratchAddons/ScratchAddons/issues/1653#issuecomment-784266011)

you:
> this could only work by interaction with the chrome.storage API, which is exactly what we need
so store it in `chrome.storage`, which `sync` and `local` do

also you:
> We weren't planning on storing sensitive data. I cannot agree that it is a pain to mess with document.cookies.
so no `cookie mode

and also you:
> the only reason we wanted addon.storage was to store something in the extensions so it's in all devices, not just one
so no `local` mode


so you are saying I should make it always use the `sync` mode, correct?

**Comment by WorldLanguages** [comment]
@RedGuy12 Would be cool to talk on the discord server about this PR later

**Comment by RedGuy12** [comment]
> which already means that this can't be done for persistent scripts and popups

There's a `chrome.cookies` api that let's you and which I used here

**Pull request closed without merging**
