### PR TITLE
editor-comment-previews: add featured tag

### PR DESCRIPTION
**Pull request by lisa-wolfgang**
Reasons for featured tag:
1. Very useful
2. Well-made (not buggy or hacky, unlikely to break)
3. Well-tested

### CODE REVIEW

**Comment by WorldLanguages** [comment]
No :P

**Comment by lisa-wolfgang** [comment]
image
image

**Comment by RedGuy12** [comment]
I thought we were going to keep open for next release?


________________________________

**Comment by lisa-wolfgang** [comment]
@RedGuy12 That was the script snapping addon.

**Pull request closed without merging**
