### PR TITLE
New addon: Repeat sound button

### PR DESCRIPTION
**Pull request by valmontechno**
Adds a loop button in the sound editor.
[discord suggestion](https://discord.com/channels/806602307750985799/1081882894185795675)

### CODE REVIEW

**Comment by pufferfish101007** [comment]
Some bugs I've found:
- if you go into the sound editor and turn on looping before having played a sound, it will not loop no matter how many times I toggle the button - to make it loop I need to turn off looping, switvh editor tabs, go back to the sounds tab, play a sound and _then_ turn on looping
- turning on looping whilst the sound is playing doesn't work
- dynamic reenabling when not in the sounds tab leads to an error (bit doesn't crash scratch or the addon)
- sometimes it just doesn't work until a page reload, not sure why

**Comment by WorldLanguages** [comment]
> [discord suggestion](https://discord.com/channels/806602307750985799/1081882894185795675)

Note: the discord suggestion was made by you (valmontechno) on the Discord server. It was not requested by other community members.

**Comment by valmontechno** [comment]
> * if you go into the sound editor and turn on looping before having played a sound, it will not loop no matter how many times I toggle the button - to make it loop I need to turn off looping, switvh editor tabs, go back to the sounds tab, play a sound and _then_ turn on looping
> * turning on looping whilst the sound is playing doesn't work
I can't reproduce these bugs.

**Comment by WorldLanguages** [comment]
@valmontechno You should try using branches instead of deleting your fork and creating a new one.

**Pull request closed without merging**
