### PR TITLE
Settings Page Redesign

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
Todo: 
- [ ] Fix groups (some pages have none)
- [ ] Fix search (shows group titles even if no addons are in group!)
- [ ] Fix addons not showing up in enabled if just enabled (how does this work in search?)
- [ ] Add settings
- [ ] Fix popup :rofl:

### CODE REVIEW

**Comment by Samq64** [comment]
Isn't that what drafts are for?

**Comment by Secret-chest** [comment]
Pictures?

**Comment by Weredime** [comment]
> Pictures?

load it into chrome yourself. this was originally made for fun

**Comment by Secret-chest** [comment]
> > Pictures?
> 
> load it into chrome yourself. this was originally made for fun

I did.

**Comment by Secret-chest** [comment]
The hotkeys section should have a keyboard icon and be separated with a line from the others.

**Comment by GrahamSH-LLK** [comment]
> The hotkeys section should have a keyboard icon and be separated with a line from the others.

That's mostly a placeholder

**Comment by Secret-chest** [comment]
I have a suggestion: add left/right arrows to addon rows to improve discoverability, and make the cards 320px instead of 300px wide. It's just 20px but the addon cards will have much nicer and larger images. Also change the logo to the real one, and its size to 32px because it's made to be displayed at round sizes (by round I mean 2\*\**n*, 3\*2\*\**n* etc.) Also the header is too large... 56px sesms more than enough.

**Comment by Secret-chest** [comment]
We should make the cards horizontal, maybe show 2 on one row if there's space, and add the screenshots to the left.

**Comment by Secret-chest** [comment]
This hurt me to use. How on earth is a horizontally scrolling list useable?

**Comment by mxmou** [comment]
> This hurt me to use. How on earth is a horizontally scrolling list useable?

I think horizontal scrolling would only make sense if the most important/useful items were displayed first.

**Comment by Secret-chest** [comment]
> > This hurt me to use. How on earth is a horizontally scrolling list useable?
> 
> I think horizontal scrolling would only make sense if the most important/useful items were displayed first.

And if it wasn't that long.

**Comment by GrahamSH-LLK** [comment]
this is actually a pain to use. it looks great but in reality has an extremely poor user experience.

**Comment by BroJac5246** [comment]
Are you going to keep the branch for future reference or delete it?

**Pull request closed without merging**
