### PR TITLE
New addon: Create empty sprite/costume instead of opening library

### PR DESCRIPTION
**Pull request by GarboMuffin**
Adds an addon that makes the "Choose a Sprite" and "Choose a Costume" buttons create an empty sprite/costume instead of opening the library. Does not change the "Choose a Sound" button.

Has been requested a couple times:  
https://discord.com/channels/806602307750985799/806609030935740477/871487795456249877  
https://discord.com/channels/806602307750985799/806602307750985803/871533280233664522

### CODE REVIEW

**Comment by mxmou** [comment]
Could it also change the tooltips to "Paint a Sprite" and "Paint a Costume"?

**Comment by WorldLanguages** [comment]
Garbo can you explain why draft? mxmou's suggestion?

**Comment by GarboMuffin** [comment]
I think I'm going to add some options, unlike everyone thinks these are useless:

image

**Comment by WorldLanguages** [comment]
@mxmou Any suggestions for the addon name and description? I think we stopped using the term `asset`.

**Comment by mxmou** [comment]
> @mxmou Any suggestions for the addon name and description? I think we stopped using the term `asset`.

"Create asset buttons" could be just "create buttons", and "create a random asset" could be changed to "choose a random item from the library".

**Comment by WorldLanguages** [comment]
Not sure how to come up with a concise name lol

**Comment by WorldLanguages** [comment]
Okay, I assumed the most annoying button in vanilla Scratch is Choose a Costume. So I named the addon for that. This is similar to Sprite folders, which can also group costumes and sounds.
Tell me what you think.

**Pull request merged**
