### PR TITLE
remove harmful and dead exact-count features

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
### Changes

Removes studio and forum exact count features
### Reason for changes

Studio causes large amounts of load on Scratch. Forum is dead, as scratchdb is dead.

### CODE REVIEW

**Review by apple502j — APPROVED** [review]

**Comment by apple502j** [comment]
`TYPE:SCREAMING REQUEST FROM DEVELOPERS`

**Comment by WorldLanguages** [comment]
Resolves part of #7617

**Comment by WorldLanguages** [comment]
> Studio causes large amounts of load on Scratch.

Fetching an additional scratchr2 page on each profile sounds more intensive. But I just checked and we do not send cookies with that request, so we allow Scratch to return a cached version of the page.

**Comment by GrahamSH-LLK** [comment]
> Resolves part of #7617

uhh that's this PR lol

**Comment by mxmou** [comment]
> Resolves part of #7617

#6729?

**Comment by DNin01** [comment]
Might also want to say something about these features being removed. If we don't, users could think it's a bug.

**Comment by mxmou** [comment]
> Wait, why is exact count for studios being removed?

From the PR description:

> Studio causes large amounts of load on Scratch.

**Comment by DNin01** [comment]
> > Wait, why is exact count for studios being removed?
> 
> 
> 
> From the PR description:
> 
> 
> 
> > Studio causes large amounts of load on Scratch.

Oh, it was slowing the servers down?

If W_L agrees on that, that makes sense.

Perhaps there's a more efficient way to implement it…

**Comment by mxmou** [comment]
> Maybe if there's a more efficient way to implement it we could re-add it in the future.

The current version of the [exactcount website](https://mxmou.github.io/exactcount/) makes fewer requests, but I think the main issue is sending additional requests on each page load. Using the more efficient algorithm and only shown the exact count when the user clicks the "100+" would be much better than what the current version of the addon did.

**Comment by Samq64** [comment]
Studios should probably have been a separate PR since it wasn't broken.

**Comment by mxmou** [comment]
> Fetching an additional scratchr2 page on each profile sounds more intensive.

It's actually six additional scratchr2 pages: shared projects, favorited projects, curated studios, followed studios, followed users, followers.

**Comment by WorldLanguages** [comment]
> Might also want to say something about these features being removed. If we don't, users could think it's a bug.

Sorry, I was going to say that we would readd this to require a click, but I missed it due to exams. We will merge #7621 before releasing a new version.

**Comment by WorldLanguages** [comment]
About profiles, I created #7623 and let's continue the discussion there.

**Pull request merged**
