### PR TITLE
Warn users before posting "scratch addons" on forums

### LINKED ISSUE #4746: Warn users before posting "scratch addons" on forums
It's happening [quite a lot](https://ocular.jeffalo.net/search?q=%22scratch%20addons%22&sort=newest), and apparently the Scratch forums don't have a list of filtered words like comments, so the ST can't easily block it like they did with comments.

We already warn the user when about to comment "scratch addons", so we should reuse the code and do the same for posting forum topics.

### PR DESCRIPTION
**Pull request by WorldLanguages**
Resolves #4746

### Changes

Extended the "scratch addons" warning to new forum posts, new forum topics, editing existing topics and (probably, haven't tested) the signature changing screen.

image

### Tests

Appears to work in Chromium. See comment: https://github.com/ScratchAddons/ScratchAddons/pull/6232#issuecomment-1599656292

### CODE REVIEW

**Comment by Samq64** [comment]
It doesn't seem to work in Scratch blocks and on the signature page it also appears when removing Scratch Addons from it.

**Comment by WorldLanguages** [comment]
I haven't tested the signature page yet. Could you elaborate the Scratchblocks issue?

**Comment by Samq64** [comment]
> Could you elaborate the Scratchblocks issue?

I can't repro anymore. Maybe I forgot to reload the tab after switching branches.

**Comment by WorldLanguages** [comment]
> Maybe I forgot to reload the tab after switching branches.

Yeah, that's likely. This just tests a regex on `textarea.value`. Don't know how ScratchBlocks would break it, as ScratchBlocks is simply represented as text in the textarea.

**Comment by WorldLanguages** [comment]
> on the signature page it also appears when removing Scratch Addons from it.

@Samq64 Is this the exact bug you were experiencing? (after trying to set the signature with "scratch addons" on it and changing the textarea afterwards)
image

**Comment by WorldLanguages** [comment]
- [ ] Tested in signature changing page
- [ ] Tested when creating a new topic (except BaG & Japanese forums)
- [ ] Tested when creating a new topic in BaG forum
- [ ] Tested when creating a new topic in Japanese forum
- [ ] Tested when editing an existing post
- [ ] Tested "post anyway" logic
- [ ] General Firefox testing

**Comment by WorldLanguages** [comment]
> No, I included Scratch Addons in the signature and reloaded the page after submitting it, then I removed the mention and the message still appeared.

Did you have to click "post anyway for that" or did it send straight away? Make sure to switch branches, then reload the extension, then reload the page, before testing.

**Comment by Samq64** [comment]
> Did you have to click "post anyway" for that

Yes

**Comment by WorldLanguages** [comment]
Tested everything.

**Pull request merged**
