### PR TITLE
New addon: Compact block category menu

### PR DESCRIPTION
**Pull request by CST1229**
### Changes

Adds the `compact-categories` addon, which hides the labels on the block category menu.

### Reason for changes

Some people might have smaller screens, and this allows them to see more categories and also have slightly more code area space.

### Tests

Works.

`columns` compatibility is still a WIP and currently not really working.

### CODE REVIEW

**Comment by lisa-wolfgang** [comment]
My opinion is that `columns` and this addon need to be mutually exclusive, and the only way to do that is to have them as a `select` setting within the same addon.

**Comment by Samq64** [comment]
I think the Add Extension button should be a circle with the label removed and put next to the other loaded extensions when columns is enabled.

**Comment by CST1229** [comment]
> I think the Add Extension button should be a circle with the label removed and put next to the other loaded extensions when columns is enabled.

That's pretty hard to do without a userscript.

**Comment by JaydenDev** [comment]
An option for a category menu like this would be cool:
image

Source: ClipCC

**Comment by CST1229** [comment]
> An option for a category menu like this would be cool: -snip-
> 
> Source: ClipCC

Outside the scope of this addon; you know it is supposed to be compact?

**Comment by JaydenDev** [comment]
> > An option for a category menu like this would be cool: -snip-
> > Source: ClipCC
> 
> Outside the scope of this addon; you know it is supposed to be compact?

This is a very compact category menu what do you mean?

**Comment by CST1229** [comment]
> This is a very compact category menu what do you mean?

It's not compact when it's literally bigger than the vanilla category menu.

**Comment by JaydenDev** [comment]
It was just an example screenshot, it wasn't a mockup or anything.

**Comment by RedGuy12** [comment]
I vote to have this in the same addon as #4018

**Comment by mxmou** [comment]
> I vote to have this in the same addon as #4018

#4018 is for reducing empty space, not removing labels. I actually think it shouldn't remove icons from tabs either.

I agree with combining addons that modify the layout of the category menu into a single addon with a select setting.

**Comment by CST1229** [comment]
This PR has been inactive and drafted for a while, and also I'd probably start from scratch if I wanted to develop this addon further, so I'm gonna close this.

**Comment by WorldLanguages** [comment]
There wasn't an issue for this, so I created one: #5973

**Pull request closed without merging**
