### PR TITLE
Add YouTube changelog video link to update notification

### PR DESCRIPTION
**Pull request by WorldLanguages**
Also, always shows banner if the URL hash is `#sa-update-notif`, so that it's easier to do future PRs like this

image

### CODE REVIEW

**Comment by Shluffy** [comment]
how does forcing it to display work?

**Comment by apple502j** [comment]
can you tinypng it?

**Comment by WorldLanguages** [comment]
> how does forcing it to display work?

Just go to https://scratch.mit.edu/#sa-update-notif

> can you tinypng it?

I already compressed it by around 50% with https://squoosh.app

**Comment by Shluffy** [comment]
> > how does forcing it to display work?
> 
> Just go to https://scratch.mit.edu/#sa-update-notif

doesn't work...

**Pull request merged**
