### PR TITLE
Fix issues with popup restyling

### LINKED ISSUE #512: Vue warn in settings page
`v-model does not support element type: BUTTON`

### PR DESCRIPTION
**Pull request by WorldLanguages**
Resolves #512 

Would like feedback on the tab design and lower margins on the cards
image

### CODE REVIEW

**Comment by TheColaber** [comment]
I really like this design overall. Will there be an option to switch between light and dark mode?

**Comment by WorldLanguages** [comment]
@TheColaber Yes there is already, if you download the extension from here

**Comment by TheColaber** [comment]
> @TheColaber Yes there is already, if you download the extension from here

Oh nice, yeah this extension's getting good.

**Comment by Explosion-Scratch** [comment]
BRUH. Do you ever mark your messages as read? lol "816 days ago"

**Comment by Explosion-Scratch** [comment]
Nvm, that's Earth_Languages lol

**Pull request merged**
