### PR TITLE
Add addon.tab.createModal

### LINKED ISSUE #3191: addon.tab.createModal
### Is your request related to a problem? Please describe.

I see few addons making scratch-www modals (like the studio-followers one + gamepad) and they all duplicate work by creating different modals. I am also creating an issue for this as I want to create the "Secret Lives" addon but it doesn't seem like i should write more code for these modals :/
### Describe the solution you'd like

An addon api, presumably addon.tab.createModal that can create a modal for an addon
### Describe alternatives you've considered

N/A

### Additional context

```javascript
addon.tab.createModal(title: String, isScratchGui: Boolean /* For different css classes */) <Element>
```

### PR DESCRIPTION
**Pull request by mxmou**
Resolves #3191

### Changes

Adds `addon.tab.createModal`.

Currently includes a test addon. When it's enabled, running `openTestModal()` on project pages, other scratch-www pages and scratchr2 pages shows the different types of modals.

### To do

* [x] Add functions that use this API to show modals similar to <del>`alert()` and `confirm()`</del> `confirm()` and `prompt()`
* [x] Use it for existing modals
  * [x] gamepad
  * [x] mediarecorder
  * [x] studio-followers
  * [x] animated-thumb
* [x] Use it instead of <del>`alert()` and `confirm()`</del> `confirm()` and `prompt()` where that's possible
* [ ] Use it in editor-devtools (probably requires adding a slightly modified version of `_createEditorModal()` to the extension version)
* [x] Remove test addon (or keep it but make it only visible on the settings page in development versions)
* [x] Handle dark mode and 2.0 → 3.0 compatibility automatically

### CODE REVIEW

**Review by FunctionalMetatable — COMMENTED** [review]
Could you add the done button (below all of the content)?

**Comment by mxmou** [comment]
> Could you add the done button (below all of the content)?

I don't think that should be handled by the API.

**Comment by WorldLanguages** [comment]
@mxmou Can you list the addons that cannot implement this for some reason? name-backpack-items for example?

**Comment by mxmou** [comment]
> @mxmou Can you list the addons that cannot implement this for some reason? name-backpack-items for example?

* Addons that override synchronous functions
  * remove-sprite-confirm
  * name-backpack-items
* Addons that use `event.stopPropagation()` (probably possible, but refactoring would be needed)
  * confirm-actions
  * disable-auto-save
  * turbowarp-player

**Comment by WorldLanguages** [comment]
Let's hopefully merge this into v1.26.0

@mxmou Can you fix the conflicts? If not, tell me and I'll do it when I find the time.
If possible, you should also consider creating a different JS module instead of adding 400+ lines to already big Tab.js. Having it as a single module would also help us put this into editor-devtools.

**Pull request merged**
