### PR TITLE
Apply "Ctrl+Enter to post" when reporting in the forums 

### LINKED ISSUE #6262: Apply "Ctrl+Enter to post" when reporting in the forums
### Why this would be helpful

I'd like to use Ctrl+Enter when submitting things, which is the point of the addon.

### My suggestion

Also post when pressing Ctrl+Enter on report screens in the forums.

### Possible alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Chiroyce1**
Resolves #6262

### Changes

Adds an `if` check to handle the different textbox on forum post report pages under `/discuss/misc/*

### Tests

Reported a post and it seems to work, tested on Firefox, macOS (cmd+enter and ctrl+enter)

### CODE REVIEW

**Comment by WorldLanguages** [comment]
@mybearworld Are you able to test this?

**Comment by Chiroyce1** [comment]
To test without actually sending reports: add a breakpoint for XHR requests in the devtools debugger, so clicking the report button or pressing ctrl+enter will trigger it but pause it before sending the request.

**Comment by mybearworld** [comment]
> @mybearworld Are you able to test this?

Yes, it works.

**Review by WorldLanguages — APPROVED** [review]
Haven't tested myself, but everything looks alright.

**Pull request merged**
