### PR TITLE
New addon: Profile message count

### PR DESCRIPTION
**Pull request by itta611**
### Changes
This addon shows user message count on profile page.
demo

### Tests
Tested on Google Chrome 95.0.4638.69

### CODE REVIEW

**Comment by lisa-wolfgang** [comment]
Why under the follow button? Just curious.

**Comment by itta611** [comment]
Just a hunch. I think it looks cluttered when displayed on the left.

**Comment by itta611** [comment]
@WorldLanguages Any updates?

**Comment by WorldLanguages** [comment]
I'm unsure about this addon's concept. Message counts should ideally stay private, they simply aren't because of performance reasons. And I don't think this has been suggested by any users.

**Comment by WorldLanguages** [comment]
Closing, if someone is interested, create an issue and we can discuss whether we want this as an addon or not, then we can reconsider.

**Comment by TheColaber** [comment]
This is something you really shouldn't or don't need to know, if you don't own the account. I think knowing message counts for other accounts you own could be implemented in an account switching addon, which I have a pr open somewhere.

**Pull request closed without merging**
