### PR TITLE
gamepad: per-axis configuration, smart mapping generator, tools for project creators, other fixes

### LINKED ISSUE #2445: Gamepad support - add support for individual axis
**Is your feature request related to a problem? Please describe.**

This is related to two problems:
1. Some controllers have axis that don't align with the expected arrow key layout (for example, tilting up makes the axis go right)
2. The limited options obviously don't support WASD, IJKL, or other buttons

**Describe the solution you'd like**

Axis and their directions should be treated as individual inputs. For example, Axis 0+ and Axis 0- could be new options, and they could go above/below the other buttons.

**Describe alternatives you've considered**

For simplicity, this could be hidden under an "Advanced" section, or be togglable in the settings.

### PR DESCRIPTION
**Pull request by GarboMuffin**
**The important things**

 - Smart mapping generator: the addon will now analyze the project's scripts and try to generate decent mappings by default. >80% of games are now playable with an xbox controller without ever touching the gamepad settings button thanks to this
 - Project creators can override mappings: there is a setting in the gamepad config to store mappings in a script comment in the stage to override the default mappings. It results in comments like 
image
  The wording of the comment header can be changed and the advertisement can be removed. If you have another idea for where to store this information, I'd love to hear it.
 - Closes #2445 - You can now configure the key of each axis individually instead of just arrows or WASD
  https://user-images.githubusercontent.com/33787854/120527083-8dbb2280-c39f-11eb-9166-d3642c0a4e06.mp4

**Less important changes**

 - Hide gamepad config button in small stage mode
 - Hide real mouse cursor when virtual cursor is being used
 - Show a warning for browsers where the gamepad API is unsupported or broken (Linux Firefox)
 - Close settings when escape is pressed
 - Change category to "Project player" instead of "Other"
 - Better handling of multiple buttons being bound to the same key
 - Allow binding button to Enter key
 - Probably some other bug fixes, stopped tracking them at some point

### CODE REVIEW

**Comment by WorldLanguages** [comment]
Wording of the comment header looks OK to me

**Comment by WorldLanguages** [comment]
@mxmou Changes to this addon on debugger branch will probably conflict with this, right?

**Comment by RedGuy12** [comment]
I think you mean @GrahamSH-LLK
________________________________

**Comment by apple502j** [comment]
@GarboMuffin Is this ready to review? Deadline for 1.16 is coming soon

**Comment by mxmou** [comment]
> @mxmou Changes to this addon on debugger branch will probably conflict with this, right?

They will.

**Comment by WorldLanguages** [comment]
Ready to undraft? Adds new locales so should be merged before Saturday.

**Pull request merged**
