### PR TITLE
Remove unlocalized instance of "Scratch Addons"

### LINKED ISSUE #5273: manifest.json has untranslated "Scratch Addons" string hardcoded on it
I don't remember why we need a `browser_action.default_title` in the first place (won't it default to the extension name anyway?)
And if we'll keep it, we should use `__MSG_extensionName__` instead, in order to support languages where the extension is named differently.

https://github.com/ScratchAddons/ScratchAddons/blob/master/manifest.json#L14

```json
  "browser_action": {
    "default_icon": "images/icon-blue.png",
    "default_popup": "webpages/popup/index.html",
    "default_title": "Scratch Addons"
  },
```

### PR DESCRIPTION
**Pull request by RedGuy12**
Resolves #5273 

### Changes

Removed properties from manifest.json that are equal to their defaults.

### Reason for changes

Redundancy and this wasn't localized

### Tests

Tested locally, this does still display properly with the proper tooltip.

### CODE REVIEW

**Comment by apple502j** [comment]
Does this also work in Firefox? @RedGuy12

**Comment by RedGuy12** [comment]
Not able to test

**Comment by WorldLanguages** [comment]
Unrelated: CODEOWNERS file should have auto-requested a review for both apple502j and me.
Possibly a typo? https://github.com/ScratchAddons/ScratchAddons/blob/master/.github/CODEOWNERS#L7

**Comment by WorldLanguages** [comment]
No issues on Firefox 105
image

**Review by WorldLanguages — APPROVED** [review]

**Review by apple502j — APPROVED** [review]

**Pull request merged**
