### PR TITLE
scratchr2: improve My Stuff tabs

### PR DESCRIPTION
**Pull request by mxmou**
### Changes

* Implements the suggestion in https://github.com/ScratchAddons/ScratchAddons/issues/6584#issuecomment-1692206685
* That didn't look very good when the text on the tab had more than one line, so this also
  * makes it truncate instead of wrap;
  * reduces the padding, font size, and font weight to make that less likely.

image

### Reason for changes

With the previous design, it wasn't obvious that the indented tabs were subcategories.

### Tests

Tested in both browsers in different languages.

### CODE REVIEW

**Review by DNin01 — COMMENTED** [review]
To me, this design looks a bit distracting - it doesn't completely fit the theme of Scratch's UI, IMO. Maybe making it blend in with the background more would help. Also, does the color change if you have a custom `dark-www` highlight color?

**Comment by mxmou** [comment]
> To me, this design looks a bit distracting - it doesn't completely fit the theme of Scratch's UI, IMO. Maybe making it blend in with the background more would help.

Do you think this looks better?
image

> Also, does the color change if you have a custom `dark-www` highlight color?

It isn't currently affected by dark mode settings. I'll fix that.

**Review by DNin01 — APPROVED** [review]
Pretty good.

**Comment by WorldLanguages** [comment]
brave_YmIjPA0UJz

**Review by WorldLanguages — APPROVED** [review]
Looks nice!

**Comment by Secret-chest** [comment]
The dots should be thinner and the same colour as the unselected button border.

**Comment by Samq64** [comment]
> The dots should be thinner and the same colour as the unselected button border.

But the unselected button are white like the background. Are you saying the dots should only be outlines?

**Comment by mxmou** [comment]
> > The dots should be thinner and the same colour as the unselected button border.
> 
> But the unselected button are white like the background.

@Secret-chest wants the dots to be the same color as the button borders:
image

I think they look better if they're more visible.

**Comment by Secret-chest** [comment]
OR make them thinner.

**Comment by DNin01** [comment]
Yeah, I kind of feel like the dots a supplementary element and don't need to follow contrast guidelines as strictly.

I wonder what it would look like if they were more like dashes instead of thick dots, as suggested by @Secret-chest.

**Comment by DNin01** [comment]
> I think they look better if they're more visible.

It's a tough decision, isn't it? I feel kinda torn too.

**Comment by WorldLanguages** [comment]
> I think they look better if they're more visible.

I think I like the opposite, personally

**Comment by GrahamSH-LLK** [comment]
> > > The dots should be thinner and the same colour as the unselected button border.
> > 
> > 
> > But the unselected button are white like the background.
> 
> @Secret-chest wants the dots to be the same color as the button borders: image
> 
> I think they look better if they're more visible.

This looks _way_ better

**Comment by BroJac5246** [comment]
> This looks way better

"This" meaning the picture or the suggestion? I'm guessing the former?

**Comment by GrahamSH-LLK** [comment]
> > This looks way better
> 
> "This" meaning the picture or the suggestion? I'm guessing the former?

The picture

**Comment by WorldLanguages** [comment]
I think a majority would prefer this version, over the purple one in the OP (original post):

(reposting image from comment https://github.com/ScratchAddons/ScratchAddons/pull/6630#issuecomment-1713732728)

image

**Comment by Secret-chest** [comment]
Let's vote:

* :+1: for light grey dots
* :-1: for dark grey dots
* :tada: for purple dots

**Comment by DNin01** [comment]
Direct comparison:
image image image

**Comment by DNin01** [comment]
I wonder if it could change depending on the state of the buttons (like hovered, active, etc.)?

**Comment by BroJac5246** [comment]
> I wonder if it could change depending on the state of the buttons (like hovered, active, etc.)?

Interesting... but probably also overkill.

**Review by WorldLanguages — APPROVED** [review]

**Pull request merged**
