### PR TITLE
editor-stage-left: add setting to have 2.0 button order (fullscreen on left)

### PR DESCRIPTION
**Pull request by WorldLanguages**
PRing on behalf of djdolphin
Right now, refresh is needed to get disabling/enabling this setting to take effect. We might want to wait until dynamicDisable and dynamicEnable work properly so that's not the case.

Image with setting enabled, see how fullscreen icon is on the left, just like 2.0
image

### CODE REVIEW

**Comment by RedGuy12** [comment]
1. Do clone-count and mos-pos work with this?
2. hmmm...idk...i kinda like the 2.0 editor button layout but not the stage on the left...

**Comment by TheColaber** [comment]
I currently see this happening with appending addons...
image
(note: pause button is fine, addons that usually want to append in between the controls are not successful)
If we really wanted to avoid this, we should have the addons append in-between `.controls_controls-container_2xinB` and `.stage-header_stage-size-row_14N65` instead of in `.controls_controls-container_2xinB`. Except that's not very possible due to the parent being `display: flex` (not sure, I just might not be good with css)

But uh... other than that... this is good to merge.

**Comment by CST1229** [comment]
I believe you can fix the appending addons by making `controls_controls-container` row-reverse, then putting the green flag, stop sign and anything between them in a div and row-reversing that.
However, there will be issues with sharedspace appending after the control buttons, but that can probably be fixed by making the starting bound the turbo mode label instead, at the cost of moving the elements addons added there.

**Comment by DatGamerYoloYT** [comment]
Can I have access to this?

**Comment by Norbiros** [comment]
Download WL's repository. Go on this branch `WorldLanguages:editor-stage-left-button-order`. Load temp add-on.

**Comment by DatGamerYoloYT** [comment]
> Reference

how tho

**Comment by DatGamerYoloYT** [comment]
image
uh oh

**Comment by Norbiros** [comment]
> image uh oh

Git pull and merge changes? This was created about year ago

**Comment by DatGamerYoloYT** [comment]
>Git pull and merge changes?

yes.

**Comment by DatGamerYoloYT** [comment]
someone please git pull and merge changes its been 21 days

**Comment by Norbiros** [comment]
> someone please git pull and merge changes its been 21 days

I don't have permissions to do that, but I created fork of W_L's branch and merged it to newest version, and I fixed bug that TheColaber reported. https://github.com/Norbiros/ScratchAddons/tree/editor-stage-left-button-order To test it just use:
`git clone https://github.com/Norbiros/ScratchAddons` and `git switch editor-stage-left-button-order`

**Comment by WorldLanguages** [comment]
@mxmou Do you think you could open a new PR that adds this feature? So we can finally close this

**Comment by TheColaber** [comment]
https://github.com/ScratchAddons/ScratchAddons/pull/4622 fixes the bugs in this pr and is more updated.

**Pull request closed without merging**
