### PR TITLE
Chrome.*

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
Resolves #

### CODE REVIEW

**Comment by GrahamSH-LLK** [comment]
Sorry, github sucks

**Comment by WorldLanguages** [comment]
bruh

**Comment by Endermaster3690** [comment]
what da problem

**Comment by CST1229** [comment]
> 
> 
> what da problem

They wanted to PR to SA-Userscript/ScratchAddons but accidentally PR'ed to this repo instead

**Comment by GrahamSH-LLK** [comment]
> > what da problem
> 
> They wanted to PR to SA-Userscript/ScratchAddons but accidentally PR'ed to this repo instead

Github automatically set base to sa/sa, not what I thought it would

**Pull request closed without merging**
