### PR TITLE
Feature unshared projects

### PR DESCRIPTION
**Pull request by TheColaber**
**Changes**

New Addon... Adds unshared projects to be featured on your profile.

**Tests**

Works on chrome.

### CODE REVIEW

**Comment by Explosion-Scratch** [comment]
Cool!!!

**Comment by WorldLanguages** [comment]
@Explosion-Scratch A few more offtopic comments and I'm banning you from the org. To see if you've learnt, please do not reply to this message - instead, react with a thumbs up :P

**Review by WorldLanguages — APPROVED** [review]
We will try to find a better way to share strings like "load more" between addons before merging this (localization)

**Review by WorldLanguages — CHANGES_REQUESTED** [review]
Instead of adding the string `"Load more"` (which will not work very well in other languages), please use Scratch's string. This code would work: `document.querySelector("[data-control='load-more'] > span").textContent`

**Comment by TheColaber** [comment]
Fixed @WorldLanguages

**Review by WorldLanguages — APPROVED** [review]

**Pull request merged**
