### PR TITLE
Beautify settings on the "View settings file" page

### PR DESCRIPTION
**Pull request by Explosion-Scratch**
This annoys me so much

### CODE REVIEW

**Comment by Chiroyce1** [comment]
Well, it was mainly intended for being copy/pasted and not directly readable.

**Comment by RIMOPA** [comment]
> Well, it was mainly intended for being copy/pasted and not directly readable.

If it is intended for being copy/pasted we must add a copy button like this

**Comment by scratchusernamemrtbts** [comment]
uhh #1719

**Comment by WorldLanguages** [comment]
The "view settings file" feature was implemented so that users can copy the JSON. It's not intended to be readable.

**Comment by Samq64** [comment]
I agree that adding a copy button, styles, etc. is unnecessary, but i think changing one line of code to format the output is a good fine.

**Comment by WorldLanguages** [comment]
@Samq64 It makes the JSON harder to copy if the user isn't aware of the Ctrl+A hotkey.

**Pull request closed without merging**
