### PR TITLE
Setting to change forum scratchblocks colors

### LINKED ISSUE #3993: Customizable block colors: affect forum scratchblocks
There could be a setting in the editor-theme3 addon to change the colors of blocks in the forums.

### PR DESCRIPTION
**Pull request by mxmou**
Resolves #3993
image
[(Testing post)](https://scratch.mit.edu/discuss/post/5335829/)

### CODE REVIEW

**Comment by kccuber-scratch** [comment]
let me check if it works with the 3.0 forum blocks too

**Comment by kccuber-scratch** [comment]
incompatible with 3.0 forum scratchblocks addon:
image
This is my theme3 setting:
image

**Comment by WorldLanguages** [comment]
How will this play out with #3805?

**Comment by mxmou** [comment]
> How will this play out with #3805?

They're mostly independent (the only conflicting part is the `addon.json`). Unlike the actual editor blocks, styling scratchblocks with CSS isn't very difficult, so I don't think #3805 should change the way this is implemented.

**Comment by RedGuy12** [comment]
We forgot to update latestUpdate

**Pull request merged**
