### PR TITLE
OneState No RPC edition

### PR DESCRIPTION
**Pull request by wgyt**
Supercedes #2676

Same thing but without rpc and stuff

### CODE REVIEW

**Comment by WorldLanguages** [comment]
Probably won't make it to stores - if we ever provide addons that a) need to be enabled by default to be worth adding and b) need a central server, it will need to be a coordinated effort and be hosted under the scratchaddons.com domain.

**Comment by RedGuy12** [comment]
Probably it's own extention
________________________________

**Comment by wgyt** [comment]
> Probably it's own extention

@RedGuy12 yeah.... that is what I was thinking, currently working on that at the moment, but I'll keep this open for the time being

**Comment by wgyt** [comment]
Note: Working on a seperate chrome extension for OneState with RPC:
image

**Comment by RedGuy12** [comment]
is it onedotprojects/onestate-extention?
________________________________

**Comment by wgyt** [comment]
> is it onedotprojects/onestate-extention?

no, its wgyt/onestate-extention

**Comment by wgyt** [comment]
wont happen, might as well close

**Pull request closed without merging**
