### PR TITLE
clean up image uploader code

### PR DESCRIPTION
**Pull request by JeffaloBob**
**Resolves**

Resolves world languages yelling at me

**Changes**

rewrite image uploader

**Reason for changes**

see above

**Tests**

no

### CODE REVIEW

**Comment by JeffaloBob** [comment]
also i need to do the l10n things but i dont know how to

**Review by WorldLanguages — APPROVED** [review]
Fine except for the md5 library. Can you provide a link to the original (I lost it :c). We'll be trying to maintain a list of the sources for each of the libraries. If the library doesn't support JS modules you'll need to use the `window.md5` global.

**Comment by JeffaloBob** [comment]
@WorldLanguages https://github.com/emn178/js-md5

**Review by Daniel4-Scratch — APPROVED** [review]

**Comment by WorldLanguages** [comment]
Waiting for #836

**Pull request merged**
