### PR TITLE
Update the "For editor" badge color

### LINKED ISSUE #5462: Edit badge colors in settings page to have better text contrast
### Why this would be helpful

Currently, I can feel the reading troubles some people might have when looking at some of the badges (especially _For editor_) in the full screen settings page.
Current badge colors

### My suggestion

My big request is to change the _For editor_ label to be brighter with black text:
The badge colors with updated "For editor" badge
```
.badge.darkgreen {
  background: #0cd1c7;
  color: #000;
  border-color: #12a39e;
}
```
<sub>(I also sneaked in completely black text to replace the very dark gray text)

If that's not enough, we can get even higher contrast by making all the text black to make them all WCAG-compliant.
The badge colors with all badges updated
```
.badge {
  color: #000;
}

.badge.blue {
  background: #56a9ff;
  border-color: #3c88d7;
}
.badge.green {
  background: #78fd2b;
  border-color: #53b31c;
}
.badge.yellow {
  background: #fddd2b;
  border-color: #fdab12;
}
.badge.red {
  background: #ff9031;
  border-color: #cb5e00;
}
.badge.darkred {
  background: #ff7272;
  border-color: #d53b3b;
}
.badge.darkgreen {
  background: #0cd1c7;
  border-color: #12a39e;
}
.badge.purple {
  background: #ff67de;
  border-color: #e137bd;
}
```

And by also adding this:
```
.badge:hover {
    background: #FFF;
    border-color: #DDD;
}
```
...we can make hovering over the badges basically switch them to a black text on white version, helping to make the text easy to read.

### Possible alternatives

- Make the labels darker with white text.
- Add a high contrast mode and make these optional.

### Additional context

Checked with https://contrastchecker.com/

### PR DESCRIPTION
**Pull request by DNin01**
Resolves #5462

### Changes

Before:
Current badge colors

After:
The badge colors with updated "For editor" badge

### Reason for changes

The "For editor" badge text is the hardest to read due to how similar the text color is to the badge color.

### Tests

Tested.

### CODE REVIEW

**Review by Samq64 — APPROVED** [review]

**Comment by Samq64** [comment]
Why are there two badge coloue PRs open?

**Review by Samq64 — COMMENTED** [review]
Why are there two badge colouer PRs open?

**Comment by DNin01** [comment]
> Why are there two badge colouer PRs open?

So that we can choose one of two options.

**Comment by DNin01** [comment]
> > > Why are there two badge colouer PRs open?
> > 
> > 
> > So that we can choose one of two options.
> 
> We should just make the decisions and then update the original.

Probably should've done that.

**Comment by WorldLanguages** [comment]
Opening 2 different PRs is confusing.

**Review by Samq64 — APPROVED** [review]

**Review by TheColaber — APPROVED** [review]

**Comment by WorldLanguages** [comment]
@DNin01 Lol we finally merged this 😅 Sorry. Feel free to say "bump" in old PRs.

**Pull request merged**
