### PR TITLE
New API: addon.tab.appendToSharedSpace

### LINKED ISSUE #2846: addon.tab.appendToSharedSpace API
Related to #2110

Lower order means element goes before others with higher order number.

Example:

```js
// addons/gamepad/userscript.js
addon.tab.appendToSharedSpace({space: "stageHeaderSizeControls", element: gamepadButton, order: 0});

// addons/debugger/userscript.js
addon.tab.appendToSharedSpace({space: "stageHeaderSizeControls", element: debuggerButtonContainer, order: 1});
```

Would guarantee this, no matter what addon calls the function first:
image

Currently, both addons race condition on the order and it's up to luck. (and dynamicEnable makes it even less predictable)

### PR DESCRIPTION
**Pull request by WorldLanguages**
Resolves #2846

- Add API (see docs below)
- Hide debugger in small stage mode
- Support RTL margin in gamepad & debugger buttons
- mouse-pos static width to avoid clone count moving around costantly when moving cursor

Docs: https://scratchaddons.com/docs/reference/addon-api/addon.tab/addon.tab.appendtosharedspace/

### CODE REVIEW

**Comment by ErrorGamer2000** [comment]
Can you make this work with the tab area? Addons like `variable-manager` that need (or, will need since this is the only addon that currently adds a new tab) a lot of space will need to make a new tab. I say this mainly because I am planning on adding a new editor tab for my `text-editor` addon.

**Comment by WorldLanguages** [comment]
Good idea!

**Comment by ErrorGamer2000** [comment]
Thanks @WorldLanguages!

**Comment by WorldLanguages** [comment]
@mxmou What's the purpose of `.sa-gamepad-spacer`? Why not just use `margin-left: auto`? I need to know this for a potential `fullscreenStageHeader` space.

**Comment by GarboMuffin** [comment]
> What's the purpose of `.sa-gamepad-spacer`? Why not just use `margin-left: auto`? I need to know this for a potential `fullscreenStageHeader` space.

It's used to right-align a button when the fullscreen mode DOM doesn't have an easy spot to just append one. sa-gamepad-spacer was just how I decided to do that. If margin-left: auto works then you can use that instead

**Pull request merged**
