### PR TITLE
Update notification for v1.40

### PR DESCRIPTION
**Pull request by WorldLanguages**
Adds update notification. Will merge this within 48 hours.

Please help with the wording!

image

### CODE REVIEW

**Comment by WorldLanguages** [comment]
Suggestion by CST

maybe mention 3.0 scratchblocks and remove-sprite-confirm being added to vanilla? like
> "3.0 scratchblocks on forums" and "Sprite deletion confirmation" were recently added to vanilla Scratch by the Scratch Team, so those addons have been removed.

**Comment by CST1229** [comment]
> Suggestion by CST
> 
> maybe mention 3.0 scratchblocks and remove-sprite-confirm being added to vanilla? like
> 
> > "3.0 scratchblocks on forums" and "Sprite deletion confirmation" were recently added to vanilla Scratch by the Scratch Team, so those addons have been removed.

> This update fixes a few bugs and adds enhancements to existing features. Go to $1 to check them out.
> "3.0 scratchblocks on forums" and "Sprite deletion confirmation" were recently added to vanilla Scratch by the Scratch Team, so those addons have been removed.
> 
> Scratch is updating their site more frequently and we're trying our best to keep most of our features working.

**Comment by mxmou** [comment]
> (Note by WL: users probably don't know what vanilla means) 

Maybe "official version of Scratch"? It could also simply say "were recently added by the Scratch Team" (or "added to Scratch by the Scratch Team").

It don't think the link to the settings page is useful in this notification because there aren't any new settings. "Most of" in the last sentence also seems unnecessary to me.

**Comment by Samq64** [comment]
`player-thumb` is included in this release and `blocks2image` has had a significant update.

**Comment by DNin01** [comment]
I wouldn't rush major releases if I were you. If there's more to do, just cherry-pick the bug fixes and release v1.39.2.

**Comment by WorldLanguages** [comment]
Okay, I will consider it

**Comment by WorldLanguages** [comment]
@mxmou Ok I cherry-picked 12 commits into the v1.39.x branch, please confirm whether I missed anything.

**Comment by mxmou** [comment]
> @mxmou Ok I cherry-picked ~12~ 13 commits into the v1.39.x branch, please confirm whether I missed anything.
> 
> I tried to pick: changes from this week in response to Scratch updates + fix from a few weeks ago (HD Image uploads and echo button bug) + mp4 support in Chrome

The list of commits looks good. Some other bug fixes have been merged since the last release but they're all very minor issues.

**Comment by WorldLanguages** [comment]
Ok, done

No need for this update notification then

**Pull request closed without merging**
