### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by samuraininja360**
Changed Readme to create support you can add your scratch profile links

### CODE REVIEW

**Comment by ZenithRogue** [comment]
lmao, did you just try to throw your own name into the readme as a contributor unprompted? You haven't even contributed anything yet

**Comment by samuraininja360** [comment]
Um I contribute Ideas! And I am on the [Scratch Contributors](https://scratchaddons.com/contributors) page

**Comment by samuraininja360** [comment]
I am aslo designing the new website so please show some compassion towards me

**Comment by pufferfish101007** [comment]
But you and World_Languages aren't the only contributors. There are loads more. We should either include all contributors or no contributors - it would probably be best to just link to https://scratchaddons.com/contributors, as then everyone gets included and we wouldn't have to update the readme continually.

**Pull request closed without merging**
