### PR TITLE
Fix unshared projects not always getting their iframes removed in `live-forum-preview`

### LINKED ISSUE #6086: live-featured-project doesn't always hide the project on 404
### Description

You can set unshared projects as featured projects, so live-featured-project will not work. In that case, it should hide the embed - it sometimes does that, but often not.

### Steps to reproduce

1. Go to any profile with an unshared featured project (for example, https://scratch.mit.edu/users/mybearworld/)
2. Reload the page until you see Giga with a magnifying glass

### Demonstration(s) and additional context

A demonstration

### Environment

Browser: Microsoft Edge 115.0.1851.0 (Official build) dev (64-bit) 
Scratch Addons version: 1.32.1
Operating system: Windows 11

### PR DESCRIPTION
**Pull request by mybearworld**
Resolves #6086

### Changes

Change the code to remove unshared projects so that it waits until the page has actually loaded before checking if a project is unshared. This also gets rid of the fallback to alternative editors when an unshared project is present, as that no longer works, and therefore also the `forceAlternative` setting.

### Reason for changes

To fix a bug.

### Tests
Tested in Microsoft Edge 115.0.1851.0 (Official build) dev (64-bit).

### CODE REVIEW

**Comment by mybearworld** [comment]
Does this warrant migration code? The behavior of the settings does change.

**Comment by Samq64** [comment]
Does this warrant migration code? The behavior of the settings does change.

> I don't think so.

**Comment by Samq64** [comment]
Note there's another `live-featured-project` PR on the 1.33 milestone: #5423

**Comment by Hans5958** [comment]
It is a duplicate of #5423. Unless there's something new on this PR, this can be closed for now.

**Pull request closed without merging**
