### PR TITLE
fix too much padding between credits

### PR DESCRIPTION
**Pull request by RedGuy12**
it looks too ugly before this

### CODE REVIEW

**Comment by WorldLanguages** [comment]
Screenshots before and after?

**Comment by apple502j** [comment]
Before:
image

After:
image

**Comment by Hans5958** [comment]
I suppose it's need a little more, it looks quite cramped.

**Comment by RedGuy12** [comment]
@Hans5958 how it is now is just leaving it to to the browser...

**Comment by mxmou** [comment]
> @Hans5958 how it is now is just leaving it to to the browser...

Which isn't enough - there should be more than one space between each pair of items to make the more readable. About half the current padding would be better.

**Comment by lisa-wolfgang** [comment]
Personally, I think a vertical list would look nicer than just sprawling them across the screen.
It could be a left sidebar on wider displays.

**Comment by Hans5958** [comment]
Probably space considerations. Doing it vertically would waste more space.

**Comment by lisa-wolfgang** [comment]
The settings page needs a redesign at some point regardless. I don't think there's much point in scrutinizing over the old design when there are much larger issues such as addon discoverability and theme separation.

**Comment by mxmou** [comment]
The current design is better.

**Pull request closed without merging**
