### PR TITLE
Prevent users from mentioning "scratch addons" in comments

### LINKED ISSUE #2089: Make it hard for users to mention "scratch addons" in Scratch comments
**Context**
Scratch added "scratch addons" to their comment bad word filter which is fine.
A few weeks ago they started muting new scratchers that commented that.
Now, even 6 y/o accounts get a 5 minute mute for "not following the Community Guidelines".
This modal is clearly confusing and doesn't direct Scratchers to the userscript/extension policy, and fixing it is likely not considered a priority by the Scratch Team.
image

**Suggestion**
- If the user is about to post a comment that mentions "scratch addons" (case insensitive), make sure the comment is not actually sent to the Scratch servers yet.
- Use the same alert format but with our own message (making sure it's clear it's by us, related to #1880), telling users their comment was not sent (did not reach Scratch servers), linking them to the userscript/extension policy.
- That alert should have a small link/button named "send anyway" that can only be clicked after 3 seconds have happened. When clicked, we should trigger a `confirm()`. It's pretty obvious the user will get muted for 5 minutes, but we don't want to actually *prohibit* users for doing anything with their account as long as they are aware of the consequences.

### PR DESCRIPTION
**Pull request by WorldLanguages**
Resolves #2089

- [x] scratchr2 comments
- [x] scratch-www comments
- [x] scratch-messaging comments (from popup)

### CODE REVIEW

**Comment by Shluffy** [comment]
Maybe make this a setting? some users know that this is not allowed, even if the try it for whatever reason

**Comment by WorldLanguages** [comment]
@shluffy posting the comment anyway takes 2 clicks

**Comment by Shluffy** [comment]
> @Shluffy posting the comment anyway takes 2 clicks

i don;t get what you mean?

**Comment by WorldLanguages** [comment]
@Shluffy Did you test the pull request? There's a "post anyway" button

**Comment by Shluffy** [comment]
> @Shluffy Did you test the pull request? There's a "post anyway" button

I have no way of doing that, although, yes, i do know it will do that and I am still against it.

**Comment by WorldLanguages** [comment]
> I have no way of doing that, although, yes, i do know it will do that and I am still against it.

Why? 99% of cases the comment won't get posted anyway, so what's wrong with requiring 2 clicks for the comment to be posted?

**Comment by Shluffy** [comment]
> > I have no way of doing that, although, yes, i do know it will do that and I am still against it.
> 
> Why? 99% of cases the comment won't get posted anyway, so what's wrong with requiring 2 clicks for the comment to be posted?

I personally find these things annoying. Like the confirm deletion. so i just leave that off. make that a setting, and people who want to keep it on can keep it on

**Comment by Shluffy** [comment]
I just want to mention, that if you think that this is best, then do it. most people probably don't care

**Comment by WorldLanguages** [comment]
@Shluffy Yeah, if you're going to be that picky just fork the extension and use your fork hehe

**Comment by Shluffy** [comment]
> @Shluffy Yeah, if you're going to be that picky just fork the extension and use your fork hehe

I don't knwo how to do that, i'm a noob

**Comment by Shluffy** [comment]
> @Shluffy Yeah, if you're going to be that picky just fork the extension and use your fork hehe

anyway, i don't post that anyway

**Pull request merged**
