### PR TITLE
Fix reply button's position

### PR DESCRIPTION
**Pull request by wgyt735yt**
**Resolves**

This solves the issue where the reply button was incorrectly placed.

Resolves 
image

**Changes**

I changed the messaging popup to move the reply button into the span that the comment is in.

**Reason for changes**

These changes should be made because the reply button should be in the correct position.

**Tests**

I have tested this pull request in Firefox 82.0.

### CODE REVIEW

**Comment by Explosion-Scratch** [comment]
Interesting, another thing that I never thought of or noticed.

**Review by scratchusernamemrtbts — APPROVED** [review]
That's good

**Comment by wgyt735yt** [comment]
> 
> Interesting, another thing that I never thought of or noticed.

Same here, I didn't notice it until World Languages brought it up in Discord.

**Comment by WorldLanguages** [comment]
This is still not at the same state as before, there's no margin.

**Pull request closed without merging**
