### PR TITLE
sprite-properties: Fix some bugs

### PR DESCRIPTION
**Pull request by GarboMuffin**
- Fixes https://github.com/ScratchAddons/ScratchAddons/issues/5561
 - Fixes https://github.com/ScratchAddons/ScratchAddons/issues/5572 / https://discord.com/channels/751206349614088204/758464349768515604/1061135466251943946 - properties panel now works in ["wide" languages](https://github.com/LLK/scratch-gui/blob/e15b2dfa3a2e58e80fae8d1586c7f56aa0cc0ede/src/lib/locale-utils.js#L6-L18) such as Japanese and Italian
 - Fixes collapse icon being draggable
 - Fixes RTL support
 - Fixes properties panel after entering editor momentarily being hidden when auto-collapse is disabled
 - Whether the panel is collapsed or not is now preserved through leaving the editor and going back in rather than resetting to the default from settings
 - Fixes info button disappearing after renaming sprite
 - Fixes performance issue caused by running document.querySelector every time targets update (oftentimes every frame)
 - Fixes compatibility with folders addon - if the current target was in a closed folder and the folder was opened, the info button would not be added

drag-drop related changes and fix to #5557 moved to https://github.com/ScratchAddons/ScratchAddons/pull/5570

### CODE REVIEW

**Comment by Samq64** [comment]
Oops, I didn't mean to do that...

**Comment by Samq64** [comment]
The sprite properties state always resets to collapsed when changing the language which causes this when collapse by default is disabled:
[Screencast from 2023-01-08 12-43-59.webm](https://user-images.githubusercontent.com/81489795/211211823-d3a3d87c-c84c-4c82-9b93-1580545bc7ca.webm)

**Comment by GarboMuffin** [comment]
The scope of this PR has grown significantly larger than I had initially expected but I believe it is basically done now, maybe with some minor code style or comment clean up

**Review by apple502j — APPROVED** [review]

**Comment by Samq64** [comment]
I noticed that `Automatically collapse when mouse leaves sprite panel` can be enabled even if  `Collapse panel by default` isn't. Should that setting just be hidden?

**Comment by WorldLanguages** [comment]
@Samq64 I think that combination of settings is valid like any other.

**Review by Samq64 — APPROVED** [review]

**Comment by Samq64** [comment]
I meant adding an if to the collapse by default setting so this can't happen:
image

It doesn't really matter though.

**Comment by mxmou** [comment]
> I meant adding an if to the collapse by default setting so this can't happen: image
> 
> It doesn't really matter though.

I think it makes sense to try to prevent this configuration because it behaves weirdly (the properties are initially visible but moving the mouse to the sprite pane and back hides them.).

**Pull request merged**
