### PR TITLE
Updates to the messaging popup (Restyle based on ZenithRogue's version)

### PR DESCRIPTION
**Pull request by Explosion-Scratch**
This is based on @ZenithRogue's PR (#476). I restyled a lot more including the reply textbox, link effects and more.

### CODE REVIEW

**Comment by Explosion-Scratch** [comment]
@WorldLanguages what do you think?

**Comment by Explosion-Scratch** [comment]
<h1><center>Changes</center></h1>
* Made the green text a brighter white
* Restyled the reply text box
* Made the link hover effect gradual
* Made the reply button show up with a transition.
* Made the delete button change opacity on hover.

**Comment by ZenithRogue** [comment]
can you upload a screencap of what you have done?

**Comment by ZenithRogue** [comment]
Also, this pull request clearly uses my code, but bypasses all of my commits

**Comment by Explosion-Scratch** [comment]
@ZenithRogue Sure! Sorry for my late reply by the way!

**Comment by Explosion-Scratch** [comment]
Unread messages now look like this: 
image 
Instead of this:
image
The reply button fades in:
image
The delete button is visible no matter what:
image
(Old version below)
image
I restyled the reply textbox:
image
Old version:
image

**Comment by Explosion-Scratch** [comment]
No more green text:
image

Old version:
image

**Comment by YOYITsM3M8** [comment]
Good

**Comment by WorldLanguages** [comment]
Please wait until #476 is merged, then PR against master (again).
I don't think I would have accepted it either, but you should have PR'd against the PR branch, not master.

**Comment by Explosion-Scratch** [comment]
Okay!

**Pull request closed without merging**
