### PR TITLE
Better Messages Page Filter Addon!

### PR DESCRIPTION
**Pull request by TheColaber**
**Changes**

Removes terrible filter and lets you change your filter settings in the settings and it shows only messages that you have filtered. Loading More also works.

**Tests**

This needs to be tested a lot as I'm sure I messed something up...

// TODO: Update messages time
Please DO NOT merge

### CODE REVIEW

**Review by WorldLanguages — APPROVED** [review]
I guess it does its job (and it wasn't that easy to understand what exactly this addon did) but I didn't actually see the point. The message count will count messages you disable anyway. And the Scratch Messaging popup is already enough for people that like organized messages.

**Comment by TheColaber** [comment]
> I guess it does its job (and it wasn't that easy to understand what exactly this addon did) but I didn't actually see the point. The message count will count messages you disable anyway. And the Scratch Messaging popup is already enough for people that like organized messages.

Eh, I did this because I saw this: https://scratch.mit.edu/discuss/topic/56422/

**Comment by WorldLanguages** [comment]
@TheColaber Yeah, but that suggestion considers the types of messages you unselect should not count within the message count: "Then you wish there was an easy way to filter what messages you **receive** and don't."

**Comment by TheColaber** [comment]
Oh, yeah I see. There is no point. I'll close it.

**Comment by Hans5958** [comment]
That would assume that everyone that uses SA leave the messages page alone, and I disagree. In fact, I am the one that still reads uses it just because it is not fit for my purposes. So, this is not reason to close this early.

I would like this to be implemented. I think this change is going to be useful to someone (like me). Even if this PR is just something along the lines of "it's just an exact copy of the ones on Scratch Messaging," I would still like to have it on the messaging page, just like how MSU does it (although differently).

**Comment by TheColaber** [comment]
> That would assume that everyone that uses SA leave the messages page alone, and I disagree. In fact, I am the one that still reads uses it just because it is not fit for my purposes. So, this is not reason to close this early.
> 
> I would like this to be implemented. I think this change is going to be useful to someone (like me). Even if this PR is just something along the lines of "it's just an exact copy of the ones on Scratch Messaging," I would still like to have it on the messaging page, just like how MSU does it (although differently).

Hmm, ok then, I'll keep working on it then.

**Comment by Hans5958** [comment]
I think you should wait until WL give a green light. I don't want your effort is wasted.

**Comment by WorldLanguages** [comment]
Nah it's fine, at this stage we've accepted lots of addons that I'd consider useless :P
It's fine as long as the name and the addon and it's description clearly say what the addon does and 
 clarify that the message count won't be affected.

**Comment by Hans5958** [comment]
Let's be real. The term "useless" is quite subjective here. Some people might use it because it is useful.

**Comment by JeffaloBob** [comment]
> Nah it's fine, at this stage we've accepted lots of addons that I'd consider useless :P

image

**Comment by WorldLanguages** [comment]
@TheColaber We can discuss how to properly describe this addon in the Discord server, so that I can merge this.

Btw this addon glitched in one of my accounts that had so few messages that the "load more" button wasn't there.

**Comment by TheColaber** [comment]
> Btw this addon glitched in one of my accounts that had so few messages that the "load more" button wasn't there.

Yeah, I know most of the bugs and I have a better version that I haven't pushed to my branch.

**Comment by Explosion-Scratch** [comment]
As it says at the top "Please DO NOT merge" I added the 'pr- do not merge'

**Comment by RedGuy12** [comment]
why close it?

**Comment by TheColaber** [comment]
If I were to do this again, this code would be a lot neater since when I did this, I was a lot newer to JS... I think I'll close it for now and make a new PR once I do this correctly. Plus there are a lot of bugs...

**Pull request closed without merging**
