### PR TITLE
Better vm trapping

### LINKED ISSUE #4751: Fallback to Redux using internal React components
### Is your request related to a problem? Please describe.
It's annoying when you can't use redux devtools at the same time with SA.

### Describe the solution you'd like
If there is no redux, fallback to use `document.querySelector("#app")._reactRootContainer._internalRoot.current.child.stateNode.store` on scratch-www pages. And it's real redux, so probably good

### Describe alternatives you've considered
Remove Redux Devtools, but why leave problems when it's easy to fix

cc @apple502j you're the god of redux handling and stuff so

### PR DESCRIPTION
**Pull request by ErrorGamer2000**
Resolves #4751

### Changes

Replaced the function prototype hack with redux.
Also made `Trap.js` use a global cache for all addons, no need to be running the code to find the values again for each addon.

### Reason for changes

Prototype tapping is bad

### CODE REVIEW

**Review by apple502j — APPROVED** [review]

**Comment by WorldLanguages** [comment]
Since we are removing the `__scratchAddonsTraps` global, could we add a different way to access the VM, blockly and Paper through the console? That's usually useful.
I think `window.scratchAddons.vm`, `window.scratchAddons.blockly` and `window.scratchAddons.paper` would be OK.

**Comment by ErrorGamer2000** [comment]
@WorldLanguages I'll get on that. I'll probably use `window.scratchAddons.traps` though.

**Comment by mxmou** [comment]
`scratchAddons.eventTargets.tab[0]` can be used to access the `addon.tab` API from the console. I think that's good enough.

**Comment by ErrorGamer2000** [comment]
Huh, good point. I think WL's suggestion is probably a better option for devs

**Comment by WorldLanguages** [comment]
> `scratchAddons.eventTargets.tab[0]` can be used to access the `addon.tab` API from the console. I think that's good enough.

That's an interesting protip :P

**Review by TheColaber — APPROVED** [review]

**Pull request merged**
