### PR TITLE
Change minimum supported Firefox version, remove unused code

### LINKED ISSUE #4334: Change minimum Firefox required version to 86 (previously 74)
Current minimum FF version is 74 (March 2020).
Unlike chromebook users, an outstanding majority of Firefox users can get the latest version of it easily. So I suggest changing the minimum to Firefox 86 (February 2021).

- `tabs` permission not required when host permissions are already present. We can now remove many `typeof browser` checks in core code ([Firefox 86+](https://blog.mozilla.org/addons/2021/02/09/extensions-in-firefox-86/))
- CSS `min()`, `max()` and `clamp()` can now be used (Firefox 75+)
- `Intl.DateTimeFormat` dateStyle and timeStyle parameter support, already in use by some addons (Firefox 79+)
- `<link rel="preload">` support: already in use by our settings page to load faster (Firefox 85+)

### PR DESCRIPTION
**Pull request by WorldLanguages**
Resolves #4334 

Firefox 86 gives us access to the URL of tabs we already have a host permission for, so we can avoid sending messages to all tabs in Firefox, and instead do the same thing we've always done in Chrome, which is only messaging scratch.mit.edu tabs.

### CODE REVIEW

**Comment by Samq64** [comment]
> this ff version will literally be 10 days old when we release the next sa version...pls wait until 1.26.0 for this

He said 86. 87 is the newest version.

**Review by apple502j — APPROVED** [review]
LGTM, we could remove other code that queries url using messages (I think we have a couple) but this change looks fine.

**Comment by WorldLanguages** [comment]
> we could remove other code that queries url using messages

Which ones are you referring to? I only found `getLocationHref` which is only used once. `getInitialUrl` gets the **initial** URL of the tab so it cannot be replaced by chrome.tabs API.

**Comment by apple502j** [comment]
@WorldLanguages Hm, think it's the only one. (Also we need to rework cloud-games, yeah)

**Pull request merged**
