### PR TITLE
New addon - Small Editor Enhancements

### LINKED ISSUE #4231: Bring sprite to front
### Is your request related to a problem? Please describe.

When there are many sprites on the Stage, some sprite can be covered by other sprites. 

### Describe the solution you'd like

Bring a sprite to front by shift-clicking its thumbnail in the sprite area (as it was in Scratch 1.4)

### Describe alternatives you've considered

Go to lookup category and click the go to front layer block

### Additional context

This is useful when the users have not yet learned that sprites can be programmatically moved from layer to layer.

### PR DESCRIPTION
**Pull request by Norbiros**
Resolves #4231,  #1453, part of  #4122 (in future, this function may be moved to new addon...), #4199 , #4249 

### About
I created this addon, because we have a lot of issues - that are to small for addons. In this addon we can have small features, and "beta" features (for example #4122 it adds one function from that)...

### To Do
- [ ] Make "hide button" works when "scene on right side" addon is enabled
- [ ] Save data about mouse position when clicking. (When you click mouse, it changes position for short time)
- [ ] Make not showing scroll bar while moving code! (Simple "`overflow: hidden`" or create more complex way)

### CODE REVIEW

**Comment by mxmou** [comment]
I don't think these features are related enough to be part of the same addon.

**Comment by Norbiros** [comment]
This is why I made this addon.
These are great features, but they are too small so therefore they were forgotten. We can split this addon into 5, but, do we want addon that adds only one css file with 3 lines of code? 

IMAO, I think the only thing you can get rid of is "mouse blocking" and put that and other features into a separate add-on (which will also include mouse-pos)...

**Comment by mxmou** [comment]
> do we want addon that adds only one css file with 3 lines of code?

If those 3 lines add a useful feature, yes.

**Comment by Norbiros** [comment]
> > do we want addon that adds only one css file with 3 lines of code?
> 
> If those 3 lines add a useful feature, yes.

... Okay, so I need to split it to: "remove sprite wooble", "hide backpack", "bring sprite to front", make new addon "inputs" and "develop better mouse loc functions, and add it to mouse addon"?

**Comment by Mbrick2** [comment]
Maybe put all bugfixes in an addon called BUGFIXES with multi select options. But again it would need migration from other bugfix addons

**Comment by Norbiros** [comment]
Okay, but in this addon I fix only one bug... It is great idea, but I think it don't help me with this situation.

**Comment by mxmou** [comment]
> Maybe put all bugfixes in an addon called BUGFIXES with multi select options. But again it would need migration from other bugfix addons

Related: #2562

Combining fixes for unrelated things is still an issue because addons are categorized.

**Comment by Samq64** [comment]
Doesn't disable sprite wobble already exist?

**Comment by apple502j** [comment]
Nope

**Comment by CST1229** [comment]
> Nope

with no reason?

**Comment by Norbiros** [comment]
I love how Apple is closing my PRs!
I put some time on this, I understand that putting all things inside one addon is problem, okay, but closing it, when we are in middle of discussion about "What do with this?"... What can I say more, I just feel bad that just my job was shut down with the reason "Nope".

**Comment by WorldLanguages** [comment]
This PR should be split into smaller PRs.

**Comment by sfederici** [comment]
> I love how Apple is closing my PRs! I put some time on this, I understand that putting all things inside one addon is problem, okay, but closing it, when we are in middle of discussion about "What do with this?"... What can I say more, I just feel bad that just my job was shut down with the reason "Nope".

Why don't you split this addon in several addons? If you don't have enough time, let me know, so I can present your addons on your behalf.

**Comment by Norbiros** [comment]
> > I love how Apple is closing my PRs! I put some time on this, I understand that putting all things inside one addon is problem, okay, but closing it, when we are in middle of discussion about "What do with this?"... What can I say more, I just feel bad that just my job was shut down with the reason "Nope".
> 
> Why don't you split this addon in several addons? If you don't have enough time, let me know, so I can present your addons on your behalf.

I am not working on Scratch Addons so you can split it. There is list of "addons" in this PR:

- **Hide Backpack**
    We already have PR for that
- **Move sprite to front layer**
     I also like this idea
- **Disable sprite wobble**
- **Lock mouse position**
      We can add it to #4122 addon.
- **Take photo of scene**
      We should add feature to screenshot variables etc.
- **Remove navbar of scene**
- **Create button that allows to hide scene**
      We already have this
- **Show pretty input for changing size**
      I really love this idea

**Comment by sfederici** [comment]
> * **Take photo of scene**
> * **Create button that allows to hide scene**

What are they for?

**Comment by CST1229** [comment]
> > * **Take photo of scene**
> > * **Create button that allows to hide scene**
> 
> What are they for?

I assume they mean the stage by "scene" - "Create button that allows to hide scene" is [Hide stage and sprite pane](https://scratch.mit.edu/scratch-addons-extension/settings#addon-hide-stage), and "Take photo of scene" is probably a button to save a screenshot of the stage.

**Comment by sfederici** [comment]
> I assume they mean the stage by "scene" - "Create button that allows to hide scene" is [Hide stage and sprite pane](https://scratch.mit.edu/scratch-addons-extension/settings#addon-hide-stage), and "Take photo of scene" is probably a button to save a screenshot of the stage.

I see. Thanks

**Comment by wolfiwaifu** [comment]
image
NOOBS

**Pull request closed without merging**
