### PR TITLE
Turbowarp player: new options

### LINKED ISSUE #4005: Turbowarp Parameters
### Is your request related to a problem? Please describe.

There is no settings for ```turbowarp-player```

### Describe the solution you'd like

an input that you can put your parameters in + presets

### Describe alternatives you've considered 

Live with it. Nah

### Additional context
 
I think I could PR this

### PR DESCRIPTION
**Pull request by OregSamSas**
Resolves #4005  
+((very partially: #1439))

### Changes

I've added new features to the TurboWarp player addon. 
Now it's possible to add automatically URL parameters, declared in the settings. (You can view in this way a project with HQ Pen on a scratch page, in the TurboWarp player frame.) 
It's also possible to use a setting "Always choose", which lets you decide on every page whether you want to open the TW link in a new tab or just replace the player. 
I also wanted to merge these changes manually with lisa-wolfgang's changes, which would allow you to enable a setting that automatically replaces the player or open it in a new tab (I don't think the second is a good idea, so I didn't support it, I think instantly replacing is a fine setting, but there's no need of doing the same with opening in a new tab. Also, for me Chrome blocked the pop-ups at first.) 

So as you can see, it's not totally done (just mostly done, because it works, just needs to be tested), hence I open it as a draft, and hence I have a to do list too. Manual testers (actually any type of them) are welcome.

### TO DO list

- [x] add URL parameters support for the code
- [x] add a table to settings for managing the URL parameters
- [x] add an option that opens the player in a new tab on Ctrl+click, and replace the player on a simple click
- [x] insert the "Always choose" into Settings
- [x] add info alerts to the settings page
- [x] make auto-replace work
- [x] fix issues with URL parameters
- [ ] **Tests**, tests, and tests
- [x] ask people about "should I add the **automatically open in new tab** feature?"
- [ ] make people answer to this question
- [ ] if most people say yes, then make it
- [ ] do the same with the Open in new **window** feature

### Reason for changes

Because a lot of people requested it. I don't want to give more details by myself, see this (closed) issue for further information: #4766, but if you have any questions about the reasons or any other thing, feel free to ask me at any time (I am going to be on a small vacation soon, so I might won't be able to answer all the questions, sorry.)

### Tests

I tested on Chrome so far, because I use it for extension changes, because of Firefox/Waterfox temporary addons. (I have the source code downloaded on my CP, and I simply loaded it up.)

### CODE REVIEW

**Comment by OregSamSas** [comment]
> I also wanted to merge these changes manually with lisa-wolfgang's changes

I don't know if it's legal though...

**Comment by OregSamSas** [comment]
Oh, and:

> - [ ] ask people about "should I add the automatically open in new tab feature?"

What do you all think about it: should I add the automatically open in new tab feature?

**Comment by OregSamSas** [comment]
> You probably shouldn't add the auto replace player option in this PR. lisa-wolfgang's changes will probably be merged first and then you'll probably have to fix some merge conflicts.

Actually this is why I added them, to avoid merge conflicts, because I had a look on lisa-wolfgang's changes, and they wouldn't work with mine

**Comment by OregSamSas** [comment]
> Also, you can fix the prettier error by enabling actions here: https://github.com/OregSamSas/ScratchAddons/settings/actions

Which option should I opt there?

**Comment by OregSamSas** [comment]
Because it's set to the first:
image

**Comment by Samq64** [comment]
It should work then.

**Comment by OregSamSas** [comment]
> It should work then [...]

But it doesn't...

**Comment by OregSamSas** [comment]
image

BUT WHY?? I don't understand it :(

**Comment by WorldLanguages** [comment]
Self reminder: there's another open PR, #3985 

@OregSamSas Don't worry about the Prettier action!

**Comment by lisa-wolfgang** [comment]
For simplicity's sake, I think it's best to remove the player mode option and keep the behavior of the "both" mode.

**Comment by lisa-wolfgang** [comment]
Thinking about this more in light of https://github.com/ScratchAddons/ScratchAddons/pull/5214.
The current method to set URL params with this PR isn't ideal for most users. The addon could be easily rescripted to take boolean toggles as inputs and convert those to the URL params. In addition, since Garbo's PR will likely be merged before this one, the URL param settings will only be useful as a "default" configuration; thus, they should be named as such, similar to the onion skinning addon's settings.

**Comment by WorldLanguages** [comment]
> since Garbo's PR will likely be merged before this one

it was

**Comment by lisa-wolfgang** [comment]
Are there any concerns with an option to automatically replace the Scratch player with the TurboWarp player? The only one I could think of would be that the user would forget that TurboWarp is being loaded, but given the distinct red color of the "loading project" screen, I don't think this is very likely.

**Comment by WorldLanguages** [comment]
> Are there any concerns with an option to automatically replace the Scratch player with the TurboWarp player? 

We've been pretty conservative around turbowarp-player features.
I think you could say that the user might only notice they've been using the TurboWarp player until they want to "see inside" for some reason. Imagine you want to see inside to debug something and you find out you can't! We can't be blamed if the user has to click the TurboWarp button every time.

**Comment by lisa-wolfgang** [comment]
We could fix this by making it more obvious that TurboWarp is enabled. For example, we could add a popup over the stage that says "You are using the TurboWarp player."

**Comment by OregSamSas** [comment]
> We could fix this by making it more obvious that TurboWarp is enabled. For example, we could add a popup over the stage that says "You are using the TurboWarp player."

Or perhaps, if an informing text would be included in turbowarp iframes on loading (e.g. logo and name above the loading blocks), that would already made it clear it's TurboWarp and nothing else (except if the loading time is too short and the user couldn't notice the text). 
I see it's not SA related anymore then, it's something that TW can implement, and not sure if it's possible at all.
For me I think it would be annoying if a notice was permanently above the stage, but I understand that's not a problem if the pop up can be "killed" with an OK or an X button.

Mock-up image:
image
 I'm sorry it didn't look the best, but I hope it explains my idea

**Comment by TheColaber** [comment]
closing unless @OregSamSas wants to continue to work on this.

**Comment by OregSamSas** [comment]
> closing unless @OregSamSas wants to continue to work on this.

Not planning to do so as far,

**Pull request closed without merging**
