### PR TITLE
Search Profile Addon: Don't go to user if they don't exist

### LINKED ISSUE #468: Only show link to user profile if user exists
**Is your feature request related to a problem? Please describe.**

When using the user search addon, the profile tab still gets added even if the user doesn't exist. This could be confusing when it goes to a 404 page.

**Describe the solution you'd like**

Fetch the user page, if it doesn't have a `200` status code then don't add the tab.

**Describe alternatives you've considered**

Rather than not adding the tab, we could just disable it or add a message when it's clicked saying that this user doesn't exist or something.

**Additional context**

I won't make a pr yet, as I don't know whether we want this or not, or want to do an alternative, but you can see the changes at https://github.com/pufferfish101007/ScratchAddons/blob/user-search-enhancement/addons/search-profile/userscript.js

### PR DESCRIPTION
**Pull request by TheColaber**
**Resolves**

Resolves #468

**Changes**

fetches the user's profile. If it doesn't exist, our tab will turn red and there will be a tooltip saying the user doesn't exist and the link to the user will not be added to the element

**Reason for changes**

So users know.

**Tests**

I do use a CSS filter that turns the image red so I am not 100% if this effects things on other browsers but this does work on chrome.

### CODE REVIEW

**Comment by MasimbaTheHuman** [comment]
I use chrome, so I could test it.

**Comment by YOYITsM3M8** [comment]
I could test too

**Comment by YOYITsM3M8** [comment]
> I could test too

Confirmed: Profile tab turns red when the user is not found
Feedback: Add credit in the `addon.json`

**Comment by TheColaber** [comment]
Ok, btw who else worked on this addon, right now there are no credits.

**Comment by YOYITsM3M8** [comment]
> Ok, btw who else worked on this addon, right now there are no credits.

idk but also is this supposed to happen? 
image at first i thought i had another version of SA with user search on but i dont :C

**Comment by TheColaber** [comment]
> > Ok, btw who else worked on this addon, right now there are no credits.
> 
> idk but also is this supposed to happen?
> image at first i thought i had another version of SA with user search on but i dont :C

There is no way that could have happened

**Comment by YOYITsM3M8** [comment]
found the original pr: #405

**Comment by TheColaber** [comment]
> > > I could test too
> > 
> > 
> > @TheColaber
> > Confirmed: Profile tab turns red when the user is not found
> > Feedback: Add credit in the `addon.json`
> 
> Actually, could you send me the addon?

Hmm?

**Comment by YOYITsM3M8** [comment]
> > > I could test too
> > 
> > 
> > @TheColaber
> > Confirmed: Profile tab turns red when the user is not found
> > Feedback: Add credit in the `addon.json`
> 
> Actually, could you send me the addon?

https://github.com/TheColaber/ScratchAddons/tree/user-exists

**Comment by pufferfish101007** [comment]
The reason no pr was ever made for this was because scratchr2's response times are really slow and we want to keep everything as lag-free as possible - see https://github.com/ScratchAddons/ScratchAddons/issues/468#issuecomment-706721646.
And while we're adding credits, I fixed a bug. (#466)

**Comment by TheColaber** [comment]
I am using the scratch website and it's pretty fast...

**Comment by GrahamSH-LLK** [comment]
> I am using the scratch website, not scratchr2 and it's pretty fast...

Scratch Website = Scratchr2

**Comment by TheColaber** [comment]
> > I am using the scratch website, not scratchr2 and it's pretty fast...
> 
> Scratch Website = Scratchr2

Ok but is it really that slow? I mean, it's only one call.

**Comment by mxmou** [comment]
> Ok but is it really that slow? I mean, it's only one call.

Compared to api.scratch.mit.edu or ScratchDB, it's slow. But if this doesn't cause a delay before the tab appears, it's OK.

**Comment by MasimbaTheHuman** [comment]
> > > > I could test too
> > > 
> > > 
> > > @TheColaber
> > > Confirmed: Profile tab turns red when the user is not found
> > > Feedback: Add credit in the `addon.json`
> > 
> > 
> > Actually, could you send me the addon?
> 
> Hmm?

Nvm it doesn't work for me

**Review by WorldLanguages — CHANGES_REQUESTED** [review]
I don't think this is a good idea. Fetching a scratchr2 page can take seconds sometimes. I'd rather see someone add a regex check to see if the searched string could potentially be a username.

**Comment by TheColaber** [comment]
> I don't think this is a good idea. Fetching a scratchr2 page can take seconds sometimes. I'd rather see someone add a regex check to see if the searched string could potentially be a username.

Where did you want to fetch from?

**Comment by WorldLanguages** [comment]
> Where did you want to fetch from?

I'd like to fetch the API, but there's no way to fetch the API that will with 100% certainty tell you a user won't 404. Only way is fetching old and slow scratchr2. So I'd rather not fetch. I'd like to see the "user" button not appear if the search is an invalid username, for example if it includes spaces.

**Comment by wgyt735yt** [comment]
> > Where did you want to fetch from?
> 
> I'd like to fetch the API, but there's no way to fetch the API that will with 100% certainty tell you a user won't 404. Only way is fetching old and slow scratchr2. So I'd rather not fetch. I'd like to see the "user" button not appear if the search is an invalid username, for example if it includes spaces.

Ok, here's my take:
The api: can fetch data about banned users (wouldn't work)
Fetching scratchr2: too slow

>I'd like to see the "user" button not appear if the search is an invalid username, for example if it includes spaces.

Fair point

**Comment by TheColaber** [comment]
> > Where did you want to fetch from?
> 
> I'd like to fetch the API, but there's no way to fetch the API that will with 100% certainty tell you a user won't 404. Only way is fetching old and slow scratchr2. So I'd rather not fetch. I'd like to see the "user" button not appear if the search is an invalid username, for example if it includes spaces.

Alright.

**Comment by WorldLanguages** [comment]
I'm closing this PR, please open another one if you want to add a regex check

**Pull request closed without merging**
