### PR TITLE
Gradient bar/nav bar.

### PR DESCRIPTION
**Pull request by fin-github**
Resolves #
N/A

### Changes

At the top it changes it from boring-blue to a blue-to-purple gradient.

### Reason for changes

Because, at the top it is boring. With this, it gives it a new neat touch.

### Tests

Enable it, look at the nav bar.

### ~~WIP~~
~~I am currently making old.css work. main.css works fine.~~

image

### CODE REVIEW

**Review by DNin01 — CHANGES_REQUESTED** [review]
Be aware that this will conflict with Editor dark mode and customizable colors, I'm pretty sure.

**Comment by WorldLanguages** [comment]
Note that I've talked with the PR author on Discord and they're creating addons mostly for learning purposes (web technologies and git) as well as personal use.

**Comment by Secret-chest** [comment]
This shouldn't be an addon, having no settings is bad.

**Comment by WorldLanguages** [comment]
I'm closing this for now.

**Comment by fin-github** [comment]
> This shouldn't be an addon, having no settings is bad.

i am still working on the settings part

**Comment by fin-github** [comment]
> Be aware that this will conflict with Editor dark mode and customizable colors, I'm pretty sure. It also has a setting that allows changing the navigation bar color, so we would have to find a way to consider that or maybe not have this proposed addon at all.

I have known that beforehand, 2 reasons why I proceeded:



1. This is a gradient not a solid color
2. This is just light. If you dont want to use editor dark mode then you can use this

**Comment by BroJac5246** [comment]
If something like this is added then I think it should be of either `discuss-button` or website dark theme/customizable colors.

**Comment by Secret-chest** [comment]
> If something like this is added then I think it should be of either `discuss-button` or website dark theme/customizable colors.

Probably `dark-www` since `discuss-button` is getting too many unrelated features.

**Comment by DNin01** [comment]
I would be interested to see what this turns into.

**Comment by Samq64** [comment]
Let's move the discussion to #6022.

**Pull request closed without merging**
