### PR TITLE
Update gitignore to include DS_Store

### LINKED ISSUE #5045: Add `.DS_Store` to gitignore
https://scratch.mit.edu/users/World_Languages/#comments-221456612
I am suggesting to add `.DS_Store` to the gitignore file. Maybe even add more things to the gitignore if necessary.
https://en.wikipedia.org/wiki/.DS_Store

This file is automatically generated by the Finder application on macOS computers. These files can sometimes come in git repositories when Mac users contribute. They are probably unnecessary for SA and also the Finder application doesn't even show these files, even when the option to show hidden files is on. The only way to see it is to use a different application like VS Code or `git status`. According to Wikipedia those files are also frequently changed so it would add more things to the commit log.

Do you think mac users should just add it to the global gitignore file on their device instead? Or do you think some people who are new to git would benefit from it being in the SA gitignore file?

### PR DESCRIPTION
**Pull request by webdev03**
Resolves #5045

### Reason for changes
Discussed in #5045

### Tests

It should work if git is working

### CODE REVIEW

**Review by Chiroyce1 — APPROVED** [review]

**Comment by apple502j** [comment]
Will make a new PR with more files myself

**Comment by Norbiros** [comment]
Maybe you can add `.idea` too?

**Comment by WorldLanguages** [comment]
> Will make a new PR with more files myself

Was the PR created already did I miss it? Or is it still pending?

**Comment by Hans5958** [comment]
For the note: Superseeded with #5096.

**Pull request closed without merging**
