### PR TITLE
Use higher-contrast colors on settings page

### LINKED ISSUE #6027: Change the accent color of Scratch Addons
### The problem

Currently, Scratch Addons' accent color is `#ff7b26`, under the CSS variable ["--brand-orange"](https://github.com/ScratchAddons/ScratchAddons/blob/3b4fcf6d1003fd78a5902f652b928696cc5ba915/webpages/styles/colors.css#L2). However, there are a number of places where this isn't ideal. Here are some examples in light mode following the WCAG:

| Colors | Contrast Ratio | AA requirement | AAA requirement |
|--------|--------|--------|--------|
| Scratch Addons logo and name on brand orange | 2.59 | 3 | 4.5 |
| Small white text on brand orange | 2.59 | 4.5 | 7 |
| Switches set to on and selected single-select settings on content background | 2.42 | 3 | 4.5 |

There are probably some other locations where this is a problem, too. That's why I'm bringing up the suggestion to change the accent color, as big a change as it may sound.

I'd like to hear your thoughts and ideas. We should work together to find a better color to use as Scratch starts to do the same thing. I suggest making this change non-optional and balancing accessibility and design. We can measure how acceptable this change will be long-term by putting ourselves in the shoes of someone who has just started to use Scratch Addons after this change - they will not have to get used to the change.

I originally suggested considering this change in a [discussion](https://github.com/ScratchAddons/ScratchAddons/discussions/5916), but I think an issue will be seen by more contributors.

### PR DESCRIPTION
**Pull request by DNin01**
A step towards #5616

### Changes

This round of changes significantly increases the contrast between the background and the foreground elements and text.

### Reason for changes

Text and content should be more accessible.

### Tests

Tested on Edge 113. RTL layout considered and tested as needed.

### CODE REVIEW

**Comment by apple502j** [comment]
See https://github.com/ScratchAddons/ScratchAddons/issues/6027#issuecomment-1543277034, blocking merge for now.

**Comment by Secret-chest** [comment]
No discussion, nothing? You know solid colours exist? Don't make SA look like that Romanian shopping website!

**Comment by DNin01** [comment]
Also, note that there is a green-to-blue gradient brand color for non-prereleases. You can see it by commenting out the code that switches the brand color to the prerelease variant.

**Comment by DNin01** [comment]
Should we save the brand color change for a different PR and merge the rest of the changes?

**Comment by WorldLanguages** [comment]
> Should we save the brand color change for a different PR and merge the rest of the changes?

Sure, move the brand color change to another PR so that this one won't be blocked by that

**Comment by apple502j** [comment]
Would like a screenshot of the changes.

**Comment by DNin01** [comment]
> Would like a screenshot of the changes.

The on/off switches and a lot of the orange things have been redone (these are blue even when developer mode is off):
Image 1
Image 2
Image 3

Various other toggleable buttons like the tabs on the popup have the same change but use the brand color. The popup features also have some changes:
Image 4

**Comment by Secret-chest** [comment]
If I were you, I'd try a mint green

**Comment by DNin01** [comment]
@WorldLanguages @apple502j Are we still working on this?

**Comment by WorldLanguages** [comment]
We can probably try to merge this for v1.34.0 I think

**Comment by DNin01** [comment]
Someone told me about https://www.myndex.com/APCA/, a newer and probably more accurate contrast calculator. WCAG isn't perfect in every way, so I might change some things in this PR to follow these guidelines instead. What do you think about that?

**Comment by DNin01** [comment]
I'm going to close this PR in favor of other, more specific PRs I will make in the future, one of which I have [just opened](https://github.com/ScratchAddons/ScratchAddons/pull/6240). I feel like the some of the changes in this PR need a reconsideration.

**Pull request closed without merging**
