### PR TITLE
Show error message if an addon.json is invalid

### LINKED ISSUE #4947: Better error messages
### Is your request related to a problem? Please describe.

If there is an syntax error, for example, a missing comma in the `addon.json`, the popup and settings pages don't load and it only lets the user know in the background page console.

### Describe the solution you'd like

Throw better error messages and maybe display something in the popup too.

### Describe alternatives you've considered

Skip addons with invalid manifests.

### PR DESCRIPTION
**Pull request by Weredime**
Resolves #4947

### Changes
Stops crashing the manifest loader if an addon manifest is invalid, and error in background page

### Tests
Firefox

### CODE REVIEW

**Comment by apple502j** [comment]
I believe addon.json being invalid should crash. Crash handling is bad, I can say, but it is still a crash and no proper recovery is expected.

**Comment by BroJac5246** [comment]
This works on Chrome 103. However, it presents a problem:
You have to manually check for errors.

With the method SA uses, the addons not loading is the error report in itself. It's annoying, but much faster than your implementation.
What I would _personally_ prefer is if the settings & settings popup showed an error message, either as an HTML element, or with `alert()` to let the user (who, in such a case will also be a developer), know that the addon being loaded had an error in the manifest, and will be skipped.

Example:
`alert("Addon \"" + addonId + "\" has an error in its manifest, this addon will not be loaded.");`

**Comment by WorldLanguages** [comment]
IMO it should throw and run
```chrome.tabs.create(`data:text/plain,Scratch Addons crashed: invalid addon.json for addon with id ${addonId}`)```

**Comment by BroJac5246** [comment]
> IMO it should throw and run
> ```chrome.tabs.create(`data:text/plain,Scratch Addons crashed: invalid addon.json for addon with id ${addonId}`)```

That would work too.

**Comment by RedGuy12** [comment]
I think it should catch the manifest error then rethrow with the addon id added to the message

**Review by TheColaber — APPROVED** [review]

**Comment by TheColaber** [comment]
Actually, the tab didn't open when I tested it in Firefox. @WorldLanguages Know why?

**Review by apple502j — CHANGES_REQUESTED** [review]
Blocking, will investigate Firefox

**Review by apple502j — APPROVED** [review]
It's fine to make this Chrome-only, I suppose. Firefox is for the devs. (MDN cites "security reasons").

**Pull request merged**
