### PR TITLE
Fix matches for image-uploader 

### LINKED ISSUE #1605: image-uploader should only run on topics
Error Found - When at https://scratch.mit.edu/discuss/ from image-uploader addon
image

### PR DESCRIPTION
**Pull request by TheColaber**
Resolves #1605

### CODE REVIEW

**Comment by pufferfish101007** [comment]
What about creating a,new topic, or editing? This should also include https://scratch.mit.edu/discuss/post/*/edit and  https://scratch.mit.edu/discuss/*/new (I think it's that for new topics)

**Comment by jeffalo** [comment]
better solution would be to check if all of the right elements are there in the userscript. that way you dont need to worry about all of the url matches and it will work on every forum page

**Comment by WorldLanguages** [comment]
> better solution would be to check if all of the right elements are there in the userscript. that way you dont need to worry about all of the url matches and it will work on every forum page

"better", kinda, but good enough

**Comment by TheColaber** [comment]
Note to you @WorldLanguages I did change it already and I think jeffalo confirms.

**Review by WorldLanguages — APPROVED** [review]
Well, this is fine but it's also fine if it throws an error. Many addons already do this if a project is a 404 and in so many other situations.

**Comment by TheColaber** [comment]
> Well, this is fine but it's also fine if it throws an error. Many addons already do this if a project is a 404 and in so many other situations.

We already have soooooooo many errors in the console... might as well reduce them.

**Pull request merged**
