### PR TITLE
addon.json changes

### LINKED ISSUE #159: [Question] Can you make the scripts run faster and earlier?
The addon is completely awesome, no question. But a little thing that annoys me is that the discuss button only loads after a second. Same thing goes for my forkphorus button. Is it possible to make that faster?

### LINKED ISSUE #160: [Question] Should you add your name to the description?
Currently, only the deleted comments thing includes "by abc" (in this case @JeffaloBob) in the description, so I wonder if you should always add that, if we should add a "creator" tag in the JSON that would be placed next to the name of the addon or just let it be.

### PR DESCRIPTION
**Pull request by apple502j**
**Resolves**
Resolves #160 
Resolves #159 

**Changes**
addon.json can now have these fields:
- `userscripts` section can now have `runAtComplete` (bool, defaults to true) - if true, scripts run at onload (like it did before), and if false, at DOMContentLoaded. Userstyles load at DOMContentLoaded.
- `credits` is an array of `{"name": "string", "link": "link URL (optional)"}`
- `libraries` is an array of library name, e.g. `["md5", "text-field-edit"]`
**Reason for changes**
Because it's nice

### CODE REVIEW

**Comment by JeffaloBob** [comment]
>   **Reason for changes**
>   Because it's nice
agreed

**Review by Hans5958 — COMMENTED** [review]
Don't forget to handle external libraries for #176, probably?

**Comment by NoobTracker** [comment]
Ah, thank you a lot! That faster loading is cool! I already thought about making that somehow. Yeah, that also nicely keeps old things compatible.

**Comment by NoobTracker** [comment]
So, why isn't that already merged?

**Comment by NoobTracker** [comment]
Okay, little question: How do the credits look like?

**Comment by apple502j** [comment]
Credits are just `Credits to: A, B, C`

**Comment by NoobTracker** [comment]
Ah, okay. It would be really nice if you could make a screenshot.

**Pull request merged**
