### PR TITLE
Create Removed_2.0_Blocks

### PR DESCRIPTION
**Pull request by Littlehanger1234C2**
Describe the new addon
I WANT REMOVED SCRATCH 2.0 BLOCKS BACK

I want Thoose blocks come back like forever if , Hide all sprites and more
Link to the new addon
https://en.scratch-wiki.info/wiki/List_of_Obsolete_Blocks

### CODE REVIEW

**Comment by TheColaber** [comment]
Hey thanks for the suggestion! Looks like you've already made an issue for this: #1420. Keep the conversation there since this is a pull request and not an issue.

**Comment by Littlehanger1234C2** [comment]
:( I wish removed blocks will come true ):

**Comment by TheColaber** [comment]
We can't just magically make blocks appear... it takes some time and code. Thanks for the suggestion.

**Comment by Littlehanger1234C2** [comment]
OK That sounds like the deal! :) I'l wait OK

**Comment by Littlehanger1234C2** [comment]
This is a preveviw

image
,
image
AND
image

**Comment by Littlehanger1234C2** [comment]
Please don't let my add on fail please!!!!

**Pull request closed without merging**
