### PR TITLE
Add my forum editor addon

### PR DESCRIPTION
**Pull request by easrng**
**Resolves**

N/A

**Changes**

Adds my addon.

**Reason for changes**

I want my addon to be added.

**Tests**

It works.

### CODE REVIEW

**Comment by WorldLanguages** [comment]
Can you instead use `addon.tab.loadScript(urlString)` which returns a promise when the script has loaded?

**Comment by easrng** [comment]
> Can you instead use `addon.tab.loadScript(urlString)` which returns a promise when the script has loaded?

For marked that's a no, because i need to get multiple instances without redownloading but i might be able to for simplemde. Just a sec.

**Comment by easrng** [comment]
Uh oh
Issue

**Comment by JeffaloBob** [comment]
wasn't the wikimedia open redirect fixed?

**Comment by WorldLanguages** [comment]
I think it was.
Anyway I don't think we'll be merging any new addons until v1.0.0

**Comment by easrng** [comment]
> wasn't the wikimedia open redirect fixed?

Yes, but I made that part of the code before it was and haven't changed it yet.

**Comment by WorldLanguages** [comment]
@easrng What's the state of this PR? Do you want to remove the reference to the now broken wikimedia redirect?

**Comment by easrng** [comment]
There is a bug still, so no.

**Comment by Explosion-Scratch** [comment]
So is this not being merged because of a bug?

**Comment by Explosion-Scratch** [comment]
I'll add the ```pr- do not merge``` label to it then.

**Comment by Explosion-Scratch** [comment]
Feel free to remove that label @WorldLanguages  if you want.

**Comment by WorldLanguages** [comment]
Thanks, I usually don't tag PRs for some weird reason :P

**Comment by Hans5958** [comment]
I'm sorry to tell you, but due to my mistake on the end, I accidentally force-pushed into the master branch, closing this pull request as the result. I have reversed the changes, but I can't reopen the pull request, so you need to make another pull request for this one.

Once again, I apologize for the inconvenience that caused from my mistake.

**Comment by Explosion-Scratch** [comment]
Wait, you closed all of them?!

**Pull request closed without merging**
