### PR TITLE
More block switching

### LINKED ISSUE #963: List of blocks that block switching does not support
**Describe the bug**

Block switching should support switching of the following blocks but doesn't:

- (looks) switch backdrop to ()/switch backdrop to () and wait
- (looks) think ()/say ()
- (looks) think () for () seconds/say () for () seconds
- (music extension) set tempo to ()/change tempo by ()
- (lego ev3) motor () turn this way for () seconds/motor () turn that way for () seconds
- (lego ev3) when brightness < ()/when distance < ()
- (lego ev3) distance/brightness (reporter blocks)
- (lego boost) turn motor () for () seconds/turn motor () for () rotations
- (lego boost) turn motor () on/turn motor () off
- (lego wedo) turn () on/turn () off
- (go direct force & acceleration) spin speed (x|y|z)/acceleration (x|y|z)

**To Reproduce**

1. Drag one of the blocks above into the workspace
2. Right click on the block
3. No option to switch blocks appears

**Expected behavior**

An option to switch between these blocks appears in their context menus.

**Screenshots**

n/a

**Device (please complete the following information):**

- OS: windows 10
- Browser: chrome 87
- Version: Scratch addons v1.4.1

**Additional context**

I also feel like the pen stamp/clear blocks should also be in with pen up/down, but that's up for debate.
Also, this should be relatively easy to fix, just some adding of some opcodes, but I'd like to confirm we'd like all of these switches to be added. My branch to fix this is https://github.com/pufferfish101007/ScratchAddons/tree/more-block-switching

### PR DESCRIPTION
**Pull request by pufferfish101007**
**Resolves**

Resolves #963 

**Changes**

Adds the following block switches:

- (looks) switch backdrop to ()/switch backdrop to () and wait
- (looks) think ()/say ()
- (looks) think () for () seconds/say () for () seconds
- (music extension) set tempo to ()/change tempo by ()
- (lego ev3) motor () turn this way for () seconds/motor () turn that way for () seconds
- (lego ev3) when brightness < ()/when distance < ()
- (lego ev3) distance/brightness (reporter blocks)
- (lego boost) turn motor () for () seconds/turn motor () for () rotations
- (lego boost) turn motor () on/turn motor () off
- (lego wedo) turn () on/turn () off
- (go direct force & acceleration) spin speed (x|y|z)/acceleration (x|y|z)

**Reason for changes**

These switches weren't available before.

**Tests**

Works on chrome.

Once again, sorry for all the commits.

### CODE REVIEW

**Review by WorldLanguages — CHANGES_REQUESTED** [review]
IMO, it's not worth it to ask translators to translate 10+ strings for adding block switching to any extensions that require physical devices to be useful (like the LEGO ones, etc.)
Say and think are meh, but they could be added
Others are OK.

**Comment by pufferfish101007** [comment]
@WorldLanguages ok, that makes sense for the hardware extensions, but can we keep tge set/change tempo? I think that quite a lot of people could find that useful.

**Review by WorldLanguages — APPROVED** [review]

**Comment by lisa-wolfgang** [comment]
This is included under the v.1.6.0 milestone, even though this looks like it's all ready to go. Will this not be included in v.1.5.0?

**Comment by TheColaber** [comment]
> This is included under the v.1.6.0 milestone, even though this looks like it's all ready to go. Will this not be included in v.1.5.0?

This was already merged lol, but idk why they put it in the v1.6.0...

**Pull request merged**
