### PR TITLE
Fix Semicolon Bug

### LINKED ISSUE #1291: Semicolon glitch addon bug
**Describe the bug**
The semicolon doesn't show up at the botton

**To Reproduce**
1. Go to [Scratch](scratch.mit.edu)
2. Scroll to the very bottom of a page
3. The semicolon is white and not black (its used in experamental dark)

**Expected behavior**
The semicolon should be black and visible

**Screenshots**
Screenshot 2021-01-11 at 3 13 43 PM
Screenshot 2021-01-11 at 3 13 34 PM

**Device (please complete the following information):**

- OS: [Chrome OS]
- Browser [Chrome]
- Version [SA: 1.7.0 Chrome: 87]

**Additional context**
The semicolon is only invisible with the website dark mode on.

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
This is the better fix b/c it looks the same on all pages, scratchr2 and www, light and dark modes.
Resolves #1291

### CODE REVIEW

**Comment by RedGuy12** [comment]
Well see #1293

This is why #1295 is better; some people don't want it inverted.
________________________________

**Comment by TheColaber** [comment]
> Well see #1293 This is why #1294 is better; some people don't want it inverted.

No... everybody would want it inverted... who would want a broken addon???

**Comment by RedGuy12** [comment]
This fix right here does not invert it which shows GrahamSH does not want it inverted

________________________________

**Comment by TheColaber** [comment]
> This fix right here does not invert it which shows GrahamSH does not want it inverted

It does not need to be inverted... this is a proper fix. Try testing it...

**Comment by GrahamSH-LLK** [comment]
Quik merging, this has no new strings and is a small bugfix, on a easter egg addon.

**Pull request merged**
