### PR TITLE
support Mac command key in mute project player

### LINKED ISSUE #1891: On mac, ctrl clicking the flag brings up context menu instead of muting
**Describe the bug**

On mac, ctrl clicking the flag brings up context menu instead of muting the project.

**To Reproduce**

1. Go to a project.
2. Right click flag.
3. See error

**Expected behavior**

It would mute the project instead of displaying a context menu.
Something like:

> window.addEventListener('contextmenu', function (e) { 
// mute project
e.preventDefault(); 
}, false);

should fix it.

**Screenshots**

Screen Shot 2021-03-15 at 4 26 45 PM
Screen Shot 2021-03-15 at 4 27 16 PM

**Device (please complete the following information):**

- MacOS Big Sure
- Chrome (Brave) 88

>

### PR DESCRIPTION
**Pull request by scratchusernamemrtbts**
**Resolves**

Resolves #1891

**Changes**

make the mute project player add-on support command key on Mac
**Reason for changes**

Mac user can't use control key to mute because it is right click on Mac
**Tests**

yes
here is a video

https://user-images.githubusercontent.com/66320961/111787284-5802b380-88f1-11eb-8f08-304c282dba17.mov

### CODE REVIEW

**Review by Explosion-Scratch — APPROVED** [review]

**Comment by Explosion-Scratch** [comment]
(why are links red tho)

**Comment by scratchusernamemrtbts** [comment]
my add-on setting set the link to red

**Comment by RedGuy12** [comment]
> (why are links red tho)

it's a 2.0 -> 3.0 setting

**Comment by scratchusernamemrtbts** [comment]
put this in a json file and upload to the add-on
you're link should be red too
`````
{"core":{"lightTheme":false,"version":"1.11.0"},"addons":{"60fps":{"enabled":true,"settings":{"framerate":"60"}},"a11y":{"enabled":true,"settings":{"tabNav":true}},"account-settings-capitalize":{"enabled":true,"settings":{}},"animated-thumb":{"enabled":true,"settings":{"persistentThumb":true}},"better-emojis":{"enabled":true,"settings":{}},"better-featured-project":{"enabled":true,"settings":{}},"better-quoter":{"enabled":true,"settings":{}},"bitmap-copy":{"enabled":true,"settings":{}},"block-switching":{"enabled":true,"settings":{"border":true,"control":true,"data":true,"event":true,"extension":true,"looks":true,"motion":true,"noop":true,"operator":true,"sensing":true,"sound":true}},"cat-blocks":{"enabled":true,"settings":{}},"clones":{"enabled":true,"settings":{}},"cloud-games":{"enabled":true,"settings":{}},"color-picker":{"enabled":true,"settings":{}},"comments-linebreaks":{"enabled":true,"settings":{}},"confirm-actions":{"enabled":true,"settings":{"followinguser":true,"joiningstudio":false,"projectsharing":true}},"copy-message-link":{"enabled":true,"settings":{}},"curator-link":{"enabled":true,"settings":{"styleAsNormalText":false}},"dark-www":{"enabled":true,"settings":{"selectedMode":"experimental-dark"}},"data-category-tweaks-v2":{"enabled":true,"settings":{"moveReportersDown":false,"separateListCategory":true,"separateLocalVariables":true}},"disable-auto-save":{"enabled":false,"settings":{}},"discuss-button":{"enabled":true,"settings":{"buttonName":"Discuss","removeIdeasBtn":false}},"editor-colored-context-menus":{"enabled":true,"settings":{}},"editor-dark-mode":{"enabled":true,"settings":{"selectedMode":"3-darker","textShadow":true}},"editor-devtools":{"enabled":true,"settings":{}},"editor-messages":{"enabled":true,"settings":{}},"editor-searchable-dropdowns":{"enabled":true,"settings":{}},"editor-stage-left":{"enabled":false,"settings":{}},"editor-stepping":{"enabled":true,"settings":{}},"editor-theme3":{"enabled":true,"settings":{"Pen-color":"#0FBD8C","control-color":"#FFBF00","custom-color":"#5f49d8","data-color":"#FF8C1A","data-lists-color":"#FF661A","events-color":"#DE9E2E","looks-color":"#9966FF","motion-color":"#4C97FF","operators-color":"#59C059","sensing-color":"#5CB1D6","sounds-color":"#CF63CF"}},"exact-count":{"enabled":true,"settings":{"forumuser":true,"studio":true,"user":true}},"feature-unshared":{"enabled":true,"settings":{}},"fix-uploaded-svgs":{"enabled":true,"settings":{}},"forum-quote-code-beautifier":{"enabled":true,"settings":{"bordercolor":"#28A5DA"}},"forum-search":{"enabled":true,"settings":{}},"forum-time-zones":{"enabled":true,"settings":{}},"full-signature":{"enabled":true,"settings":{"signature":true,"whathappen":true,"whatworkingon":true}},"hide-flyout":{"enabled":true,"settings":{"speed":"default","toggle":"cathover"}},"image-uploader":{"enabled":true,"settings":{}},"infinite-scroll":{"enabled":true,"settings":{"forumScroll":true,"messageScroll":true,"profileCommentScroll":true,"projectScroll":true,"showFooter":true,"studioScroll":true}},"last-edit-tooltip":{"enabled":true,"settings":{}},"live-featured-project":{"enabled":true,"settings":{"alternativePlayer":"none","autoPlay":false,"forceAlternative":false,"showMenu":false}},"load-extensions":{"enabled":false,"settings":{"music":true,"pen":true,"text2speech":true,"translate":true,"videoSensing":false}},"mediarecorder":{"enabled":true,"settings":{}},"more-links":{"enabled":true,"settings":{}},"mouse-pos":{"enabled":true,"settings":{}},"msg-count-badge":{"enabled":true,"settings":{}},"mute-project":{"enabled":true,"settings":{}},"my-ocular":{"enabled":true,"settings":{"discuss":true,"profile":true}},"onion-skinning":{"enabled":true,"settings":{"afterTint":"#0000FF","beforeTint":"#FF0000","default":true,"layering":"front","mode":"merge","next":0,"opacity":25,"opacityStep":10,"previous":1}},"pause":{"enabled":true,"settings":{}},"progress-bar":{"enabled":true,"settings":{"height":5,"topbar":false}},"project-info":{"enabled":true,"settings":{"editorCount":true}},"project-notes-tabs":{"enabled":true,"settings":{}},"remix-tree-button":{"enabled":true,"settings":{"buttonColor":"#4d97ff"}},"remove-sprite-confirm":{"enabled":true,"settings":{}},"resizable-comment-input":{"enabled":true,"settings":{}},"scratch-messaging":{"enabled":true,"settings":{}},"scratch-notifier":{"enabled":true,"settings":{"becomeownerstudio_notifications":true,"commentsforme_notifications":true,"commentsonmyprojects_notifications":true,"curatorinvite_notifications":true,"favoriteproject_notifications":true,"followuser_notifications":true,"forumpost_notifications":true,"loveproject_notifications":true,"mark_as_read_when_clicked":true,"notification_sound":"addons-ping","remixproject_notifications":true,"studioactivity_notifications":true}},"scratchr2":{"enabled":true,"settings":{"activeColor":"#ff7d7c","linkColor":"#f70000","primaryColor":"#4d97ff"}},"search-load-more-fix":{"enabled":true,"settings":{}},"search-profile":{"enabled":true,"settings":{}},"semicolon":{"enabled":true,"settings":{}},"show-bbcode":{"enabled":true,"settings":{}},"studio-tools":{"enabled":true,"settings":{"mystufftools":true}},"true-youtube-links":{"enabled":true,"settings":{}},"youtube-fullscreen":{"enabled":true,"settings":{}},"longer-wiwo":{"enabled":true,"settings":{}},"variable-manager":{"enabled":true,"settings":{}},"scratchstats":{"enabled":true,"settings":{}},"folders":{"enabled":true,"settings":{}},"block-palette-icons":{"enabled":true,"settings":{}}}}
`````

**Pull request merged**
