### PR TITLE
change canvas color button in costume editor

### PR DESCRIPTION
**Pull request by callumjt**
ive added a button in the costume editor to change the canvas color.

this should be added as its easier to make a sprite if its light or dark

tested on firefox

sorry if there are bugs im still very new to js

preview:
[https://cdn.discordapp.com/attachments/1089456285910573066/1092077085213859940/2023-04-02_14-18-56.mp4](url)

### CODE REVIEW

**Comment by DNin01** [comment]
If I'm correct, this is already covered by:
https://github.com/ScratchAddons/ScratchAddons/blob/5f39d79a88330bf72be8cf9070d9df596d92983b/addons/editor-dark-mode/addon.json#L970
But it might be possible to make these two features compatible with each other.

**Review by DNin01 — CHANGES_REQUESTED** [review]
If you intend for this to be a new addon, don't forget to add the new addon's ID to the `addons.json` file.

Or, as I was suggesting, we could also move this feature to `editor-dark-mode` so they work together.

**Comment by callumjt** [comment]
> If you intend for this to be a new addon, don't forget to add the new addon's ID to the `addons.json` file.
> 
> Or, as I was suggesting, we could also move this feature to `editor-dark-mode` so they work together.

oops i forgot to upload addons.json

**Comment by callumjt** [comment]
ummm why did it request a review from wl?

**Comment by DNin01** [comment]
> ummm why did it request a review from wl?

They're a ["code owner"](https://github.com/ScratchAddons/ScratchAddons/blob/5f39d79a88330bf72be8cf9070d9df596d92983b/.github/CODEOWNERS#L2). It's a GitHub feature that allows reviewers to automatically be requested for certain changes.

**Comment by callumjt** [comment]
> 



> > ummm why did it request a review from wl?
> 
> They're a ["code owner"](https://github.com/ScratchAddons/ScratchAddons/blob/5f39d79a88330bf72be8cf9070d9df596d92983b/.github/CODEOWNERS#L2). It's a GitHub feature that allows reviewers to automatically be requested for certain changes.

ah ok

**Comment by BroJac5246** [comment]
> Or, as I was suggesting, we could also move this feature to `editor-dark-mode` so they work together.

Personally, I think this would be more useful as a separate addon. This is something I would use, but I would not think to look in the editor dark mode addon.

**Comment by WorldLanguages** [comment]
Could we first discuss in a newly created issue about why this feature would be useful? @callumjt Have you seen anyone suggesting this? I can only remember requests of adding a way to dynamically disable the canvas dark mode.

**Comment by callumjt** [comment]
> 



> Could we first discuss in a newly created issue about why this feature would be useful? @callumjt Have you seen anyone suggesting this? I can only remember requests of adding a way to dynamically disable the canvas dark mode.

someone in the discord requested this and i thought it was a good idea so i made it.

**Comment by WorldLanguages** [comment]
Actually, I think I got confused and I was referring here to what you just made:

> I can only remember requests of adding a way to dynamically disable the canvas dark mode.

**Comment by WorldLanguages** [comment]
I think we could possibly remove "canvas dark mode" from editor-dark-mode into a separate addon, what do you think @mxmou?

**Comment by mxmou** [comment]
> I think we could possibly remove "canvas dark mode" from editor-dark-mode into a separate addon, what do you think @mxmou?

The toggle inside the costume editor should probably be a separate addon, but I think the editor dark mode setting would still be useful as a default value.

**Comment by DNin01** [comment]
I just realized, if it were a separate addon, then users could use it even if they prefer light themes for the rest of the editor.

**Comment by Secret-chest** [comment]
You should add settings to customise the colours, and generate the checkerboard colours dynamically

**Comment by WorldLanguages** [comment]
> I just realized, if it were a separate addon, then users could use it even if they prefer light themes for the rest of the editor.

You can already achieve this through the "vanilla Scratch colors" preset.

**Comment by mxmou** [comment]
> > I just realized, if it were a separate addon, then users could use it even if they prefer light themes for the rest of the editor.
> 
> You can already achieve this through the "vanilla Scratch colors" preset.

You can't currently have a dark canvas background in a light theme.

**Comment by callumjt** [comment]
hmm

**Comment by callumjt** [comment]
> hmm

shoot wrong thing

**Comment by callumjt** [comment]
so do you think that this would be accepted? :)

**Comment by callumjt** [comment]
:(

**Comment by callumjt** [comment]
Ye I don't think this is gonna be accepted :(

**Comment by BroJac5246** [comment]
> Ye I don't think this is gonna be accepted :(

It hasn't been closed, so I wouldn't be surprised if it will be accepted.

@WorldLanguages any thoughts?

**Comment by DNin01** [comment]
> Ye I don't think this is gonna be accepted :(

It takes a while for some things to get reviewed - we always have quite a lot to do.

**Comment by callumjt** [comment]
> > Ye I don't think this is gonna be accepted :(
> 
> It takes a while for some things to get reviewed - we always have quite a lot to do.

sorry i am quite impatient

**Review by DNin01 — CHANGES_REQUESTED** [review]
Unfortunately, there are a few things that need to be addressed:
- Dynamic enable/disable don't work. It takes more than specifying `dynamicEnable`/`Disable` in the manifest - sometimes you need to modify code too. Check [this documentation page](https://scratchaddons.com/docs/reference/addon-api/addon.self/#using-addonselfdisabled-and-events-dynamicdisable) for more info.
- This addon could take `Editor dark mode and customizable colors (editor-dark-mode)` into account. For instance, `scene-color` could automatically set the canvas color to light when `editor-dark-mode`'s "Change the costume editor background and selection borders" setting is disabled, and dark when it is enabled.
- The checkerboard pattern should be visible and it should look the same as in `Editor dark mode and customizable colors` and vanilla Scratch.

**Comment by callumjt** [comment]
> Unfortunately, there are a few things that need to be addressed:
> 
> - Dynamic enable/disable don't work. It takes more than specifying `dynamicEnable`/`Disable` in the manifest - sometimes you need to modify code too. Check [this documentation page](https://scratchaddons.com/docs/reference/addon-api/addon.self/#using-addonselfdisabled-and-events-dynamicdisable) for more info.
> 
> - This addon could take `Editor dark mode and customizable colors (editor-dark-mode)` into account. For instance, `scene-color` could automatically set the canvas color to light when `editor-dark-mode`'s "Change the costume editor background and selection borders" setting is disabled, and dark when it is enabled.
> 
> - The checkerboard pattern should be visible and it should look the same as in `Editor dark mode and customizable colors` and vanilla Scratch.

I should be able to do all of those tomorrow but I'm not sure what you mean on 3? Do you
Mean on light mode?

**Comment by DNin01** [comment]
> > Unfortunately, there are a few things that need to be addressed:
> > 
> > * Dynamic enable/disable don't work. It takes more than specifying `dynamicEnable`/`Disable` in the manifest - sometimes you need to modify code too. Check [this documentation page](https://scratchaddons.com/docs/reference/addon-api/addon.self/#using-addonselfdisabled-and-events-dynamicdisable) for more info.
> > * This addon could take `Editor dark mode and customizable colors (editor-dark-mode)` into account. For instance, `scene-color` could automatically set the canvas color to light when `editor-dark-mode`'s "Change the costume editor background and selection borders" setting is disabled, and dark when it is enabled.
> > * The checkerboard pattern should be visible and it should look the same as in `Editor dark mode and customizable colors` and vanilla Scratch.
> 
> I should be able to do all of those tomorrow but I'm not sure what you mean on 3? Do you Mean on light mode?

Here's a comparison:

### Editor dark mode and customizable colors
Light
Dark

### Scene color
Light
Dark
(Also, this picture doesn't show it, but in dark mode, the opaque area on the outside does not change, but `editor-dark-mode` does change it.)

Ideally, these should match. Also note that the background is customizable on `editor-dark-mode`.

**Comment by WorldLanguages** [comment]
> @WorldLanguages any thoughts?

I'm a bit confused over how exactly this new addon would play out with the editor-dark-mode toggle that also changes the canvas color. I think we'd need to discuss that before the PR author continues to make changes to the implementation.
Reviewing this would be a lot simpler if we had discussed this on an issue before the PR submission or if there wasn't an existing toggle that switched the canvas color.

Some more concerns:
1. We'd need to avoid code duplication
2. Does the current implementation support 4 hardcoded color values? Why where those values chosen?

**Comment by callumjt** [comment]
> > @WorldLanguages any thoughts?
> 
> 
> 
> I'm a bit confused over how exactly this new addon would play out with the editor-dark-mode toggle that also changes the canvas color. I think we'd need to discuss that before the PR author continues to make changes to the implementation.
> 
> Reviewing this would be a lot simpler if we had discussed this on an issue before the PR submission or if there wasn't an existing toggle that switched the canvas color.
> 
> 
> 
> Some more concerns:
> 
> 1. We'd need to avoid code duplication
> 
> 2. Does the current implementation support 4 hardcoded color values? Why where those values chosen?

What if on editor dark mode, we see if this addon is enabled and if so we don't change the canvas but we still do the colour variables and this addon gets those colour variable and sets them?

**Comment by Samq64** [comment]
I think the button should be added to `editor-dark-mode` or the canvas setting should be removed from it. Either was I think it could be a colour input instead of a toggle.

**Comment by callumjt** [comment]
ok so let me get this right. in editor dark mode there will now be a switch that has the options light and dark and that will be the default value then this addon will change it? will the light and dark colours be the same for both addons?

**Comment by WorldLanguages** [comment]
>  in editor dark mode there will now be a switch that has the options light and dark and that will be the default value then this addon will change it?

That's one of the best ways IMO, but let's see if someone can think of a better way

> will the light and dark colours be the same for both addons

Don't see why they woudl need to be different.

**Comment by callumjt** [comment]
> > in editor dark mode there will now be a switch that has the options light and dark and that will be the default value then this addon will change it?
> 
> That's one of the best ways IMO, but let's see if someone can think of a better way
> 
> > will the light and dark colours be the same for both addons
> 
> Don't see why they would need to be different.

ok ill start working on that. should i change all the editor dark mode presets too?

**Comment by mxmou** [comment]
> How does editor-dark-mode **currently** determine the background color of the canvas?

If the setting to "change the costume editor background and selection borders" is enabled, it uses the accent color setting. It also generates a few variants of that color. If the setting is disabled, it doesn't make any changes to the costume editor.

> I also wonder what would happen if this new addon is dynamically disabled. Or possibly this addon shouldn't support dynamicDisable at all, to avoid thinking about this edge cases. But it could support dynamicEnable normally.

I imagine it would revert to the vanilla colors, or to the default set in editor dark mode if that is enabled.

> And if editor-dark-mode is dynamically enabled after this new addon runs, then it shouldn't have any effect in the canvas, right? Any other edge cases we need to consider? What happens if the user changes the editor-dark-mode default from light to dark while the editor is open?

Editor dark mode wouldn't affect the state of the light/dark toggle but it might change the exact colors.

Changing the default would have no effect if `scene-color` is enabled. If it's disabled, I would expect the editor dark mode setting to be updated dynamically.

**Comment by WorldLanguages** [comment]
> Editor dark mode wouldn't affect the state of the light/dark toggle but it might change the exact colors.

Hmm, I think I see what you mean, but it's a bit hard to wrap my head around the idea.
So editor-dark-mode may affect both the default when the editor is loading, as well as the exact colors that this other new addon lets the user choose. Am I getting this right?

Honestly, I don't care exactly how we solve this, as long as it's somehow coherent, user choices are migrated when we release a new version, and dynamicDisable/Enable works as expected (or are intentionally unsupported). We need to support all migration cases (for example, I don't think we should enable this new addon by default to people that had the vanilla colors preset), as well as all combinations of dynamicDisable/Enable in all possible orders (both addons can be dynamically enabled in 2 possible orders, or only one of the addons can be dynamically enabled, and if this new addon also supports dynamicDisable then multiply this by two).

**Comment by Secret-chest** [comment]
I can't withstand this ugly black. Please add settings to set exact colours, like we have now.

**Comment by callumjt** [comment]
Shoot forgot about this, I might be able to make it on Thursday

**Comment by WorldLanguages** [comment]
@mxmou Could you write a small pseudo-specification on how exactly this new addon should interact with editor-dark-mode?

**Comment by mxmou** [comment]
> @mxmou Could you write a small pseudo-specification on how exactly this new addon should interact with editor-dark-mode?

Depending on which addons are enabled and how they're configured, a light or dark color scheme may be used:
* If editor dark mode is enabled and `scene-color` is disabled, the active color scheme should be controlled by a new select setting in editor dark mode. The existing setting to change the "costume editor background and selection border" should be removed.
* If `scene-color` is enabled and editor dark mode is disabled, the color scheme is set by the user using the switch added by `scene-color`. The switch is initially set to light mode.
* If both addons are enabled, the color scheme is controlled by the switch. The initial value of the switch depends on the editor dark mode setting.

A color scheme defines the following colors:
* artboard: the 480x360 area in the middle of the canvas. Scratch's default color: `#ffffff`
* workspace: the darker outer area. Default color: `#ecf1f9`
* checkerboard pattern. Default color: `#d9e3f2`
* background: the background of the `<canvas>` element. It's only visible when zoomed very far out. Default color: `#d9e3f2`

Editor dark mode currently also changes a few other colors. Those shouldn't be affected by the new addon.

How exactly each color scheme looks depends on editor dark mode settings:
* If editor dark mode is disabled, the light color scheme is the same as Scratch's defaults. The dark color scheme could use `#575e75`, Scratch's dark gray color, as a base color.
* If editor dark mode is enabled, both color schemes should be generated based on its settings.

Enabling or disabling editor dark mode while `scene-color` is enabled shouldn't change the state of the switch. Disabling `scene-color` while editor dark mode is enabled should reset the color scheme to the default set in editor dark mode, but it should probably remember the state of the switch and use it again when the addon is reenabled.

**Comment by callumjt** [comment]
> > > Unfortunately, there are a few things that need to be addressed:
> > > 
> > > * Dynamic enable/disable don't work. It takes more than specifying `dynamicEnable`/`Disable` in the manifest - sometimes you need to modify code too. Check [this documentation page](https://scratchaddons.com/docs/reference/addon-api/addon.self/#using-addonselfdisabled-and-events-dynamicdisable) for more info.
> > > * This addon could take `Editor dark mode and customizable colors (editor-dark-mode)` into account. For instance, `scene-color` could automatically set the canvas color to light when `editor-dark-mode`'s "Change the costume editor background and selection borders" setting is disabled, and dark when it is enabled.
> > > * The checkerboard pattern should be visible and it should look the same as in `Editor dark mode and customizable colors` and vanilla Scratch.
> > 
> > 
> > I should be able to do all of those tomorrow but I'm not sure what you mean on 3? Do you Mean on light mode?
> 
> Here's a comparison:
> ### Editor dark mode and customizable colors
> 
> Light Dark
> ### Scene color
> 
> Light Dark (Also, this picture doesn't show it, but in dark mode, the opaque area on the outside does not change, but `editor-dark-mode` does change it.)
> 
> Ideally, these should match. Also note that the background is customizable on `editor-dark-mode`.

how do i change the opaque area? i thought the this code would do the job but it doesnt seem to work 
image

**Comment by Secret-chest** [comment]
I still don't understand, can't the colours be customisable?

**Comment by callumjt** [comment]
> I still don't understand, can't the colours be customisable?

yeee umm i have no clue on how to do that

**Comment by callumjt** [comment]
I have no motivation to make this so imma just close it

**Pull request closed without merging**
