### PR TITLE
remove "check format" from format code action

### PR DESCRIPTION
**Pull request by RedGuy12**
**Resolves**

none

**Changes**

removed "check format"

**Reason for changes**

it's annoying that it says it failed when it actually worked just fine. it spams my emails

**Tests**

i have this action on my own repos and it works

### CODE REVIEW

**Comment by Hans5958** [comment]
> it spams my emails

Then turn it off, as in turn off the notification on https://github.com/settings/notifications.

image

**Comment by GrahamSH-LLK** [comment]
> > it spams my emails
> 
> Then turn it off, as in turn off the notification on https://github.com/settings/notifications.
> 
> image

Yeah, Github Actions notifs are useless

**Comment by RedGuy12** [comment]
But I want to know if the CI on my repos fails.
________________________________

**Comment by WorldLanguages** [comment]
> i have this action on my own repos and it works

If so, merge it yourself at your own risk :P

**Pull request merged**
