### PR TITLE
README: Add badge for Discord online users

### LINKED ISSUE #7676: Display total number of online Discord users on README.md
It would be cool to reflect the status of our Discord community on our repository's README, instead of a static badge that just says "chat on discord". It's probably pretty easy to display our server's online user count.

<sub>Note: I don't use Discord.</sub>

### PR DESCRIPTION
**Pull request by DNin01**
Resolves #7676

### Changes

Changes the static "chat on discord" badge to a dynamic badge that displays the number of users on our Discord server who are online.

### Reason for changes

It's a great opportunity to display the statistic.

### CODE REVIEW

**Review by Samq64 — APPROVED** [review]

**Review by WorldLanguages — APPROVED** [review]

**Comment by WorldLanguages** [comment]
Oh, I thought this was a link to the dev server, not the community server 🤔

**Comment by WorldLanguages** [comment]
It was changed by @Hans5958 3 years ago: #2516

It's not a big deal I guess, but it's funny that I didn't notice until now.

**Comment by WorldLanguages** [comment]
Whoops, what happened?

image

**Comment by Hans5958** [comment]
cc @RedGuy12

**Comment by pufferfish101007** [comment]
I've enabled the server widget so it should work now.

**Pull request merged**
