### PR TITLE
Include hidden files in packer action

### PR DESCRIPTION
**Pull request by Samq64**
Resolves https://github.com/ScratchAddons/ScratchAddons/pull/7134#issuecomment-2552137326

Tells upload-artifact to explicitly include dotfiles since it doesn't by default anymore. See https://github.com/actions/upload-artifact/issues/602.

### Tests

I successfully ran the action on my fork and loaded the extension into Chromium.

### CODE REVIEW

**Review by DNin01 — APPROVED** [review]
This will work fine, but I think a better approach would be to not have hidden files in the first place.

**Comment by Hans5958** [comment]
Would you guys prefer this or the other solution by @DNin01?

**Comment by Samq64** [comment]
I haven't tested it yet but I like @DNin01's solution better.

**Comment by DNin01** [comment]
I think #8015 will fix the issue that #8012 left behind.

**Comment by DNin01** [comment]
Superseded.

**Pull request closed without merging**
