### PR TITLE
Fix broken credits

### PR DESCRIPTION
**Pull request by lankybox02**
### Changes

Fix 2 broken credit links & add the new username instead of the old (invalid) one.

### Reason for changes

Because no proper credit was given.

### Tests

No tests.

### CODE REVIEW

**Comment by LankyBox01** [comment]
I confirm changes

**Comment by WorldLanguages** [comment]
> Because no proper credit was given.

Could you clarify if this was our mistake? I'm confused

**Comment by Chiroyce1** [comment]
> Could you clarify if this was our mistake? I'm confused

Basically for their credits, they're making a change to refer to their new account instead of some non-functioning links.

**Comment by lankybox02** [comment]
> > Could you clarify if this was our mistake? I'm confused
> 
> Basically for their credits, they're making a change to refer to their new Scratch account instead of some non-functioning links.

^

**Pull request merged**
