### PR TITLE
More consistent icons in `material-forum-editor-buttons`

### PR DESCRIPTION
**Pull request by Mr-Anonymous75**
## Changes

I made all the icons more constistent, and also removed unnecessary borders from all of them.

dark-www on
dark-www off

## Motivation

The icons just seemed kinda inconsistent.

## Tests

I've tested on Chrome 97 and Firefox Dev Edition 97 on Windows 11 21H2, with `dark-www` both on and off.

---

<sup>I usually spend hours cleaning up the SVG code, but I was tired enough by the time I got there - you won't believe how tough link and scratchblocks were.</sup>

### CODE REVIEW

**Comment by Mr-Anonymous75** [comment]
> > I usually spend hours cleaning up the SVG code, but I was tired enough by the time I got there - you won't believe how tough link and scratchblocks were.
> 
> bruh we minify svgs

Whatever

**Comment by Mr-Anonymous75** [comment]
> Are they from the official Google Material icon set? Also, I like them filled.

No. I edited them manually - they're still the same icons, just modified.

**Comment by RedGuy12** [comment]
> No. I edited them manually - they're still the same icons, just modified.

This probably won't be added then

**Comment by Secret-chest** [comment]
> > I like them filled.
> 
> Well, filled icons would look slightly out of place with the link icon and some of the others.

Why? The link icon just dosen't have an area to be filled.

**Comment by Mr-Anonymous75** [comment]
@WorldLanguages Review this please

**Comment by apple502j** [comment]
Icon looks good. Can anyone screenshot that before/after the changes on light/default mode?

**Comment by Mr-Anonymous75** [comment]
> Icon looks good. Can anyone screenshot that before/after the changes on light/default mode?

I'll do that in a few minutes

**Comment by Mr-Anonymous75** [comment]
Hmm... The scratchblocks icon stays white with regardless of its background. I'm guessing I'll have to meddle around with dark-www to fix this.

**Comment by mxmou** [comment]
> I'm guessing I'll have to meddle around with dark-www to fix this.

Setting stroke to black in the SVG file should be enough.

**Comment by Mr-Anonymous75** [comment]
> > I'm guessing I'll have to meddle around with dark-www to fix this.
> 
> Setting stroke to black in the SVG file should be enough.

So black stroke with zero width?

**Comment by Mr-Anonymous75** [comment]
Uhh can you do that minify thing again?
<sup>How do you even do that?</sup>

**Comment by Mr-Anonymous75** [comment]
> Icon looks good. Can anyone screenshot that before/after the changes on light/default mode?

Screenshots updated.

**Comment by mxmou** [comment]
The new emoji icon is weird. I think it would make more sense to use original Material icons, which already have both filled and outlined versions.

**Comment by Mr-Anonymous75** [comment]
> The new emoji icon is weird. I think it would make more sense to use original Material icons, which already have both filled and outlined versions.

I'll change the emoji icon to one from Google's material icon set if you'd like.

**Comment by Mr-Anonymous75** [comment]
> > > The new emoji icon is weird. I think it would make more sense to use original Material icons, which already have both filled and outlined versions.
> > 
> > 
> > I'll change the emoji icon to one from Google's material icon set if you'd like.
> 
> Ideally all of them would be from Google's set (either outlined or filled). That's what the addon description promises.

Oh. Well, I've changed the emoji icon for now.
Though I did modify it just a bit to make it thicker.

**Comment by RedGuy12** [comment]
> Though I did modify it just a bit to make it thicker.

***Stop modifying them!***

**Comment by Mr-Anonymous75** [comment]
> > Though I did modify it just a bit to make it thicker.
> 
> _**Stop modifying them!**_

_**If I dont, It'll look inconsistent!**_

**Comment by mxmou** [comment]
> > > Though I did modify it just a bit to make it thicker.
> > 
> > 
> > _**Stop modifying them!**_
> 
> _**If I dont, It'll look inconsistent!**_ Seriously though, all the other icons have a thickness of 2.5px, but unmodified Google icons have a 2px thickness.

If you only use unmodified Google icons, they will all have a thickness of 2px, which will also look consistent.

**Comment by Mr-Anonymous75** [comment]
> > > > Though I did modify it just a bit to make it thicker.
> > > 
> > > 
> > > _**Stop modifying them!**_
> > 
> > 
> > _**If I dont, It'll look inconsistent!**_ Seriously though, all the other icons have a thickness of 2.5px, but unmodified Google icons have a 2px thickness.
> 
> If you only use unmodified Google icons, they will all have a thickness of 2px, which will also look consistent.

I guess I didn't think of that.

**Comment by Secret-chest** [comment]
> > > > > Though I did modify it just a bit to make it thicker.
> > > > 
> > > > 
> > > > _**Stop modifying them!**_
> > > 
> > > 
> > > _**If I dont, It'll look inconsistent!**_ Seriously though, all the other icons have a thickness of 2.5px, but unmodified Google icons have a 2px thickness.
> > 
> > 
> > If you only use unmodified Google icons, they will all have a thickness of 2px, which will also look consistent.
> 
> I guess I didn't think of that.

Please. Stop. Modifying. Them. The. Addon's. Description. Says. That. For. A. Reason.

**Comment by Mr-Anonymous75** [comment]
> If you only use unmodified Google icons, they will all have a thickness of 2px, which will also look consistent.

>Please. Stop. Modifying. Them. The. Addon's. Description. Says. That. For. A. Reason.

Turns out that unmodified Google icons are inconsistent with each other.
<sup>Everyone's probably getting super frustrated right now</sup>

**Comment by mxmou** [comment]
> > If you only use unmodified Google icons, they will all have a thickness of 2px, which will also look consistent.
> 
> > Please. Stop. Modifying. Them. The. Addon's. Description. Says. That. For. A. Reason.
> 
> Turns out that unmodified Google icons are inconsistent with each other. Everyone's probably getting super frustrated right now

They're designed to be used together. Any differences between them are probably intentional.

**Comment by Secret-chest** [comment]
> > > If you only use unmodified Google icons, they will all have a thickness of 2px, which will also look consistent.
> > 
> > > Please. Stop. Modifying. Them. The. Addon's. Description. Says. That. For. A. Reason.
> > 
> > Turns out that unmodified Google icons are inconsistent with each other. Everyone's probably getting super frustrated right now
> 
> They're designed to be used together. Any differences between them are probably intentional.

Yes. Please keep them unmodified.

**Comment by mxmou** [comment]
> Perhaps the inconsistency is a matter of how they're being sized?
> 
> I haven't looked into this much in-depth, but if the icons are different sizes and are all being set to the same size, that might be the issue.

I think they're all 24px, they just have different stroke widths. For example, the bold and italic icons use thicker strokes than most others.

**Comment by Mr-Anonymous75** [comment]
> > Perhaps the inconsistency is a matter of how they're being sized?
> > I haven't looked into this much in-depth, but if the icons are different sizes and are all being set to the same size, that might be the issue.
> 
> I think they're all 24px, they just have different stroke widths. For example, the bold and italic icons use thicker strokes than most others.

Regulating the stroke widths is the whole point of this PR. But if I change them all to unmodified Google icons, won't they be the same as they already were?

**Comment by mxmou** [comment]
> Regulating the stroke widths is the whole point of this PR. But if I change them all to unmodified Google icons, won't they be the same as they already were?

The ones that are currently filled wouldn't be the same as they were.

**Comment by Mr-Anonymous75** [comment]
> > Regulating the stroke widths is the whole point of this PR. But if I change them all to unmodified Google icons, won't they be the same as they already were?
> 
> The ones that are currently filled won't be the same as they were.

I guess.

**Comment by WorldLanguages** [comment]
Sorry for not checking this earlier. What's the status of this PR? Ideally the icons should be taken from Google Material without any arbitrary changes.

**Comment by WorldLanguages** [comment]
Should this PR be closed?

**Comment by Secret-chest** [comment]
> Should this PR be closed?

I think yes.

**Comment by just-a-hriday** [comment]
I'm reviving this PR.

The icons are still inconsistent, and it's bugging me. Sorry for anyone getting frustrated at this point.

I'm going to use unmodified Material icons this time, and I'm going to add a filled/outlined option.

**Comment by Secret-chest** [comment]
Hey, please redo the block icon if you can. It was done by me and it sucks.

**Comment by just-a-hriday** [comment]
> Hey, please redo the block icon if you can. It was done by me and it sucks.

I created an issue in Google's material icons repo requesting a Blockly icon.

In the meanwhile, I'll just use a question mark.

**Comment by Secret-chest** [comment]
Google doesn't make material icons anymore.

**Comment by just-a-hriday** [comment]
> Google doesn't make material icons anymore.

Where did you read that? I can't seem to find proof of anything like that.

It seems like google employees are still replying to github issues too.

**Pull request closed without merging**
