### PR TITLE
Format code

### PR DESCRIPTION
**Pull request by DNin01**
It looks like Prettier has made some changes again and is formatting some things that were fine before. I just opened this pull request so those changes can happen.

I recommend all contributors merge `upstream/master` into their branches once this pull request has been merged to avoid headaches.

### CODE REVIEW

**Comment by DNin01** [comment]
This doesn't make any changes other than updating the formatting, so this can be merged without needing a thorough review.

**Comment by WorldLanguages** [comment]
Let's change the Prettier GitHub action so that it never commits automatically unless you manually run it.

**Comment by DNin01** [comment]
> Let's change the Prettier GitHub action so that it never commits automatically unless you manually run it.

Sure. It won't fix the status check failure, but it would remove some headaches of having to sync the branch and revert format-code commits.

**Comment by DNin01** [comment]
> Can't the action be set to only use a specific version of prettier?

Can we do that with the VS Code extension (and the Node.js module if we ever use that for development)?

**Comment by DNin01** [comment]
But let's start by merging this. This issue is disrupting our contributors' pull requests.

**Comment by WorldLanguages** [comment]
I was thinking about 2 separate workflows because contributors could still want to manually format their code by manually triggering the action, but I bet it's also possible to do it with one, somewhat more confusing though

**Comment by Hans5958** [comment]
> I was thinking about 2 separate workflows because contributors could still want to manually format their code by manually triggering the action, but I bet it's also possible to do it with one, somewhat more confusing though

There's also a way by using `if:` on a step, so the formatting step can be run only on dispatch.

**Comment by DNin01** [comment]
> Let's change the Prettier GitHub action so that it never commits automatically unless you manually run it.

The root problem, though, is that Prettier sometimes changes the way things are formatted. Lots of things naturally change overtime and disrupt workflows when they do. Making this process manual won't solve it completely. It'll only make the situation controllable. Even if we do this, most contributors will have this happen at least once per update because they don't know what they're about to run into. And then they have to wait for us to fix it (because our [rules](https://github.com/ScratchAddons/ScratchAddons/settings/branches) don't allow our action to push to our `master` branch) and then merge upstream into their branches.

Hardcoding a version might help as it would give us control over the problem, but we may still want to update occasionally.

**Comment by WorldLanguages** [comment]
@DNin01 I haven't think of it much, but doesn't hardcoding the version cause similar problems? What would we need to do when we want to increase the version manually? Still, I guess manually updating it is better than it happening automatically with no prior notice.

**Pull request merged**
