### PR TITLE
Smooth Project Borders on 2 to 3.0 pages

### PR DESCRIPTION
**Pull request by Daniel4-Scratch**
**Changes**

I have smoothed the borders for all project and profile preview
Screen Shot 2020-11-25 at 7 49 59 am

using:
```css
.thumb img {
    margin-bottom: 2px;
    border-radius: 5px;
}
```
and 
```json
{
   "url": "all.css",
   "matches": ["https://scratch.mit.edu/*"]
}
```
**Reason for changes**
Just making the project borders smooth

**Tests**
All test passed.

<sup> not 100% if the will be pulled

### CODE REVIEW

**Review by WorldLanguages — CHANGES_REQUESTED** [review]
@mxmou will do the final call, but what I am sure about is that this new CSS should not belong in a new file. Likely in scratchr2.css but not sure.

**Review by mxmou — CHANGES_REQUESTED** [review]
To match the Scratch 3.0 design as much as possible, this should not apply to profile pages (because they are similar to the 3.0 home page, where thumbnails are not rounded). Please move it to `studio.css` (for project and curator tumbnails). And yes, as @WorldLanguages said, `scratchr2.css` is the file that applies to all 2.0-styled pages.

Also, the border radius should be 4px and the margin 8px (to match the Explore page).

**Comment by Daniel4-Scratch** [comment]
Ok, I will do this soon :)

**Comment by Daniel4-Scratch** [comment]
Ok, updated the files

**Comment by Daniel4-Scratch** [comment]
Done

**Review by WorldLanguages — APPROVED** [review]

**Review by mxmou — APPROVED** [review]

**Pull request merged**
