### PR TITLE
New feature: Old Shaped Categories

### PR DESCRIPTION
**Pull request by WildmonkGitHub**
Resolves #

This will fix the round shape categories into thin square shape; this is just a theme of Scratch 2.0 UI.

### Changes

I have put a short CSS code, this will make the round "bubble" type categories into thin square, just like Scratch 2.0.

### Reason for changes

These changes were made because some people were very close to old Scratch 2.0, and they want their Scratch 3 website looks like Scratch 2.

### Tests

Nope! I haven't tested this pull request.

### CODE REVIEW

**Comment by CST1229** [comment]
Did you use the wrong branch? (Note that pull requests are for if you implemented a change and want it to be added to SA; for feature requests use the Issues tab, the Discussions tab or the SA Discord server.)

**Comment by WildmonkGitHub** [comment]
> Did you use the wrong branch? (Note that pull requests are for if you implemented a change and want it to be added to SA; for feature requests use the Issues tab, the Discussions tab or the SA Discord server.)

Well, I haven't update I have created a new feature request that can be added to SA

**Comment by DNin01** [comment]
It looks like you're trying to merge the wrong branch. Please open a new pull request.

When choosing the branch, choose "compare across forks" and select your fork and branch on the right side.

Or take [this shortcut](https://github.com/ScratchAddons/ScratchAddons/compare/master...WildmonkGitHub:ScratchAddons:master).

**Comment by DNin01** [comment]
Also, it is a good idea to create an [issue](https://github.com/ScratchAddons/ScratchAddons/issues) before you make changes. This allows us to discuss and consider the idea before you begin work. Tip: Include a screenshot of what you're proposing in your issue's description.

For reference, issues submit feedback, feature requests, suggestions and bug reports. Pull requests request code changes.

**Comment by DNin01** [comment]
By the way, welcome and thanks for taking the time to contribute. We're happy to help - everyone starts somewhere.

**Pull request closed without merging**
