### PR TITLE
Fix forum exactcount showing just a number

### LINKED ISSUE #731: Shouldn't exact count show 'posts' after it?
Currently it shows this:
image
If it said something like ```6769 posts``` that would be a little better lol

### PR DESCRIPTION
**Pull request by mxmou**
**Resolves**

Resolves #731 

**Changes**

Changes the forum exactcount to show *<number> post(s)* instead of just a number.

### CODE REVIEW

**Comment by TheColaber** [comment]
Please Change to this:

addon.json:
```javascript
{
  "name": "Show exact count",
  "description": "Shows the exact count for user and studio info.",
  "credits": [
    {
      "name": "TheColaber",
      "link": "https://scratch.mit.edu/users/TheColaber"
    },
    {
      "name": "Maximouse",
      "link": "https://mxmou.github.io/exactcount"
    },
    {
      "name": "World_Languages"
    }
  ],
  "settings": [
    {
      "name": "Exact counts for profiles",
      "id": "user",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Exact count for studios",
      "id": "studio",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Exact count for forum user",
      "id": "forumuser",
      "type": "boolean",
      "default": true
    }
  ],
  "userscripts": [
    {
      "url": "user.js",
      "matches": ["https://scratch.mit.edu/users/*/"],
      "settingMatch": {
        "id": "user",
        "value": true
      }
    },
    {
      "url": "studio.js",
      "matches": ["https://scratch.mit.edu/studios/*"],
      "settingMatch": {
        "id": "studio",
        "value": true
      }
    },
    {
      "url": "forum.js",
      "matches": ["https://scratch.mit.edu/discuss/topic/*"],
      "settingMatch": {
        "id": "forumuser",
        "value": true
      },
      "runAtComplete": false
    }
  ],
  "tags": ["community"],
  "enabledByDefault": false
}

```

forum.js:
```javascript
export default async function ({ addon, global, console }) {
  while (true) {
    let userbox = await addon.tab.waitForElement(".postleft dl", { markAsSeen: true });
    if (userbox.childNodes[6].nodeValue.includes("+")) {
      fetch('https://scratchdb.lefty.one/v2/forum/user/info/' + userbox.querySelector("a").innerText)
        .then((response) => response.json())
        .then((data) => {
          userbox.childNodes[6].nodeValue = `${data.counts.total.count} posts`;
        })
    }
  }
}
```
It runs faster and doesn't skip any post if they appear late.

**Review by WorldLanguages — CHANGES_REQUESTED** [review]
This works fine only for English users. Can we find a way that will keep the localization?

**Comment by mxmou** [comment]
> This works fine only for English users. Can we find a way that will keep the localization?

Most of the forums aren't localized at all, and this includes post counts.

**Review by WorldLanguages — APPROVED** [review]

**Comment by TheColaber** [comment]
@mxmou did you see my comment above?

**Comment by WorldLanguages** [comment]
@TheColaber Please PR so that we can see where the changes are.

**Comment by TheColaber** [comment]
> @TheColaber Please PR so that we can see where the changes are.

Hey, so I want to create a new fork cuz mine is getting old. I would have to delete my current fork which has some branches that I have PRs for. If I delete my fork will it get rid of my PRs?

**Comment by mxmou** [comment]
> Hey, so I want to create a new fork cuz mine is getting old. I would have to delete my current fork which has some branches that I have PRs for. If I delete my fork will it get rid of my PRs?

Only delete the branches that are already merged.

**Comment by TheColaber** [comment]
> > Hey, so I want to create a new fork cuz mine is getting old. I would have to delete my current fork which has some branches that I have PRs for. If I delete my fork will it get rid of my PRs?
> 
> Only delete the branches that are already merged.

No, I am saying that my whole fork is old. It is about 70 commits behind and I've merged some things in my main be accident.

**Comment by mxmou** [comment]
> No, I am saying that my whole fork is old. It is about 70 commits behind and I've merged some things in my main be accident.

Then clone it and merge upstream into your main branch.

**Pull request merged**
