### PR TITLE
Add text=auto and more to .gitattributes

### PR DESCRIPTION
**Pull request by DNin01**
A step towards #6779

### Changes

- Sets the `text=auto` Git attribute, which makes Git convert the line endings in files that it thinks are text to LF on checkin (when committing) and to the system's native line ending on checkout.
  - Does not affect Prettier or EditorConfig.
  - Contributors can still use LF during development if they want.
- Marks the most significant file types in the repository as either text or binary as appropriate.
- Tells Linguist (GitHub's renderer) that .vscode/*.json are JSON with Comments files.

### Reason for changes

Often, new contributors can be committing inconsistent line endings if they have not set `core.autocrlf` correctly. This setting performs line ending conversion when checking in changes, and optionally during checkout as well. This means additions and modifications to text files that are committed always use LF characters to mark the ends of lines, which is what we want. Setting `text=auto` in the `.gitattributes` file replicates the desired behavior for checkout (assuming `core.eol` is set to `native`) and checkin.

Learn more:
- https://git-scm.com/docs/gitattributes#_checking_out_and_checking_in
- https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreeol
- https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreautocrlf

Please correct me if I'm wrong.

### Notes

***Tested as of https://github.com/ScratchAddons/ScratchAddons/pull/6821/commits/caddeb53976ea013a41575141534f1caeb6f7840***

Tested in Git version 2.41.0.windows.1 with the following config/attribute combinations:
- `core.autocrlf` = `true`, `* text=auto`
- `core.autocrlf` = `false`, `* text=auto`
- `core.autocrlf` = `false`

Confirmed the following (with `text=auto` unless otherwise specified):
- The index stays the same no matter how `core.autocrlf` is configured (tested with true and false)
- No changes were made when running `git add --renormalize .`
- Before, when this attribute was not set and `core.autocrlf` = `false`, running `git add --renormalize .` can cause CRLF to appear in the index
- Theoretically, this would work on macOS or Linux too, only with the working directory having LF line endings (haven't tested, why didn't setting `core.autocrlf=false` and `core.eol=lf` then switching branches in GitHub Desktop replicate this?)
- I have read the Git documentation and I think I know what I'm doing

Tests:
- [x] Successful test on Windows
- [ ] Successful test on macOS/Linux

### CODE REVIEW

**Review by Hans5958 — APPROVED** [review]
General convention, so LGTM. Probably put it on the top instead on the bottom of `export-ignore`.

**Comment by DNin01** [comment]
I should check what file extensions this applies to.

**Comment by DNin01** [comment]
I haven't found anything that suggests that Git takes file extensions into account when determining whether a file is text or binary, so it would probably be sensible to explicitly mark each file type that appears in the repository as either text or binary.

**Review by TheColaber — APPROVED** [review]

**Comment by DNin01** [comment]
@Hans5958 Some [changes](https://github.com/ScratchAddons/ScratchAddons/pull/6821/commits/89761afa3ee894a879039bb28a1494fe3234e31d) were made since your last review. Does this still look OK? If it is, I think we're ready to merge.

**Review by Hans5958 — COMMENTED** [review]
All good in me.

**Review by Hans5958 — APPROVED** [review]

**Pull request merged**
