### PR TITLE
Everything. Is. Scratch.

### PR DESCRIPTION
**Pull request by CodeGuy92**
### Changes

I just added an addon. This addon will TURN EVERYTHING INTO SCRATCH.

### Reason for changes

Because... why not? (It's an easter egg, after all!)

### Tests

I downloaded the repo and it worked horribly well

### CODE REVIEW

**Comment by CodeGuy92** [comment]
Capture

**Comment by CodeGuy92** [comment]
This would be really funny haha

**Comment by apple502j** [comment]
Scratch. Scratch Scratch. Scratch Scratch Scratch. **Scratch.**

**Comment by CodeGuy92** [comment]
Scratch :(

**Comment by Secret-chest** [comment]
@apple502j Why did you close it?

**Comment by WorldLanguages** [comment]
@Secret-chest There's nothing Scratch specific about the addon's code.

**Comment by CodeGuy92** [comment]
> @Secret-chest There's nothing Scratch specific about the addon's code.

But it's an easter egg
/shrug

**Comment by Secret-chest** [comment]
So please reopen it!

**Comment by Secret-chest** [comment]
> @Secret-chest There's nothing Scratch specific about the addon's code.

It is an easter egg!

**Comment by apple502j** [comment]
Everything is Scratch; thus this change is also scratched.

**Pull request closed without merging**
