### PR TITLE
drag-drop: do not HD-upload images

### PR DESCRIPTION
**Pull request by apple502j**
Resolves a bug where all drag-drop uploads were HD when better-img-uploads is enabled. In case anyone wants old behavior, this is now a setting (off by default, only shows if someone is using HD upload addon).

This code should not break in most circumstances - if better-img-uploads is not available when the settings is true, then it'll just fallback to normal upload (aka existing code path). Dynamic enabling of better-img-uploads should also be fine. It might break when better-img-uploads was dynamically disabled (drag-drop would still upload as HD), but better-img-uploads isn't dynamically disableable yet, so who cares

### CODE REVIEW

**Comment by TheColaber** [comment]
But what if you want them to be?

**Comment by mxmou** [comment]
> 
> 
> But what if you want them to be?

... which most people who enabled the HD upload addon probably do.

**Comment by apple502j** [comment]
@TheColaber @mxmou In that case the last commit can be reverted. @WorldLanguages will you reconsider that?

https://discord.com/channels/751206349614088204/751207339545198682/874283234370945044

**Comment by WorldLanguages** [comment]
> ... which most people who enabled the HD upload addon probably do.

I wouldn't be so sure. We discovered this behavior because someone sent feedback about them wanting to use the normal upload.
Also, "HD image uploads" is beta, sometimes makes images blurrier (source: this same feedback and other people), and the description says it "adds a button".
If we keep this behavior as a setting it should be off by default, even tho it's a ""breaking change""

**Comment by apple502j** [comment]
it's off by default dont worry

**Comment by WorldLanguages** [comment]
Well then the setting can be kept. I kinda forgot we have "if addonEnabled" now so we should keep the setting.

**Pull request merged**
