### PR TITLE
Make profile page banner less blurry

### PR DESCRIPTION
**Pull request by mxmou**
**Resolves**

None

**Changes**

Increases resolution of the profile page banner.

**Reason for changes**

It looks better now.

**Tests**

Before:
Blurry screenshot

Now:
Less blurry screenshot
*(I didn't remove Ocular statuses, I just didn't have the addon enabled when I took the screenshot)*

### CODE REVIEW

**Comment by retronbv** [comment]
wow! Only one change lol

**Comment by RedGuy12** [comment]
Maybe a setting that let's you change blurriness? I like it a little obscured since it's in the background (I also have live featured project)
________________________________
From: Maximouse ***@***.***>
Sent: Monday, March 15, 2021 3:21:19 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] Make profile page banner less blurry (#1889)


Resolves

None

Changes

Increases resolution of the profile page banner.

Reason for changes

It looks better now.

Tests

Before:
[Blurry screenshot]<https://user-images.githubusercontent.com/51849865/111215917-01853480-85d4-11eb-92ca-dcda0eba06c0.png>

Now:
[Less blurry screenshot]<https://user-images.githubusercontent.com/51849865/111215921-04802500-85d4-11eb-9b18-27f6c87a7b1b.png>
(I didn't remove Ocular statuses, I just didn't have the addon enabled when I took the screenshot)

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ScratchAddons/ScratchAddons/pull/1889

Commit Summary

  *   Make profile page banner less blurry

File Changes

  *   M addons/better-featured-project/userscript.js<https://github.com/ScratchAddons/ScratchAddons/pull/1889/files#diff-a4aa9044b0c0518accf669edebd3a026e6f8425eebfeaddac8f21299bdc06299> (2)

Patch Links:

  *   https://github.com/ScratchAddons/ScratchAddons/pull/1889.patch
  *   https://github.com/ScratchAddons/ScratchAddons/pull/1889.diff

**Comment by mxmou** [comment]
> wow! Only one change lol

Yeah, I would do it before but I always thought it was already the maximum resolution. It wasn't.

**Comment by mxmou** [comment]
> Maybe a setting that let's you change blurriness? I like it a little obscured since it's in the background (I also have live featured project)

Good idea.

**Comment by mxmou** [comment]
I added a blur setting, which is an integer between 0 and 5. Maximum blur looks like this:
Blur 5

**Comment by devxan** [comment]
> Maybe a setting that let's you change blurriness? I like it a little obscured since it's in the background (I also have live featured project)

No, bad idea. 
> Good idea.

Wrong
> I added a blur setting, which is an integer between 0 and 5. Maximum blur looks like this:

Ok thats good

**WOW GITHUB UPDATED LIVE** 😮 👏🏻

**Comment by WorldLanguages** [comment]
lol that commit ^ is funny but at least translators get context on what gets blurred here

**Pull request merged**
