### PR TITLE
Update notification for v1.37

### PR DESCRIPTION
**Pull request by WorldLanguages**
image

### CODE REVIEW

**Comment by Jazza-231** [comment]
I am honoured to have my addon on this notifcation

**Comment by BroJac5246** [comment]
@DNin01 do you anticipate being able to make a blog post? Probably not but it could be fun considering it's almost April Fools' Day.

**Comment by DNin01** [comment]
> @DNin01 do you anticipate being able to make a blog post? Probably not but it could be fun considering it's almost April Fools' Day.

I hope so. What would I say that's special for April Fools Day, though?

**Comment by BroJac5246** [comment]
> > @DNin01 do you anticipate being able to make a blog post? Probably not but it could be fun considering it's almost April Fools' Day.
> 
> I hope so. What would I say that's special for April Fools Day, though?

Make jokes about fish? Claim we're announcing Scratch Addons 2.0? Whatever you want.

**Comment by BroJac5246** [comment]
> Claim we're announcing Scratch Addons 2.0?

(To be clear, say "April Fools'" afterwards)

**Pull request merged**
