### PR TITLE
New addon: Folders

### LINKED ISSUE #1179: Sprite folders addon
An addon that lets you group sprites into folders. UX to be discussed.
In order to remember what sprite is in what folder, invisible unicode characters in sprite names could be used to encode what folder a sprite is in (and possibly even a name for the folder). This would mean anyone with Scratch Addons (and this addon enabled) could see the folders, without affecting non extension users.
Alternatively, local storage could be used to store folders, but is less ideal, and would not sync between devices.

### PR DESCRIPTION
**Pull request by GarboMuffin**
**Resolves**

Resolves #1179

**Changes**

**(This is all outdated)**

Implements folders for sprites, costumes, and sounds.

This is *very unfinished*, *very broken*, and *it probably will find a way to corrupt your project*, so please don't use it yet on a project that you don't already have 30 backups of.

https://user-images.githubusercontent.com/33787854/106839608-2ea10780-6664-11eb-8c77-06f1733af6a0.mp4

TODOs & Things that need discussion:

1. Is it worthwhile to implement inline folders similar to Discord's server folders instead of replacing the entire list? (it should be relatively straightforward)
2.  Implement a way for people to manage folders. Currently you manually rename things to `Folder Name/Name`. Possibilities: context menu options (leaning towards this, seems easiest), dedicated button, hovering items over each other like Discord (I don't think this is viable), something else. Thoughts?
3. How should folder names be encoded? It uses a / as a folder divider right now.
4. I need an icon for the button to leave a folder

Going to wait for some thoughts on these (esp. 1 & 2) before continuing.

I wouldn't bother trying to make a big list of all the bugs. I know lots of things are broken and will be rewriting significant portions of this at some point.

You can test it here: https://scratch.mit.edu/projects/483212055/editor

### CODE REVIEW

**Comment by RedGuy12** [comment]
> * I need an icon for the button to leave a folder

download `https://iconify.design/icon-sets/uil/step-backward-circle.html` to `/images/icons/step-backward-circle.svg`

`/images/icons/` would need to be added to the `web_accessible_resources` in `manifest.json`

**Comment by TheColaber** [comment]
> > * I need an icon for the button to leave a folder
> 
> download `https://iconify.design/icon-sets/uil/step-backward-circle.html`

Sure if that fits in the context of scratch (not sa)

> `/images/icons/` would need to be added to the `web_accessible_resources` in `manifest.json`

Not nessasarly. Simply just storing the svg file in the addon's folder as he did with the other image(s) is best.

**Comment by Secret-chest** [comment]
Here is a better icon that fits the Scratch style: http://gugalcrom.net/files/up.svg

**Comment by RedGuy12** [comment]
> Here is a better icon that fits the Scratch style: http://gugalcrom.net/files/up.svg

We only use iconify icons. See the Design page on the Wiki.
________________________________

**Comment by mxmou** [comment]
> We only use iconify icons. See the Design page on the Wiki.

Than only applies to the extension's own UI, not addons.

**Comment by GarboMuffin** [comment]
Decided to try something new


https://user-images.githubusercontent.com/33787854/107298409-f66e4000-6a3a-11eb-8776-3ae565e9b024.mp4


Might go back to how it was before, not sure yet.

**Comment by TheColaber** [comment]
Could this be 2 separate modes? I could see how both could be useful... but I guess for now this one is fine.

**Comment by GarboMuffin** [comment]
Here's how it works right now

https://user-images.githubusercontent.com/33787854/108925405-2b18f480-7602-11eb-961b-af180fc7a643.mp4

This is what folders currently look like to someone who doesn't have the addon: (Notice the Button/)

chrome_6HclGtn9a2

You could call this "feature complete" but it's far from finished.

**Comment by RedGuy12** [comment]
What's on the to do list?

**Comment by GarboMuffin** [comment]
> 
> 
> What's on the to do list?

A lot of bug fixes and internal cleanup

**Comment by WorldLanguages** [comment]
Let's try to merge this within the following days?

**Comment by Barthdry** [comment]
This one is messing up with the scratch editor and once i removed the extension and opened the same project it got messed up.

**Comment by GarboMuffin** [comment]
What project?

**Comment by RedGuy12** [comment]
@barthdy do you have two versions of the extension enabled?
________________________________

**Comment by Barthdry** [comment]
i just changed the name of the other

**Comment by RedGuy12** [comment]
> i just changed the name of the other and enable it

You need to disable the other. Only one can be enabled, regardless of the title.

**Review by WorldLanguages — APPROVED** [review]
Excellent

**Pull request merged**
