### PR TITLE
60fps prevent default

### LINKED ISSUE #425: 60 FPS addon broken
**Describe the bug**

On my chromebook, when I do alt + click, it acts as a right click. I think you might need prevent default.
**To Reproduce**

On a laptop,
1. Go to a project
2. Click on green flag while holding alt.
3. See bug.

**Expected behavior**

It works

ChromeOS

### PR DESCRIPTION
**Pull request by JeffaloBob**
**Resolves**

Resolves #425 

**Changes**

preventDefault

**Reason for changes**

chrome book

**Tests**

i dont have chrome book which i can to download stuff to test.

@GrahamSH-LLK does this solve the issue?

### CODE REVIEW

**Comment by WorldLanguages** [comment]
@GrahamSH-LLK Please confirm whether this fixes the issue.

**Comment by GrahamSH-LLK** [comment]
It doesn't seem to.

**Comment by JeffaloBob** [comment]
> It doesn't seem to.

does alt clicking work in turbowarp for you?

**Comment by GrahamSH-LLK** [comment]
No.

**Comment by JeffaloBob** [comment]
> No.

then i think we will have to re-evaluate the alt click shortcut

**Comment by WorldLanguages** [comment]
@JeffaloBob Try listening for the double click event - if alt is being pressed, prevent default, then enable 60fps mode

**Comment by JeffaloBob** [comment]
@GrahamSH-LLK does this solve the issue?

**Comment by GrahamSH-LLK** [comment]
Nope!

**Comment by JeffaloBob** [comment]
closed because yeah

**Pull request closed without merging**
