### PR TITLE
Support updated tabs on search and Explore pages

### LINKED ISSUE #5925: Scratch updated their search controls, making a few addons look weird
### Description

Scratch updated some code for their search/explore controls, making dark-www have the wrong text color and when hovered, background color and search-profile way too big.

### Steps to reproduce

1. Search for something

### Demonstration(s) and additional context

example image
example image

### Environment

Browser: Microsoft Edge 114.0.1788.0 (Official build) dev (64-bit) 
Scratch Addons version: 1.31.1
Operating system: Windows 11

### PR DESCRIPTION
**Pull request by mxmou**
Resolves #5925

### Changes

Makes `dark-www` and `search-profile` compatible with Scratch's recent changes to tabs in search results and on the Explore page.

### Reason for changes

Scratch changed the implementation of tabs to improve accessibility, which caused bugs in these addons.

### Tests

Tested on Edge and Firefox.

### CODE REVIEW

**Comment by CST1229** [comment]
Is this worthy of a 1.31.3?

**Comment by Samq64** [comment]
> Does this mean we'll need a 1.31.3?

I don't think so since two new addons were already merged.

**Review by WorldLanguages — APPROVED** [review]
Tested in Chromium. Style issues fixed and keyboard navigation works properly.

**Comment by WorldLanguages** [comment]
Merging this as admin.

**Pull request merged**
