### PR TITLE
Automatically typecast number settings to numbers

### PR DESCRIPTION
**Pull request by pufferfish101007**
**Resolves**

Resolves https://github.com/ScratchAddons/ScratchAddons/pull/2116#discussion_r611223125

**Changes**

Adds the number attr to number settings inputs

**Reason for changes**

The value will now be automatically typecasted to a number so that addon.settings.get eeturns the correct type.

**Tests**

Tested on #2116 without the typecasting on the actual addon. Also logged typeof addon.settings.get blah blah blah andit was all correct.

### CODE REVIEW

**Comment by WorldLanguages** [comment]
I'm confused by this PR, and is `number` even a valid HTML attribute for inputs?

**Comment by WorldLanguages** [comment]
AFAIK we already store numbers for number settings?

**Comment by TheColaber** [comment]
> AFAIK we already store numbers for number settings?

Nope.
image
image

**Comment by pufferfish101007** [comment]
> I'm confused by this PR, and is `number` even a valid HTML attribute for inputs?

It's a vue thing, see https://v1.vuejs.org/guide/forms.html#number



> AFAIK we already store numbers for number settings?

For defaults, yes, but when you change it it just v-models it into the settings object which is sent to the background; v-model only uses numbers if youuse the number attr in vue 1. You can try it out by console.logging `typeof addon.settings.get("xyz")` - for me it always is a string without this pr.

**Comment by RedGuy12** [comment]
number is not just a vue thing, it is part of the html spec.
________________________________

**Comment by TheColaber** [comment]
> number is not just a vue thing, it is part of the html spec.

I don't think that's true...

**Comment by pufferfish101007** [comment]
> > number is not just a vue thing, it is part of the html spec.
> 
> I don't think that's true...

Yeah I can't find it anywhere on MDN, and it's in the vue 1 docs.

**Pull request merged**
