### PR TITLE
Improve Browse Followers modal scrolling

### PR DESCRIPTION
**Pull request by mxmou**
### Changes

- Changes the number of items loaded at once to 28 (four rows, two if old studio layout is enabled)
- Replaces infinite scrolling with a Load More button to match Scratch's add projects modal
- Remembers the scroll position when switching between Followers and Following tabs

### CODE REVIEW

**Comment by apple502j** [comment]
@mxmou can you make infinite-scroll addon restore previous behavior?

**Comment by mxmou** [comment]
> @mxmou can you make infinite-scroll addon restore previous behavior?

Done. I also fixed another infinite-scrolling bug.

**Comment by WorldLanguages** [comment]
"Load more" button disappears forever after clicking on it once

**Comment by mxmou** [comment]
> "Load more" button disappears forever after clicking on it once

Fixed.

**Pull request merged**
