### PR TITLE
Make the README.md WAAAYY better. YW.

### PR DESCRIPTION
**Pull request by Ani-Xan**
I saw the current README.md and thought it was a little bland, so I fixed it.

### CODE REVIEW

**Comment by Ani-Xan** [comment]
Don't worry about the checks, it's a markdown file.

**Comment by tb148** [comment]
> 
> 
> Don't worry about the checks, it's a markdown file.

Do worry about them.

**Comment by Ani-Xan** [comment]
@tb148 
Do you have access to merge the commit? Or can just @WorldLanguages merge commits?

**Comment by tb148** [comment]
> 
> 
> @tb148
> Do you have access to merge the commit? Or can just @WorldLanguages merge commits?

Yes, I have write access.

**Comment by Ani-Xan** [comment]
> Yes, I have write access.

Then would you please merge my commit? 🥺

**Comment by WorldLanguages** [comment]
@Ani-Xan I'll look at those tomorrow. Be patient

**Comment by Ani-Xan** [comment]
> @Ani-Xan I'll look at those tomorrow. Be patient

Oh, okay. Sry! 😑

**Comment by WorldLanguages** [comment]
Sorry but I'll write the readme myself soon. In the meantime, I don't find one necessary. You could say something is better than nothing, but having too many people on here before the extension launch can be counterproductive, so I don't see the point yet. This is still a pretty private-ish WIP.

**Comment by Ani-Xan** [comment]
@WorldLanguages Okay, I hear you. I just allowed edits by maintainers.

**Pull request closed without merging**
