### PR TITLE
Add More Padding

### LINKED ISSUE #211: [Feature] The options page is really crowded
**Is your feature request related to a problem? Please describe.**

The options page is really crowded

**Describe the solution you'd like**

Add more padding

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
**Resolves**

Resolves #211 
**Changes**

Add 10px more padding

**Reason for changes**

Cause

**Tests**

Inspect

### CODE REVIEW

**Comment by WorldLanguages** [comment]
Hmm, I see the point, but 20px might be too much? More padding means you can see less addons on the screen at the same time. Let's see what others think.

**Comment by JeffaloBob** [comment]
i already feel like i can't see enough addons on the screen... more padding would make this worse no?

**Comment by GrahamSH-LLK** [comment]
Idea: Use the "More Settings" page, and add a setting for margin level.

**Comment by GrahamSH-LLK** [comment]
@WorldLanguages If you could help add the More Settings page in index.js, that would be great. I'm going to add the bar.

**Comment by GrahamSH-LLK** [comment]
I just need to figure out how to add "addons" to the settings page. //cc @WorldLanguages

**Comment by WorldLanguages** [comment]
Nope that's not how you're supposed to do it.
We haven't yet made a "global extension settings menu" but we will.

> Idea: Use the "More Settings" page, and add a setting for margin level.

That level of customization is too overkill, imo. People can just zoom in or out.

**Comment by GrahamSH-LLK** [comment]
I meant something like gmail, where you can choose Compact, Comfortable, or Default.

**Comment by GrahamSH-LLK** [comment]
Oh, well. I'll close it.

**Pull request closed without merging**
