### PR TITLE
Show exact count bug fixed

### LINKED ISSUE #583: "Show exact count" doesn't handle empty sections on profile page
**Describe the bug**

When the "Exact Counts for Profiles" checkbox is selected while the "Show exact count" addon is enabled, the addon does not notice that sections of the profile that are empty are hidden, causing overflow into other sections.

**To Reproduce**

1. Go to the Scratch Addons settings and enable the "Show exact count" addon (also make sure that the Exact Counts for Profiles checkbox is selected.)
2. Open the profile of any Scratch user for whom at least one of the following is true:
   - The user is not following any studios
   - The user is not a member of any studios
   - The user is not following anyone
   - The user has no followers

(For ease of reproduction, go to [CloudHost's profile](https://scratch.mit.edu/users/CloudHost).)

**Expected behavior**

The addon should account for empty sections of the profile -- in other words, when those values are 0.

**Screenshots**

image

**Device:**

- OS: Windows 10
- Browser: Chrome 86

### PR DESCRIPTION
**Pull request by TheColaber**
**Resolves**

Resolves #583

**Changes**

Fixed code so it can skip boxes that don't show.

**Reason for changes**

So there are no bugs,

**Tests**

Works on chrome,

### CODE REVIEW

**Comment by WorldLanguages** [comment]
This approach won't work for non-English language users. Can you try another way of detecting what row it is, without relying on language?

**Comment by TheColaber** [comment]
> This approach won't work for non-English language users. Can you try another way of detecting what row it is, without relying on language?

I am not sure... there isn't much information in the boxes' elements...

**Comment by mxmou** [comment]
@TheColaber And that's because all of them, except the first two, contain a div with `id="featured"` 🤣

You could probably test the "View all" link.

**Comment by TheColaber** [comment]
> @TheColaber And that's because all of them, except the first two, contain a div with `id="featured"` 🤣
> 
> You could probably test the "View all" link.

🤣 I'll give it a try!

**Comment by TheColaber** [comment]
K, done...

**Comment by WorldLanguages** [comment]
I'll close this in favor of #629, since you also made the changes to this addon there

**Pull request closed without merging**
