### PR TITLE
Compress PNGs

### PR DESCRIPTION
**Pull request by Samq64**
Resolves none

### Changes

Compresses PNGs.

### Reason for changes

Smaller files sizes are always better if the quality is the same.

### Tests

Not tested.

### CODE REVIEW

**Comment by apple502j** [comment]
Please don't compress the logo; otherwise probably ok

**Comment by Samq64** [comment]
> Please don't compress the logo; otherwise probably ok

Why? it's the only one that saves more than 10KB.

**Comment by Samq64** [comment]
@apple502j Which logo are you talking about? sAll of them?

**Comment by apple502j** [comment]
> Why? it's the only one that saves more than 20KB.

Other places use the logo too, and we should use the same file everywhere.

**Review by Weredime — APPROVED** [review]

**Comment by WorldLanguages** [comment]
Does it make sense to compress Scratch emojis?

And many images only save ~100 bytes when compressed, is it worth it to compress those?

**Comment by Weredime** [comment]
> Does it make sense to compress Scratch emojis?
> 
> And many images only save ~100 bytes when compressed, is it worth it to compress those?

It's still better than nothing - We save file space in the bundle size, thus faster downloading and updating. Every little thing counts

**Comment by WorldLanguages** [comment]
I don't think it makes sense to cut 100 bytes in images when we could avoid shipping all language locales within the extension. I think we should only compress some images where it makes sense. If we really want to invest efforts into shrinking extension size (which I'm not convinced we should), that's where we would look first.

**Review by apple502j — APPROVED** [review]

**Comment by Samq64** [comment]
> I don't think it makes sense to cut 100 bytes in images when we could avoid shipping all language locales within the extension. I think we should only compress some images where it makes sense. If we really want to invest efforts into shrinking extension size (which I'm not convinced we should), that's where we would look first.

OK, I'll remove the ones that save less than 500 bytes. I wanted to compress the logo, which actually saves a reasonable amount (25KB) but apple doesn't want me to.

**Comment by Weredime** [comment]
> I don't think it makes sense to cut 100 bytes in images when we could avoid shipping all language locales within the extension. I think we should only compress some images where it makes sense. If we really want to invest efforts into shrinking extension size (which I'm not convinced we should), that's where we would look first.

<sup>build step pls</sup>

**Review by WorldLanguages — CHANGES_REQUESTED** [review]
Blocking merge for now

**Pull request merged**
