### PR TITLE
SECURITY: Sanitize HTML returned from ScratchDB

### PR DESCRIPTION
**Pull request by apple502j**
Defense in depth; not actual vulnerability.

### CODE REVIEW

**Comment by jeffalo** [comment]
unrelated, but you can/should remove the `cleanPost` function. it was a temporary fix in ocular because scratchindexer was vulnerable to xss. thats fixed now.

**Comment by apple502j** [comment]
Well, that function will stay.

**Comment by WorldLanguages** [comment]
@jeffalo Realistically there has never been and there will never be XSS, but it's still _potential_ XSS, if something crazy happens like Cloudflare getting hacked.

**Comment by apple502j** [comment]
Or more realistically, Mozzy's server gets hacked (e.g. domain expired)

**Review by WorldLanguages — APPROVED** [review]

**Comment by WorldLanguages** [comment]
We may be able to use the [window.Sanitizer](https://developer.mozilla.org/en-US/docs/Web/API/Sanitizer) API in the future.

**Pull request merged**
