### PR TITLE
Switch Badges to for-the-badge

### PR DESCRIPTION
**Pull request by Mbrick2**
Resolves None

### Changes

Switched the badge style to for-the-badge

### Reason for changes

It look quite a bit neater

### Tests

Ah... Preview?

### CODE REVIEW

**Comment by Secret-chest** [comment]
Why?

**Comment by Mbrick2** [comment]
> Why?

It look quite a bit neater

**Comment by WorldLanguages** [comment]
I'll probably soon change the README - if it is changed, it will be a single pull request to avoid polluting the commit log with changes that aren't extension code.

**Comment by Hans5958** [comment]
You mean those big "For The Badge" badges? I don't like those...

**Pull request closed without merging**
