### PR TITLE
Adds bookmarklet versions of a couple addons

### PR DESCRIPTION
**Pull request by brourbeinsus**
### Additions

This simply adds a bookmarklet version of a couple addons, I was only able to find 2 that worked correctly, editor stage left and account settings capitalize. Account settings capitalize is kind of useless as a bookmarklet but I thought I would add it just in case.

### Why did I add these?

Mostly for people on mobile devices who can’t download browser extensions and don’t have a developer console, so I went through to see what addons worked as a bookmarklet and found 2.

### CODE REVIEW

**Comment by retronbv** [comment]
But how will this help?

**Comment by RedGuy12** [comment]
No

**Comment by WorldLanguages** [comment]
You may want to take a look at @Scratch-Bookmarklets

**Comment by xItzDiamondx** [comment]
You know about us @WorldLanguages?

**Comment by Shluffy** [comment]
> You know about us @WorldLanguages?

it used to be a scratch forum topic, but that got dustbinned, possibly because of the extension policy

**Pull request closed without merging**
