### PR TITLE
Live forum posts

### LINKED ISSUE #2708: live forum posts
### Is your request related to a problem? Please describe.

I hate refreshing the page over and over just to see a post.

### Describe the solution you'd like

A live forum post addon which automatically adds a new post when posted.

### PR DESCRIPTION
**Pull request by FunctionalMetatable**
Resolves #2708

### Changes

Adds live forum posts addon

### Tests

Tested locally

### CODE REVIEW

**Comment by WorldLanguages** [comment]
This feels too spammy because forums are still from the 2.0 era...

**Comment by GrahamSH-LLK** [comment]
I feel like this will mess up like all forum addons?

**Comment by FunctionalMetatable** [comment]
> I feel like this will mess up like all forum addons?

How? We could use `addon.tab.waitForElement` instead of `document.querySelectorAll`

**Comment by FunctionalMetatable** [comment]
Should I merge this addon into the `live-comments` addon I'm working on in #3064?

**Comment by WorldLanguages** [comment]
No

**Comment by WorldLanguages** [comment]
I'm closing, there's more cons than pros:
1. Many forum addons need to be changed
2. This spams Scratch's servers, and forum pages load specially slowly (which would hint they take more time for Scratch servers to handle)

Live comment does not have con 1, is way more useful, and is less spammy, but it's also in a gray area. We need to consider the Scratch Team is actively trying to discourage Scratch being used for chatting

**Pull request closed without merging**
