### PR TITLE
Bump to prerelease 1.10.0

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
What do you _think_ this is?
<sub><sup>(Rhetorical Question)</sup></sub>

### CODE REVIEW

**Comment by TheColaber** [comment]
not evil code

**Comment by WorldLanguages** [comment]
nuuu where's v2.0.0

**Comment by TheColaber** [comment]
someone do something great for a 2 point o

**Comment by GrahamSH-LLK** [comment]
> nuuu where's v2.0.0

@WorldLanguages I was tempted to make this PR change every single bit of orange to blue and call it v2 😛

**Comment by TheColaber** [comment]
> > nuuu where's v2.0.0
> 
> @WorldLanguages I was tempted to make this PR change every single bit of orange to blue and call it v2 😛

now truly we could have an easter egg that does that

**Pull request merged**
