### PR TITLE
Add color settings to Scratch 2.0 → 3.0

### LINKED ISSUE #415: Add color selection settings to Scratch 2.0 -> 3.0
This awesome addon by Maximouse can easily alter the colors of the header and the hover color and normal color of links. Please add this function into settings!

### PR DESCRIPTION
**Pull request by mxmou**
**Resolves**

Resolves #415 

**Changes**

Adds color settings to the 2.0 → 3.0 addon.
image

These settings will be moved to website dark mode if #657 is implemented. I added the notice because enabling the addon, then changing the primary color immediately doesn't update the text color (see #783).

The added files have nothing to do with compatibility, but they're named like that for a reason.

### CODE REVIEW

**Comment by WorldLanguages** [comment]
This won't be merged in time for v1.6.0 because of localization (and well, Christmas!) 
Can you explain what you mean by this?
>These settings will be moved to website dark mode if #657 is implemented.

I do not understand, what stops you from moving these to website dark mode, where it would likely make the most sense?

**Comment by mxmou** [comment]
> I do not understand, what stops you from moving these to website dark mode, where it would likely make the most sense?

2.0 → 3.0 currently overrides website dark mode, and some parts of it rely on that. And website dark mode doesn't change the primary bar color on 2.0-styled pages, so there are currently two different colors. I'm not yet sure how this should be implemented -- as two separate settings?

**Comment by WorldLanguages** [comment]
@mxmou That makes sense, I simply did not understand why you said the sentence I quoted.

**Comment by WorldLanguages** [comment]
My navbar looks like this on default settings, what am I missing?
image

**Comment by mxmou** [comment]
@WorldLanguages Fixed.

**Review by WorldLanguages — APPROVED** [review]

**Pull request merged**
