### PR TITLE
Default project addon

### LINKED ISSUE #1975: Option to remove "My Variable" and "Scratch Cat" and "Pop" when making a new project/sprite
When you make a new project, a Scratch Cat sprite appears with a variable named "my variable". Also, whenever you make a blank sprite, "pop" appears in sounds. This is extremely annoying when you had a lot of sprites that used to be blank. What if there was a feature to remove those from coming up whenever you make a new project/sprite? Obviously, Scratch Cat and Pop would still be available in the Sound and Costume library.

### LINKED ISSUE #2573: Change Default Sprites
### Is your request related to a problem? Please describe.

My request is not related to a problem

### Describe the solution you'd like

Create a new addon to change the default loaded sprite to something else other than the cat. I want that when the editor loads, it doesn't show the cat, but my own `.sprite3` file

### Describe alternatives you've considered
None

### Additional context
None

### PR DESCRIPTION
**Pull request by FunctionalMetatable**
Resolves #1975
Resolves #2573

### Changes

Adds an addon which sets a default project when created

### Reason for changes

I do not want to see scratchcat always

### Tests

Tested on Edge

### CODE REVIEW

**Comment by Samq64** [comment]
> Resolves #
> 
> I remember there was an issue - but i cant find it

I think it might have been either #1975 or #2573.

**Comment by FunctionalMetatable** [comment]
> > Resolves #
> > I remember there was an issue - but i cant find it
> 
> I think it might have been either #1975 or #2573.

thanks

**Comment by FunctionalMetatable** [comment]
@WorldLanguages will this be merged for 1.18.0?

**Comment by WorldLanguages** [comment]
> @WorldLanguages will this be merged for 1.18.0?

Yes.

I'll ask griffpatch to create an empty project (no Scratch cat, no pop sound on stage, no "my variable" global variable) and give us the ID, then I'll add it as an "empty project" preset. Then this can be merged.

**Comment by Samq64** [comment]
> > @WorldLanguages will this be merged for 1.18.0?
> 
> Yes.
> 
> I'll ask griffpatch to create an empty project (no Scratch cat, no pop sound on stage, no "my variable" global variable) and give us the ID, then I'll add it as an "empty project" preset. Then this can be merged.

Should he just remove the cat sprite from [https://scratch.mit.edu/projects/510186917/](Untitled-1) or will the addon accept unshared projects?

**Comment by WorldLanguages** [comment]
> will the addon accept unshared projects

Yes, it will, and no changes are needed to support unshared projects.

**Comment by Samq64** [comment]
It doesn't work for me. (I fetched the latest commits on my fork I was using tor add the TurboWarp dark mode preset and decided to test this.) The addon appears, but enabling it doesn't do anything.

**Comment by WorldLanguages** [comment]
> Edit 2: I tried again and the project crashed and the console gave me 11 errors and 4500+ warnings, but I think the crash was caused by me accidentally changing the project ID in settings while the project was loading, so it's not really a problem with the addon.

I doubt it's not a problem with the addon, can you share screenshot?

**Comment by Samq64** [comment]
> you share screenshot?

Screenshot (15)

**Pull request merged**
