### PR TITLE
Customizable block colors now affects developer tools middle click feature

### LINKED ISSUE #666: Customizable block colors does not affect developer tools middle click feature
image

### PR DESCRIPTION
**Pull request by TheColaber**
**Resolves**

Resolves #666

**Changes**

Fixed a bit of devtool bugs and added some CSS for it and theme3.

**Reason for changes**

Well... it's a bug...

**Tests**

On chrome it works.

Edit: I don't know if it's appropriate but idk... should I give credit to myself in devtools? probably not...

Edit Edit: Btw, how do I request a review to people?

### CODE REVIEW

**Comment by WorldLanguages** [comment]
@TheColaber Why do you rename Pen to extensions? Please only change what the issue mentions.

cc @ZenithRogue, since this is your addon.

**Comment by TheColaber** [comment]
> @TheColaber Why do you rename Pen to extensions? Please only change what the issue mentions.
> 
> cc @ZenithRogue, since this is your addon.

I just thought, since the other extensions don't get modified and it would require a bit more work for the devtools addon. If @ZenithRogue is not ok with this I'll revert it.

**Comment by ZenithRogue** [comment]
I will take a good look at this tomorrow. I can see a couple things already that will need to be changed for this

**Comment by TheColaber** [comment]
@ZenithRogue Anything you want me to change?

**Comment by ZenithRogue** [comment]
Sorry, I have been really busy with work. Haven't had a chance to make all the changes. But this PR unfortunately won't work until I made said changes

**Pull request merged**
