### PR TITLE
Add /news to scratchr2

### LINKED ISSUE #888: 2.0 to 3.0 doesn't work on news page
**Describe the bug**

The 2.0 to 3.0 addon doesn't work on the news page
**To Reproduce**

1. Go to https://scratch.mit.edu/news
2. The header isn't switched

**Expected behavior**

The header should be the 3.0 header

**Screenshots**
image

**Device (please complete the following information):**

- OS: Chrome OS
- Browser Chrome
- Version 1.4.0 built from this repository.

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
**Resolves**

Resolves #888

**Changes**

Adds link to JSON
**Reason for changes**

### CODE REVIEW

**Review by mxmou — CHANGES_REQUESTED** [review]
The match should probably be added to `dark-www` too.

**Comment by GrahamSH-LLK** [comment]
@mxmou Fixed.

**Review by mxmou — CHANGES_REQUESTED** [review]
Not `experimental_scratchwww.css`, just `experimental_scratchr2.css`.

**Comment by GrahamSH-LLK** [comment]
> Not `experimental_scratchwww.css`, just `experimental_scratchr2.css`.

Whoops.

**Comment by GrahamSH-LLK** [comment]
We should be good now.

**Review by mxmou — APPROVED** [review]

**Comment by Explosion-Scratch** [comment]
Why is that even there? XD

**Comment by mxmou** [comment]
> Why is that even there? XD

It was used for announcements before it was moved to https://blogscratch.tumblr.com/ in 2015.

**Pull request merged**
