### PR TITLE
Bold block text addon

### PR DESCRIPTION
**Pull request by Secret-chest**
Resolves None

### Changes

Added bold text on blocks addon

### Reason for changes

Readability

### Tests

No, too simple. I tested it in Stylus

### CODE REVIEW

**Comment by RedGuy12** [comment]
I believe the is an option for this in editor dark mode (or it may be in custom block colors,  I don't remember)

If there is not a option, you can add one to custom block colors. Not its own addon.
________________________________
From: Secret-chest ***@***.***>
Sent: Tuesday, June 15, 2021 1:11:06 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] Bold block text addon (#2789)


Resolves None

Changes

Added bold text on blocks addon

Reason for changes

Readability

Tests

No, too simple. I tested it in Stylus

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ScratchAddons/ScratchAddons/pull/2789

Commit Summary

  *   Update addons.json
  *   Create addon.json
  *   Create userstyle.css

File Changes

  *   M addons/addons.json<https://github.com/ScratchAddons/ScratchAddons/pull/2789/files#diff-bb33cb076f6d0e3d6cfe187036954a1ca81e6bf0b7f141f578f4805426fa48e7> (1)
  *   A addons/bold-block-text/addon.json<https://github.com/ScratchAddons/ScratchAddons/pull/2789/files#diff-521ed9eb80c295b0e7fdabdec02dc034e28c1238a2e69f771923733768152063> (12)
  *   A addons/bold-block-text/userstyle.css<https://github.com/ScratchAddons/ScratchAddons/pull/2789/files#diff-61d9fe6883d1842e3d0a9db184a4f3b7a0fc9ee80637f4ae79dc98d86a72aa3f> (3)

Patch Links:

  *   https://github.com/ScratchAddons/ScratchAddons/pull/2789.patch
  *   https://github.com/ScratchAddons/ScratchAddons/pull/2789.diff

**Comment by mxmou** [comment]
> I believe the is an option for this in editor dark mode (or it may be in custom block colors, I don't remember) If there is not a option, you can add one to custom block colors. Not its own addon.

The option is in editor dark mode and it's called "text shadow on blocks". Not exactly the same as this. I think this should be another setting in the same addon.

**Comment by WorldLanguages** [comment]
@mxmou Do you think this should be part of editor dark mode and customizable colors?

**Comment by mxmou** [comment]
> @mxmou Do you think this should be part of editor dark mode and customizable colors?

I think it should because text shadow is in the same place.

**Comment by Secret-chest** [comment]
> > @mxmou Do you think this should be part of editor dark mode and customizable colors?
> 
> I think it should because text shadow is in the same place.

@mxmou Then I'll move the text shadow here.

**Comment by mxmou** [comment]
> > > @mxmou Do you think this should be part of editor dark mode and customizable colors?
> > 
> > 
> > I think it should because text shadow is in the same place.
> 
> @mxmou Then I'll move the text shadow here.

I wouldn't do that - one of the editor dark mode presets enables the text shadow setting, and I think it should stay that way.

**Comment by WorldLanguages** [comment]
@mxmou Do you think this still has a chance as an independent addon? Don't forget "text shadows in blocks" is only part of dark mode because the author of "Dark editor" arbitrarily decided to add it to the userstyle way before it was an addon.

**Comment by mxmou** [comment]
> @mxmou Do you think this still has a chance as an independent addon? Don't forget "text shadows in blocks" is only part of dark mode because the author of "Dark editor" arbitrarily decided to add it to the userstyle way before it was an addon.

It's very small and we already have two addons that could have this as a setting.

**Comment by WorldLanguages** [comment]
Which two? Custom block shape → custom block appearance?

**Comment by mxmou** [comment]
> Which two? Custom block shape → custom block appearance?

Dark mode and custom block colors.

**Comment by WorldLanguages** [comment]
@mxmou Do you think we could add this for 1.19 either as a separate addon or setting in a different addon?

**Comment by mxmou** [comment]
When this is added, I think we should consider moving the text shadow on blocks setting to either this addon (if it's a separate addon) or customizable block colors.

**Comment by Secret-chest** [comment]
> When this is added, I think we should consider moving the text shadow on blocks setting to either this addon (if it's a separate addon) or customizable block colors.

Yeah, Maybe "Block text style tweaks" as a better name, this and text shadow? The shadow is unrelated to dark mode and is there because of Dark Editor, which could be changed to not enable the shadow.

**Comment by WorldLanguages** [comment]
I dislike big addons (we should split editor-devtools at some point) so I'd like to move dark mode text shadow and bold to a single addon. Don't think it suits customizable block colors.

**Comment by lisa-wolfgang** [comment]
I made some additional changes, but since the PR author deleted the branch with their proposed changes, I'm migrating this addon to another PR: #4031

**Pull request closed without merging**
