### PR TITLE
Rename the setting “Maximum number of lines” in Line breaks in comments

### PR DESCRIPTION
**Pull request by DNin01**
Resolves no open issues.

### Changes

Changed “Maximum number of lines” to “Maximum number of lines visible at once”.

### Reason for changes

- To make the addon easier to understand

### Tests

Didn’t test the changes, but there weren’t any code changes.

### CODE REVIEW

**Comment by mxmou** [comment]
I agree with the setting name change, but I think the previous description was more accurate. The addon doesn't make line breaks in comments you write visible to others - it makes line breaks in all comments (including those written by people who don't use the addon) visible to you.

The scrollbar setting is on by default because comments with line breaks visible can be really tall.

**Comment by DNin01** [comment]
> I agree with the setting name change, but I think the previous description was more accurate. The addon doesn't make line breaks in comments you write visible to others - it makes line breaks in all comments (including those written by people who don't use the addon) visible to you.
> 
> 
> 
> The scrollbar setting is on by default because comments with line breaks visible can be really tall.

Okay. I didn't fully understand how the addon worked. I'll change back everything but the setting name.

**Review by WorldLanguages — APPROVED** [review]

**Comment by WorldLanguages** [comment]
@mxmou Do you want to suggest any more changes? If not, you can merge this

**Comment by mxmou** [comment]
Adding a notice explaining that people without the addon won't see line breaks would probably be a good idea, but that can be a separate PR.

**Comment by WorldLanguages** [comment]
> Adding a notice explaining that people without the addon won't see line breaks would probably be a good idea, but that can be a separate PR.

See #5421

**Pull request merged**
