### PR TITLE
Stop window scrolling when you scroll over a comment

### PR DESCRIPTION
**Pull request by Jazza-231**
Resolves bug report in SA server

### Changes

Just added pointer-events: none; to scroll.css

### Reason for changes

Comments should be ignored and should just scroll the code area

### Tests

Works on brave

### CODE REVIEW

**Comment by CST1229** [comment]
Wouldn't this also prevent the textarea from being focused or selecting anything in it?

**Comment by WorldLanguages** [comment]
> Wouldn't this also prevent the textarea from being focused or selecting anything in it?

Yeah, I think we'd need to fix this with JavaScript instead (event capture and stop-propagation)
CSS will only let you disable all mouse events, it doesn't let you disable just scroll.

**Comment by WorldLanguages** [comment]
For context, apparently this is the bug report

> Intended behavior: Holding CTRL/CMD and scrolling while hovering in the code editor zooms Scratch's code editor in and out.
>
> However, while using the Better Editor Comments addon and zooming while hovering over a code comment, it uses the browser's built-in zoom feature instead of Scratch's to zoom in and out. Happens on SA v1.35.1, both Chrome and Firefox

**Comment by Jazza-231** [comment]
The second I submitted this I knew it didn't work 😭😭 aaaaaaaaaaa

**Comment by Jazza-231** [comment]
See https://github.com/ScratchAddons/ScratchAddons/issues/6829

**Pull request closed without merging**
