### PR TITLE
hide-stage: Fix hidden stage on project page regression and other errors

### PR DESCRIPTION
**Pull request by GarboMuffin**
- Fixes https://github.com/ScratchAddons/ScratchAddons/issues/4866. sa-stage-hidden is now once again applied to the body wrapper, not the root element. A different class is now applied to the root element to style something that isn't inside the body wrapper.
 - Fixes an editor crash when rendering a text bubble after entering and leaving fullscreen with the stage hidden

### CODE REVIEW

**Review by mxmou — APPROVED** [review]

**Comment by GarboMuffin** [comment]
Found another crash I believe related to this addon when leaving fullscreen. Will look at that in the morning.

**Review by Weredime — APPROVED** [review]

**Comment by GarboMuffin** [comment]
So there is another way to do this that is actually probably better

Instead of all these renderer traps, the `display: none` can be replaced with `position: absolute; z-index: -9999999` which hides it in a way that clientWidth and clientHeight aren't 0.

**Comment by WorldLanguages** [comment]
Requesting review again because this PR now uses a different method to hide the stage.

**Review by WorldLanguages — APPROVED** [review]
Tested

**Comment by WorldLanguages** [comment]
Here's a diff between v1.27.1 and this PR: https://github.com/ScratchAddons/ScratchAddons/compare/v1.27.1..a94a371#diff-e9250ac7772b00c94ceb300c763f7664acfa95559f6dbfe8c1094729cde182f6

**Review by Weredime — APPROVED** [review]

**Pull request merged**
