### PR TITLE
Add v1.31 update notification

### PR DESCRIPTION
**Pull request by WorldLanguages**
YT thumbnail and video still pending

image

### CODE REVIEW

**Review by Samq64 — APPROVED** [review]

**Comment by BroJac5246** [comment]
Should the project progress bar revamp be mentioned somewhere? Some people might have been scared away from it before v1.30.1. It's okay if we don't (this is the v1.31.0 notification, after all), but this might be our best opportunity.

Also, if someone creates a blog post, should that be linked?

**Comment by Samq64** [comment]
> Should the project progress bar revamp be mentioned somewhere? Some people might have been scared away from it before v1.30.1. It's okay if we don't (this is the v1.31.0 notification, after all), but this might be our best opportunity.

Oh, right I forgot about that. It should probably get the updated tag even though it's been available to users for a little while.

**Comment by WorldLanguages** [comment]
> Should the project progress bar revamp be mentioned somewhere?

We could add a latestUpdate field. But since it's actually from 1.30.x then it would be weird. If you think it's worth it, open a PR soon and we can discuss it.

**Comment by WorldLanguages** [comment]
> Also, if someone creates a blog post, should that be linked?

Good idea

**Comment by michaeleldar** [comment]
Is there gonna be a video for this release, because I didn't see one.

**Comment by CST1229** [comment]
> Is there gonna be a video for this release, because I didn't see one.

there isn't one - #5785

**Pull request merged**
