### PR TITLE
Create jsfile.js

### PR DESCRIPTION
**Pull request by LankyBox01**
WorldLaunguages told me to add my extension

### CODE REVIEW

**Comment by RedGuy12** [comment]
yeah, that's not how you do it

**Comment by LankyBox01** [comment]
ye i know im trying to fix it

**Comment by retronbv** [comment]
https://github.com/ScratchAddons/ScratchAddons/wiki I would suggest reading the “How to make an addon” wiki page

**Comment by LankyBox01** [comment]
Yes that is what i am trying to do

**Comment by RedGuy12** [comment]
it looks like its only the home page that's having problems

go here Creating an addon · ScratchAddons/ScratchAddons Wiki (github.com)<https://github.com/ScratchAddons/ScratchAddons/wiki/Creating-an-addon>
________________________________

**Comment by GrahamSH-LLK** [comment]
Please A. undelete the branch and B. open the PR
Otherwise, we can't accept this code

**Comment by LankyBox01** [comment]
I can't reopen the pr since i cannot undelete the branch
How do i undelete a branch

**Comment by retronbv** [comment]
> Otherwise, we can't accept this code

this code isn’t even an addon, it’s just a blob of js code in a folder. We couldn’t even accept it if we wanted to. (In its current state)
(No offense @LankyBox01)

**Comment by LankyBox01** [comment]
yes i am trying to recreate it using the wiki tutorial

**Comment by mxmou** [comment]
> How do i undelete a branch

I'm not sure if you can because you deleted the whole fork.

**Pull request closed without merging**
