### PR TITLE
Add Account Settings fix as easter egg

### LINKED ISSUE #1154: Account Settings capitalization.
**Is your feature request related to a problem? Please describe.**

LLK/scratch-www#4731
LLK/scratch-www#4771
https://scratch.mit.edu/discuss/topic/461302/

People want "Account **S**ettings fixed.

**The fix**

It's very easy! It's CSS - not even JavaScript!

```css
.account-nav .dropdown, ul.user-nav {
    text-transform: capitalize;
}
```

One problem: this is kinda small for its own addon...

### PR DESCRIPTION
**Pull request by mxmou**
**Resolves**

Resolves #1154 - see https://github.com/ScratchAddons/ScratchAddons/issues/1154#issuecomment-753487461

**Changes**

Adds an Account Settings capitalization fix as an easter egg addon.

### CODE REVIEW

**Review by WorldLanguages — APPROVED** [review]

**Comment by Hans5958** [comment]
Whilst viewing ScratchAddons/website#141, I saw that this is set as an Easter egg. May I ask why?

**Comment by mxmou** [comment]
> Sorry for the way overdue comment, but whilst viewing [ScratchAddons/website#141](https://github.com/ScratchAddons/website/issues/141), I saw that this is set as an Easter egg. May I ask why?

World_Languages [said it's too small for a normal addon](https://github.com/ScratchAddons/ScratchAddons/issues/1154#issuecomment-753487461). I'm not sure why the scrolling fix was fine though.

**Comment by mxmou** [comment]
Maybe bug fixes could be a separate tag (similar to "beta") on the settings page.

**Comment by Hans5958** [comment]
> 
> 
> Maybe bug fixes could be a separate tag (similar to "beta") on the settings page.

That's really weird. Curator links, which is also a simple addon, does not get added as an Easter egg addon. Probably it's either a double standard, an oversight, or both. 

I would like this not as an Easter egg addon, because of a simple fact that it isn't and shouldn't be. Hopefully, by the time we got tags figured out, we could remove the Easter egg tag and add a tag that is made for minor fixes.

PS. Now the name "Easter egg addons" should be changed into something like "secret addons" or "hidden addons"...

**Comment by WorldLanguages** [comment]
@Hans5958 That could be sorted out as part of #2031

**Comment by Hans5958** [comment]
Yes, I know. That's why I mentioned to solve this "by the time we got tags figured out"

captain obvious

**Pull request merged**
