### PR TITLE
Scrollbar

### PR DESCRIPTION
**Pull request by JeffaloBob**
**Resolves**

Resolves #

**Changes**

**Reason for changes**

**Tests**

### CODE REVIEW

**Comment by GrahamSH-LLK** [comment]
Make sure to change the light.css files. The scrollbar is different in light mode.

**Comment by JeffaloBob** [comment]
image

**Comment by JeffaloBob** [comment]
image

**Comment by JeffaloBob** [comment]
> Make sure to change the light.css files. The scrollbar is different in light mode.

the grey looks fine in dark and light

**Pull request merged**
