### PR TITLE
Add ScratchLab

### PR DESCRIPTION
**Pull request by LankyBox01**
add support for ScratchLab... idk
https://github.com/ScratchAddons/ScratchAddons/issues/1584

**Resolves**

Resolves #

**Changes**

**Reason for changes**

**Tests**

### CODE REVIEW

**Comment by LankyBox01** [comment]
this may not work, im not too sure.

**Comment by RedGuy12** [comment]
This would NOT work. Look at lines 23, 29, and 42 of manifest.json. And each addon would need to add it in their addon.json

But this still needs discussion before implementation!

**Comment by LankyBox01** [comment]
oh gosh

**Comment by GrahamSH-LLK** [comment]
This is absolutely rejected. Adding a new domain to the manifest _disables_ the extension for all users until they agree to it. We would need serious discussion to do this.

**Comment by LankyBox01** [comment]
I've already closed this tough.

**Comment by GrahamSH-LLK** [comment]
I know, I just wanted to put that here so that anyone who sees it doesn't think that the problem was that you didn't finish it/didn't know how to do it.

**Comment by RedGuy12** [comment]
Duplicate of #23
________________________________

**Comment by retronbv** [comment]
> Duplicate of #23
> […](#)

Not a dupe. But an attempt to implement a different scratch editor

**Comment by RedGuy12** [comment]
Yes...it's more matches...
________________________________

**Comment by retronbv** [comment]
Again. Not a dupe. It’s a dupe if it tries to implement the exact same things.

**Comment by TheColaber** [comment]
> Yes...it's more matches...


It implements a shorter way TO match, it does not run on other sites.

**Comment by RedGuy12** [comment]
I got the idea it was both...a shorter way to match isn't very useful until we have more things to match
________________________________

**Comment by TheColaber** [comment]
well that would be the next step. but the point of that would be just to have smaller match patterns rn

**Pull request closed without merging**
