### PR TITLE
Add GIF support to HD Image Uploads Addon

### PR DESCRIPTION
**Pull request by ErrorGamer2000**
### Changes

Added GIF support to HD Image Uploads Addon

### Reason for changes

Scratch itself allows `.gif` uploads, though it splits it into frames. This does the same (with better splitting) with the HD Image Uploads Addon

### Tests

Tested, but my internet sucks and I can't upload a vid.

### CODE REVIEW

**Comment by RedGuy12** [comment]
Update licenses/license-info.json and licenses/REDME.md



________________________________
From: ErrorGamer2000 ***@***.***>
Sent: Friday, July 30, 2021 5:33:13 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] Add GIF support to HD Image Uploads Addon (#3172)

Changes

Added GIF support to HD Image Uploads Addon

Reason for changes

Scratch itself allows .gif uploads, though it splits it into frames. This does the same (with better splitting) with the HD Image Uploads Addon

Tests

Tested, but my internet sucks and I can't upload a vid.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ScratchAddons/ScratchAddons/pull/3172

Commit Summary

  *   Add GIF support

File Changes

  *   M addons/better-img-uploads/userscript.js<https://github.com/ScratchAddons/ScratchAddons/pull/3172/files#diff-854cc3c818d6760de96084d1f214859d4919296db14211aa9204b9c5b218cd4c> (82)
  *   A libraries/thirdparty/cs/libgif.js<https://github.com/ScratchAddons/ScratchAddons/pull/3172/files#diff-481f6f3b808908ee090947dd3e3dbfa3c62bb4c3bede161c522ae7e4992e47b7> (994)

Patch Links:

  *   https://github.com/ScratchAddons/ScratchAddons/pull/3172.patch
  *   https://github.com/ScratchAddons/ScratchAddons/pull/3172.diff

**Comment by WorldLanguages** [comment]
Will we actually add a gif library for this 🤦‍♂️

**Comment by TheColaber** [comment]
Yeah I thought we already rejected this...

**Comment by apple502j** [comment]
It's not omggif, at least /s
but no.

**Comment by ErrorGamer2000** [comment]
I could try to just take out the code I need, and add that to the addon.

**Pull request closed without merging**
