### PR TITLE
Add v1.33.2 update notification

### LINKED ISSUE #6119: Let people know that there might be some issues after the Scratch color changes
It's possible that our addons will have some issues and inconsistencies after Scratch changes the design. It would be nice to let users know why anything looks weird in case that happens. One way we could do this is by releasing a version of Scratch Addons immediately after the update that displays a notification that looks something like this:

> Scratch just had a big update that changes some of the colors around the website. The Scratch Addons team has been working hard to update addons to accommodate, but you might still see some strange things for a little while. If you want, you can disable any themes from Scratch Addons' settings.

### PR DESCRIPTION
**Pull request by WorldLanguages**
Resolves #6119

This update will ship after Scratch deploys the colors update.

brave_r8zy6KvHQp

### CODE REVIEW

**Comment by WorldLanguages** [comment]
@DNin01 I tweaked your suggestion a bit

**Comment by WorldLanguages** [comment]
Accidentally committed to the wrong branch. Ignore the previous 2 commits.

**Review by DNin01 — APPROVED** [review]
I approve the notification wording. Not tested.

**Review by Samq64 — APPROVED** [review]

**Comment by WorldLanguages** [comment]
Sent this update notification (and a few more strings) to translators.

**Pull request merged**
