### PR TITLE
turbowarp-player: send project token

### LINKED ISSUE #4603: [Meta] Changes to projects.scratch.mit.edu
https://github.com/LLK/scratch-www/pull/6773

We should check what addons could be affected by this.

### PR DESCRIPTION
**Pull request by apple502j**
Resolves #4603

See also: https://discord.com/channels/751206349614088204/751207339545198682/981968933819154463

### CODE REVIEW

**Comment by Chiroyce1** [comment]
Maybe a privacy warning since users might be paranoid that their Scratch assets token will be processed by TurboWarp? (won't be sent to the server since it's a fragment and not a query param)

**Comment by WorldLanguages** [comment]
I think this is good enough until we can find a better fix. Of course, sending tokens anywhere in the URL is unideal (URL hash will remain in places like browser history) but it's slightly better than using query params.

**Comment by apple502j** [comment]
TurboWarp's postMessage based API is experimental and currently requires sending the whole sb3, which is not ideal

**Comment by GarboMuffin** [comment]
The experimental postMessage API currently only exists in the packager. I'm planning to add something similar to the main site this weekend or earlier. It should be able to accept just a project.json when that happens.

With ?token= I am concerned that the tokens are expected to expire after an unknown (and possibly short) amount of time.

**Comment by apple502j** [comment]
Token expiration should not be a problem; we can fetch ourselves, and I believe TurboWarp does not fetch the token twice unless reloaded (which is unlikely; they'll probably load from saved files or click TurboWarp button again.)

@WorldLanguages Merge this and get this to 1.26.1?

**Pull request merged**
