### PR TITLE
Uninstall url

### LINKED ISSUE #435: Set uninstall URL to /farewell
See https://github.com/ScratchAddons/website/issues/23

### PR DESCRIPTION
**Pull request by BoomerScratch**
**Resolves**

Resolves #435

**Changes**

Add a script in background.html that sets the uninstall URL.

**Reason for changes**

ScratchAddons/website#23

### CODE REVIEW

**Comment by WorldLanguages** [comment]
Please test your next PR before submitting :(

**Comment by BoomerScratch** [comment]
@WorldLanguages fixed and tested

**Comment by WorldLanguages** [comment]
Can you move it to transition.js? I think it makes sense to put it there.

**Comment by BoomerScratch** [comment]
@WorldLanguages okay, I'll do that.

**Comment by BoomerScratch** [comment]
@WorldLanguages done. (please do a squash merge)

**Review by WorldLanguages — APPROVED** [review]

**Pull request merged**
