### PR TITLE
Change banner hue based on highlight color

### PR DESCRIPTION
**Pull request by mxmou**
### Changes

Makes blue colored areas change based on the highlight color setting.
image

Adds a `"map"` type for custom CSS variables.

### CODE REVIEW

**Comment by WorldLanguages** [comment]
@mxmou I'll merge these PRs for v1.23.1:

- #3942
- #3945 
- #3948
- #3949 
- (this one) #3950

Sounds good?

**Comment by mxmou** [comment]
@WorldLanguages Yes, that's good. This one will have to be updated after merging #3942 to fix conflicts.

**Comment by WorldLanguages** [comment]
@mxmou I merged the rest. Can you resolve the conflicts? And tell me if you have other hotfixes in mind or if we can release 1.23.1 after this PR is merged.

**Comment by mxmou** [comment]
> Can you resolve the conflicts?

Done.

> And tell me if you have other hotfixes in mind or if we can release 1.23.1 after this PR is merged.

I don't think any other hotfixes are necessary. The border color could be changed later because it isn't very important.

**Comment by Secret-chest** [comment]
Can we add a setting to make it have the same saturation and lightness as the navbar too?

**Comment by DNin01** [comment]
@Secret-chest FYI, this pull request was merged two years ago.

**Comment by mxmou** [comment]
> Can we add a setting to make it have the same saturation and lightness as the navbar too?

SA would become unusable and impossible to maintain if there was a setting for every tiny detail. The brightness of this color is controlled by the "colored areas" setting. Perhaps it could use the saturation and lightness of the navigation bar color if "colored areas" are set to "default".

**Comment by Secret-chest** [comment]
Exactly. Can we do it?

**Pull request merged**
