### PR TITLE
Fix bugs in project-notes-tabs

### LINKED ISSUE #6714: Double project note tabs
### Description

Sometimes, if the "Preview project notes" and "Project note tabs" addons are enabled, the project note tabs appear twice.
I also noticed that only the upper ones work. The other just change color upon click, but don't switch the text fields.
Added: Every time you repeat the steps below, an additional bar gets added.
Added: After this happens, the "Preview" button freezes when enabled and doesn't allow to get back to edit mode.

### Steps to reproduce

1. Open a project. Ensure that "Preview project notes" and "Project note tabs" are enabled.
2. Click on "See inside".
3. Click on "See project page".

### Demonstration(s) and additional context

image

### Environment

Browser: Vivaldi 6.2.3105.54 
Scratch Addons version: 1.35.0-prerelease 646ffc2f 
Operating system: Windows 11 Pro 23H2 22631.2338

### PR DESCRIPTION
**Pull request by WorldLanguages**
Resolves portions of #6698
Resolves #6714

### CODE REVIEW

**Comment by WorldLanguages** [comment]
@DNin01 Could you confirm if this fixed "Preview toggle is placed above the remix attribution card" and #6714?

**Review by DNin01 — APPROVED** [review]
This fixes those issues, however, toggling preview on and then off with `project-notes-tabs` on (which currently reverts them to sections) and then entering and leaving the editor causes tabs to show up:
Tabs and Instructions section together

After some time, I also got this to happen:
Remix attribution card and preview toggle turned on with hidden description sections

So not perfect, but it is an improvement!

**Comment by WorldLanguages** [comment]
> After some time, I also got this to happen:

Would be helpful to see the HTML/DOM for that.

**Comment by WorldLanguages** [comment]
I have to admit, I dislike the note tabs addon now 😅

**Pull request merged**
