### PR TITLE
Update signature.css to make the divider line stationary

### PR DESCRIPTION
**Pull request by RedGuy12**
This makes the divider line stay in one place, so it does not look like the signature is part of the post.

**Resolves**

I would have made an issue, but I could fix it so i did

**Changes**

edided the css selector

**Reason for changes**

to make it look nicer

**Tests**

I tested it through DevTools

### CODE REVIEW

**Comment by Hans5958** [comment]
Can you make the PR title more descriptive?

**Comment by RedGuy12** [comment]
> Can you make the PR title more descriptive?

Done

**Comment by GrahamSH-LLK** [comment]
This breaks it, the scrolling no longer works. Also, please make an issue before opening a PR.

**Comment by RedGuy12** [comment]
I must have made the wrong triangle bracket...

Paul Reid

________________________________

**Pull request closed without merging**
