### PR TITLE
Stop using window.console in addons

### PR DESCRIPTION
**Pull request by RedGuy12**
Found a few refrences to window.console in various addons. This pr makes them use the console passed them.

### CODE REVIEW

**Comment by apple502j** [comment]
`window.console` can be used outside project pages.

**Comment by wgyt** [comment]
> `window.console` can be used outside project pages. Sentry-polluted console.log is only used on project pages, not on r2 or other www pages.

Sentry pollution is one of the reasons to not use real console, another is to use better console.

**Comment by TheColaber** [comment]
This still appears to be untested.

**Comment by apple502j** [comment]
Closing as stale; will open another PR later.

**Pull request closed without merging**
