### PR TITLE
Update issue forms

### LINKED ISSUE #5061: Hide "I understand" checkbox
### READ BEFORE CREATING!

- [X] I understand

### Why this would be helpful/solve a problem

The "I understand" checkbox with the "READ BEFORE CREATING!" header and no other text clutters the issue and looks little silly to anyone viewing the issue after it is created.

### What this change does

Hiding the checkbox after the issue is created. (This can already be done through editing since the template only appears the first time)

### Possible alternatives

Removing it.

### Demonstration(s) and additional context

image

### PR DESCRIPTION
**Pull request by Samq64**
Resolves  #5061

### Changes

Updates the issue forms:

- Removes the "I understand" checkboxes
- Removes `required: false`
- Adjusts a couple little things
- ~Deletes the new addon form, since it was pretty much exactly the same as the enhancement one~

### Tests

Untested

### CODE REVIEW

**Review by DNin01 — APPROVED** [review]
Thanks for correcting the checkbox problem. Now I know about that for next time.

And I don't mind the removal of the "new addon" form too much. While for me, it felt useful to have new addon ideas be automatically labeled, triaging them all is not that bad and that was one almost identical form, now out of the way.

**Review by apple502j — APPROVED** [review]

**Comment by Samq64** [comment]
While I'm at, do you want me to add a spot to add enabled addons? This would make more scene after the user has an easier way to get that, but it can be done now.

**Comment by DNin01** [comment]
> While I'm at it, do you want me to add a spot to add enabled addons? This would make more scene after the user has an easier way to get that, but it can be done now.

Maybe. I like when we get to see those just in case.

**Comment by TheColaber** [comment]
> Deletes the new addon form, since it was pretty much exactly the same as the enhancement one

it was added so github could automatically add the "new addon" tag. Please add it back.

**Comment by Samq64** [comment]
> it was added so github could automatically add the "new addon" tag. Please add it back.

@TheColaber Done.

**Review by TheColaber — APPROVED** [review]

**Pull request merged**
