### PR TITLE
add missing glasses easter egg addon

### PR DESCRIPTION
**Pull request by JeffaloBob**
**Resolves**

part of #508 

**Changes**

i added an addon which makes the page blurry, this addon is intended to be part of the easter egg feature i heard was being worked on. i dont know why but i found this addon really funny.
image
image

**Reason for changes**

its really funny

**Tests**

yes it works

### CODE REVIEW

**Comment by YOYITsM3M8** [comment]
Make it so you have to go through like a lot of menus to get to the Addon or something to make it harder to find

**Comment by YOYITsM3M8** [comment]
also your script completely wrecks fullscreen
image

**Comment by JeffaloBob** [comment]
> Make it so you have to go through like a lot of menus to get to the Addon or something to make it harder to find
> 
> **EDIT:**
> One word: Konami code

in the op i mention that this is meant to be part of the Easter egg feature which unlocks joke addons.

**Comment by JeffaloBob** [comment]
> also your script completely wrecks fullscreen
> image

odd, i wonder if full screen uses CSS filter, I'll have a look at that

**Comment by JeffaloBob** [comment]
the joke is no longer funny and also firefox

**Pull request closed without merging**
