### PR TITLE
Fix missing "of"

### PR DESCRIPTION
**Pull request by apple502j**

### CODE REVIEW

**Comment by WorldLanguages** [comment]
AAAAAA we already discussed this

**Comment by mxmou** [comment]
I don't think "new addons of this update" is correct.

**Comment by mxmou** [comment]
I would use "*in* this update".

**Comment by WorldLanguages** [comment]
> I don't think "new addons of this update" is correct.

IMO, it's correct but it sounds weird. Grammatically, it's no different than "new features of this update" which is an exact phrase that returns over 250,000 results on Google

> I would use "_in_ this update".

Too late now :P

**Pull request merged**
