### PR TITLE
UI consistency

### LINKED ISSUE #961: Dark Editor: Create new block
**Describe the bug**

image

It shows "Make a Blo"
The bottom of the modal is not the correct color

ALSO: The colors on the "Add an input" etc. dont have the correct color from "Customize block colors"
**To Reproduce**

1. Go to the editor
2. Click on create new block
3. See error

**Expected behavior**

It says "Make a Block"
The bottom of the modal is the correct color
The colors on the "Add an input" etc. have the correct color from "Customize block colors"

**Screenshots**

image

**Device (please complete the following information):**

- OS: [chromeos]
- Browser [chrome]
- Version [86.0.4240.199 (Official Build) (64-bit)]

**Additional context**

I have "Dark Editor", "Customize block colors", "Project progress bar", "Pause button", "Mouse position", "Developer Tools", "60FPS player mode"  ALL turned on

### LINKED ISSUE #1354: Some website themes slightly affect the editor
Cannot remember what theme it was, but it was styling inputs and textareas even in the editor.

### LINKED ISSUE #1363: UI consistency
### Is your feature request related to a problem? Please describe.

Some addons add features to the Scratch website. Their appearance should be consistent with Scratch itself.

#### Developer tools

- Inputs (search, middle click) should be styled the same as Scratch inputs. This would make it possible to remove some devtools-specific styles from editor dark mode.
- The overlay behind the help popup should be blue to match Scratch's design, the popup itself should have rounded corners and a transparent border.
- The popup doesn't have a close button - it's closed by clicking the background - which might be confusing.

#### Onion skinning

The buttons are slightly larger than the zoom buttons. Either the icons or the padding should be smaller.

#### Auto-hide block palette

If "toggle on" is set to category click, the palette should either not disappear when the cursor leaves it, or the description should be changed to not mention it as an alternative to the lock icon.

#### Record project video

- The popup should be styled like a Scratch popup - using Scratch classes if possible, so it's automatically dark in dark mode.
- The font in the popup is too big (should be 1rem for body text and 0.85rem for the buttons).
- The duration popup has no border when website dark mode is enabled (#1354).

#### Search profile

If the user didn't search for a valid username, the tab turns red and has a scary tooltip that ends with an exclamation mark. Can't it just not appear?

### PR DESCRIPTION
**Pull request by mxmou**
**Resolves**

Resolves #1363
Resolves #1354
Resolves #961 (only the cut off text, the issue mentions other things but they aren't actually bugs)

**Changes**

- Changes the appearance of developer tools and media recorder to match Scratch's design
- The developer tools help popup and the media recorder popup are now compatible with dark mode
- Adds a close button to devtools popup
- Makes the search profile tooltip less scary

The problem with auto-hide block palette I mentioned in the issue is probably a bug, so I'm going to make a separate issue for it.

**Reason for changes**

Consistency.

**Tests**

Screenshots:
image
image
image
image
image
image
image
image

The popups work with all dark mode variants, except that Dark Editor doesn't make them dark, which I think is correct behavior: it already does the same for Make a variable/list/block popups.

### CODE REVIEW

**Comment by WorldLanguages** [comment]
I think I might not be able to merge this until #1253 is completed, unless you separate editor-devtools changes into a separate PR

**Comment by WorldLanguages** [comment]
@mxmou Can you please not modify editor-devtools on this PR so that I can merge it in time for v1.8 (and not cause conflicts on #1390)

**Comment by mxmou** [comment]
@WorldLanguages Done.

**Comment by WorldLanguages** [comment]
I also removed the changing of a string, feel free to PR after release to give time for translators.

**Comment by WorldLanguages** [comment]
@mxmou You can now PR changing the string, and making editor devtools support dark mode.

**Pull request merged**
