### PR TITLE
 Featured Button obscures ocular statuses (ScratchAddons#2464) 

### LINKED ISSUE #2464: better-featured-project obscures long ocular statuses
**Describe the bug**

The "change featured project" button obscures parts of long ocular statuses on profile pages if my-ocular and better-featured-project are enabled.

**To Reproduce**

1. Enable better-featured-project and my-ocular
2. Set your ocular status to something very long
3. Go to your profile page
4. See that part of the status is behind the button

**Expected behavior**

The text should wrap around the button, not be behind it.

**Screenshots**

overlap

**Device (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version: 88.0

(My browser / operating system: Windows NT 10.0, Firefox 88.0, No Flash version detected)

### PR DESCRIPTION
**Pull request by Norbiros**
Resolves #2464

### Changes

The text wrap around the button, not be behind it.

### Reason for changes

The "change featured project" button obscures parts of long ocular statuses on profile pages if my-ocular and better-featured-project are enabled.

### CODE REVIEW

**Comment by Norbiros** [comment]
**Why it shows commits from Fetch and Merge function... Very strange!**

**Comment by GrahamSH-LLK** [comment]
> Why it shows commits from Fetch and Merge function... Very strange!

Because it merges through a merge commit?!

**Comment by apple502j** [comment]
Please don't set styles via JavaScript.

**Comment by mxmou** [comment]
> Please don't set styles via JavaScript.

That addon already uses JavaScript to set styles, but that should probably be changed.

**Comment by Norbiros** [comment]
Okay...
Addon is writed in old style, it uses old techniques etc. I can update it addon, and add style... I will create new pr soon.

**Pull request closed without merging**
