### PR TITLE
Fix middle-click-popup not working if language is set to Turkish/Japanese

### PR DESCRIPTION
**Pull request by Tacodiva**
If the language is set to Turkish, the middle click popup doesn't work. This happens because I accidentally assumed that the first input of the `() of []` block was the variable and the second was the sprite. This is not true in Turkish and maybe other languages.

### CODE REVIEW

**Comment by Tacodiva** [comment]
Uhhhh, sorry about that. I accidentally merged branches the wrong way around :sweat_smile:

**Comment by Samq64** [comment]
> Idk if having those commits are gonna be a problem when the PR they're from gets merged and I don't think I can remove them.

I think PRs are almost always squashed.

**Comment by WorldLanguages** [comment]
PRs are squashed so as long as you agree with the "files changed" tab of the PR we're fine.

**Comment by Tacodiva** [comment]
Yes the diff of this PR is good to go

**Review by WorldLanguages — APPROVED** [review]
The popup now works properly in Turkish.

**Review by apple502j — APPROVED** [review]

**Pull request merged**
