### PR TITLE
Change variable names to maintain consistensy

### LINKED ISSUE #478: Change variable names to maintain consistensy
This is the continuation of #228 and #288 (wow, what a coincidence!), because somehow it wasn't taken seriously.

**Is your feature request related to a problem? Please describe.**

There is an issue where the variables have inconsistent names, either on case, and even naming, probably because they are implemented hastily.

**Describe the solution you'd like**

Let's fix those inconsistencies.

**Firstly**, the options/settings, we need to decide which term to use.

**Secondly**, the case. I propose using camelCase instead of snake_case due to reasons.

1. camelCase is more often used in modern configuration files and manifest files, such as Prettier, ESLint, Node.js, VS Code, and, heck, even Scratch projects.
2. It looks nicer when viewing the code and when it is around variables with also camelCase.
3. camelCase is a standard on JavaScript. This project is JavaScript-based.

**Describe alternatives you've considered**

This can work both ways, and should be discussed nonetheless.

**Additional context**

Here are some changes that I suggested a while ago.

- setting_match -> optionMatch (settings or options?)
- setting_match.setting_id -> optionMatch.id (the "setting" is redundant because it already refers the setting)
- setting_match.setting_value -> optionMatch.value
- enabled_by_default -> enabledByDefault
- potential_values -> potentialValues
- persistent_scripts -> persistentScripts

### PR DESCRIPTION
**Pull request by Hans5958**
**Resolves**

Resolves #478.

**Changes**

Similar changes to #288.

**Reason for changes**

#478

**Tests**

Not tested, but changes have been made consistently using search and replace tools.

### CODE REVIEW

**Comment by WorldLanguages** [comment]
Oh wow

**Review by WorldLanguages — APPROVED** [review]
Appears to work.

**Comment by WorldLanguages** [comment]
Should I merge? Not sure if you want to modify the schema before or after this.

Btw, I find it funny how your spelling of the word "consistency" isn't consistent :P

**Comment by WorldLanguages** [comment]
Have you considered `addon.settings` changing to `addon.options`?

**Comment by Hans5958** [comment]
That's the other half of the story, as I said...

> Firstly, the options/settings, we need to decide which term to use.

**Comment by WorldLanguages** [comment]
> Also, it is currently `addon.options`, but then it can be changed later.

What do you mean' It's currently `addon.settings`.

**Comment by YOYITsM3M8** [comment]
@WorldLanguages i am retronbv in the discord

**Comment by WorldLanguages** [comment]
I'm talking about the `addon.settings` JS API.

**Comment by Hans5958** [comment]
> 
> 
> I'm talking about the `addon.settings` JS API.

Yes, I know. Real talk, man. It was options in the beginning and still options in this PR. Mandela effect much?

**Pull request merged**
