### PR TITLE
Add refreshRequired to manifest

### PR DESCRIPTION
**Pull request by apple502j**
This changes the manifest to add `refreshRequired` which replaces `sa-autoupdate-theme-ignore`. It also shows notice on settings. `refreshRequired` should only be used for themes.

### CODE REVIEW

**Comment by apple502j** [comment]
Note: merge ScratchAddons/manifest-schema#22 first

**Comment by WorldLanguages** [comment]
Needs discussion, moving to v1.8 milestone in order to focus in other stuff in the meanwhile

**Comment by WorldLanguages** [comment]
Instead of working on this, I'd like to work on userscript autorefresh (#783) and "on disabled" listener (#1303) directly, if possible - this is a middle step that could be avoided, and we could make refreshing directly unnecessary.

**Comment by WorldLanguages** [comment]
Added those issues to v1.9.0 milestone - we could still merge this, but it's not worth it.

**Comment by TheColaber** [comment]
I'd actually really like for this to be merged... I'm working on #1303 right now and it's almost done. Until everything transitions to #783 most addons will need refreshRequired for the addons manifest.

**Pull request closed without merging**
