### PR TITLE
New addon: Paint layers

### LINKED ISSUE #4067: Show layer feature for costume editor
### Is your request related to a problem? Please describe.

**No**, it's not related to a problem, just requesting a new addon for Scratch Addons

### Describe the solution you'd like

It will show the **layers** in the **svg** editor in the **costume editor**. will appear as panels on the **right side** of the editor. It can be toggled from the eye icon and layers can be custom edited.

### Describe alternatives you've considered

eye icon **=>** _to hide or show the selected layer_

layer order **=>** _to change layer order of layers from top to bottom_

double click on the layer **=>** _only that layer will remain visible. other layers will not be visible._

### Additional context

More settings and tools can be added. I just wrote what I remember.
like the layers in **photoshop**

sa

### PR DESCRIPTION
**Pull request by TheColaber**
Resolves #4067

### Changes
image

This addon adds a new button near the zoom buttons in the costume editor. Clicking the button shows a panel view of each layer in the currently selected costume. Layers can be moved forward and backward by dragging them in the panel view.

### Reason for changes
The intent of this addon is to make basic costume layer management easier. It will be invaluable to users of the Scratch paint editor.

### Tests
N/A (these will be done when the addon exits draft state)

### Todo
New features:
- [ ] Select/unselect layer on click (partially implemented)
- [ ] Scroll/zoom to layer on click
- [ ] Show/hide selected layers
- [ ] Sort front-to-back/back-to-front
- [ ] Edit single layer (make other layers a configurable transparency; if layer is a group, ungroup layer; regroup layer when finished)
- [ ] Show sublayers when editing layer (plus exit layer button)
- [ ] Name layers (not sure if this is possible to save in costume data)

Improvements:
- [x] Fix canvas stretching
- [x] Make layer list scrollable
- [ ] Fix undo/redo breaking panel view
- [ ] Change layer panel button icon
- [ ] Make layer order more intuitive (front/back labels on top/bottom)
- [ ] Scratch UI/drag styles
- [ ] Dynamic enable/disable
- [ ] `addon.tab.appendToSharedSpace`
- [ ] Move vanilla layer/group buttons to the new layer panel area?

### CODE REVIEW

**Comment by mxmou** [comment]
> Move vanilla layer/group buttons to the new layer panel area?

Anything that acts on the current selection should stay at the top. Anything that acts on the list of layers or a specific layer that isn't necessary selected can be in the layer panel.

**Comment by lisa-wolfgang** [comment]
A layer is really just a group with 1 or more objects, but some users may not be familiar with what a layer actually is. That's why, in my opinion, it makes sense to include related costume editor features inside or near the panel. 

I originally considered adding separate "merge layers", "move layer to front/back", and "move layer forward/backward" features, but I realized that those already exist in the vanilla editor, and it would be confusing to have similarly-named but actually duplicate functionality.

**Comment by mxmou** [comment]
I wouldn't expect enabling an addon to move things though, unless that was the addon main purpose.

**Comment by ilbailba** [comment]
> I originally considered adding separate "merge layers", "move layer to front/back", and "move layer forward/backward" features, but I realized that those already exist in the vanilla editor, and it would be confusing to have similarly-named but actually duplicate functionality.

I think maybe it's not silly to have a second button.  As you know, in most programs, there is more than one way to implement features.

**Comment by TheColaber** [comment]
closing so someone smart can make this

**Pull request closed without merging**
