### PR TITLE
`player-thumb`: Fullscreen loading support and bug fixes

### PR DESCRIPTION
**Pull request by Samq64**
### Changes

- Adds fullscreen mode loading support and fixes the border size
- Disables green flag pointer events until the project is loaded
- Fixs `fullscreen`'s override styles from leaking outside fullscreen mode
- ~~Mostly fixed thumbnail being removed when exiting the editor before the project is started (but sometimes the Redux event fires too early)~~
- Only adds transparency to the loader background once the thumbnail has been injected
- Removed embed support because it's buggy

### Tests

Tested on Chromium, there is a race condition causing the editor menubar to be visible on the loading screen before `.sa-body-editor` is added.

### CODE REVIEW

**Comment by WorldLanguages** [comment]
If there are no rejections, I will merge this before release, unless I forget.

**Comment by Samq64** [comment]
I can keep just the `addon.json` and `fullscreen` selector changes for this release if there isn't enough time.

**Comment by WorldLanguages** [comment]
@Samq64 I will merge this. Is that fine?

**Comment by Samq64** [comment]
> @Samq64 I will merge this. Is that fine?

@WorldLanguages Sure

**Pull request merged**
