### PR TITLE
Scratch font

### PR DESCRIPTION
**Pull request by valmontechno**
Add the "Scratch" font to the text tool of the costume editor

### CODE REVIEW

**Comment by WorldLanguages** [comment]
Has it been removed recently? Where's the context?

**Comment by CST1229** [comment]
> Has it been removed recently? Where's the context?

The font selection item has not been there since 3.0's launch. I don't think the font itself was removed yet.

**Comment by BroJac5246** [comment]
> > Has it been removed recently? Where's the context?
> 
> The font selection item has not been there since 3.0's launch. I don't think the font itself was removed yet.

That's my understanding as well.

**Comment by WorldLanguages** [comment]
Ohh, I see. Would this addon continue to work if Scratch removes the font (not from the list, but from Scratch)

This idea is probably rejected because of licensing issues, right?

**Comment by CST1229** [comment]
> Ohh, I see. Would this addon continue to work if Scratch removes the font (not from the list, but from Scratch)

Probably not.

**Comment by BroJac5246** [comment]
> This idea is probably rejected because of licensing issues, right?

I heard somewhere that that's why it was removed, but I'm not against this. There are still simple workarounds to access the font, so it's not like we're doing anything that's otherwise impossible.

**Pull request closed without merging**
