### PR TITLE
addon.tab.editorMode: Use Redux on /projects/editor/

### LINKED ISSUE #6452: `addon.tab.editorMode` should not rely on the URL
### Description

`addon.tab.editorMode` always returns `editor` if the URL does not change while on fullscreen.

**This is not the case when running Scratch Addons (in dev mode) on scratchfoundation.github.io as there's a special if statement for that that uses Redux to check for fullscreen.**

### Steps to reproduce

1. Go to https://scratch.mit.edu/projects/editor/ while logged out
2. Go full screen
3.  `addon.tab.editorMode` still returns `editor`

### Demonstration(s) and additional context

The easiest fix is probably to use Redux

### Environment

Any browser

### PR DESCRIPTION
**Pull request by Samq64**
Resolves #6452

Tested on Chromium on the website and localhost.

### CODE REVIEW

**Comment by WorldLanguages** [comment]
We should remember that Redux isn't strictly necessary here. It's only needed to support this URL: https://scratch.mit.edu/projects/editor/

If we have trouble using Redux someday, we will come back to this

**Comment by WorldLanguages** [comment]
Can we change this to only use Redux when it's strictly necessary? I don't really like the idea of engaging with Redux for the most basic APIs when it's not really necessary.

These are the only situations where we need to use Redux, I believe:

1. When running scratch-gui locally (`isScratchGui`)
2. If `location.pathname === "/projects/editor" || location.pathname === "/projects/editor/"`

**Comment by Samq64** [comment]
This PR also fixes 404 project pages not returning null. Is it worth keeping that?

**Review by mxmou — APPROVED** [review]

**Review by WorldLanguages — APPROVED** [review]

**Comment by WorldLanguages** [comment]
Note that this did NOT change whether the `.sa-body-editor` class is added to the body or not. I'm going to reopen the issue.

**Pull request merged**
