### PR TITLE
Add reduxCondition to more addons

### PR DESCRIPTION
**Pull request by GarboMuffin**
**Changes**

I missed some addons in #2268

This adds reduxCondition and similar optimizations to:

 - comments-linebreaks
 - remix-tree-button
 - more-links
 - infinite-scroll
 - copy-message-link
 - true-youtube-links
 - better-emojis

Has been at least briefly tested

### CODE REVIEW

**Comment by RedGuy12** [comment]
Some conditions for addons that interact with project comments were removed in #2493 because the same code will run on www studio comments, which doesn't have redux

**Comment by GarboMuffin** [comment]
> Some conditions for addons that interact with project comments were removed in #2493 because the same code will run on www studio comments, which doesn't have redux

The new www studio comments *will* have redux. All scratch-www pages have redux, even contact-us does. It won't be a problem anyways because everything that can run on those pages checks `if (!state.scratchGui) return true;`

**Comment by apple502j** [comment]
Note that reduxCondition is fool-proof so even if we run it on scratchr2 page that should be fine.

**Comment by WorldLanguages** [comment]
TODO: check URL matches for true-youtube-links, probably shouldn't be wildcard

**Pull request merged**
