### PR TITLE
New "customizable banner colors" addon

### PR DESCRIPTION
**Pull request by MystPi**
### Changes
Allows you to customize the color of the discuss, explore, and My Stuff banner. However, you can only change the discuss and My Stuff banners if you have the Scratch 2 to 3 addon enabled.

image

image

image

### Reason for changes

Some people (like me) dislike the default green color. Now you'll be able to change it.

> This is my first addon, so please forgive me if I've done anything wrong.

### CODE REVIEW

**Comment by WorldLanguages** [comment]
@MystPi This is a great first contribution!

The main issue with this is that this is probably too small to be a whole addon.
@mxmou said [here](https://github.com/ScratchAddons/ScratchAddons/issues/1092#issuecomment-1029124658):
> There could even be an addon to change all the banner colors, including Scratch's own ones.

So if this was extended to change other colors, like the Explore header, it would surely be added.
Let's see what mxmou can say about the current state of this PR and then we can consider extending it.

**Comment by MystPi** [comment]
> @MystPi This is a great first contribution!
> 
> The main issue with this is that this is probably too small to be a whole addon. @mxmou said [here](https://github.com/ScratchAddons/ScratchAddons/issues/1092#issuecomment-1029124658):
> 
> > There could even be an addon to change all the banner colors, including Scratch's own ones.
> 
> So if this was extended to change other colors, like the Explore header, it would surely be added. Let's see what mxmou can say about the current state of this PR and then we can consider extending it.

Thanks, and great idea! I could implement an option to change the explore header too.

**Comment by RedGuy12** [comment]
does #3950 not work?

**Comment by WorldLanguages** [comment]
> does #3950 not work?

That only affects variations of blue.

**Comment by MystPi** [comment]
I changed the following:
- Renamed it to "customizable banner colors"
- Added the option to change the explore page's banner

**Comment by lisa-wolfgang** [comment]
I'm thinking that this would fit better as a new option in the "website dark mode and customizable colors" addon. This doesn't mean that we can't reuse what's been created so far, though.

**Comment by mxmou** [comment]
> I'm thinking that this would fit better as a new option in the "website dark mode and customizable colors" addon. This doesn't mean that we can't reuse what's been created so far, though.

I think a separate addon is better, but the "colored areas" setting in dark-www should remain. This means that
* we don't need to add four (or more) new settings to dark-www;
* website dark mode presets can still have a preferred banner color scheme, but it will be ignored if this addon is enabled;
* this addon can have its own presets independent from website dark mode (although the "normal", "darker" and "darker and desaturated" options should probably be duplicated here);
* colors that only appear on one page, for example pink on the WeDo page and teal on the 2020 annual report, would be affected by dark-www and don't need separate settings.

It could have the following settings:
* blue banners
* dark blue banners (could also be generated based on the blue color)
* green banners
* yellow banners
* purple banners

"Areas" might be a better word for these because the colors aren't only used for banners. All of them should also have automatically generated text colors.

The selectors from `addons/dark-www/desaturated_banners.css` could be used in this addon's code.

**Comment by Samq64** [comment]
If most of this addon's code and presets are being duplicated from dark-www why not just remove the option from dark-www?

**Comment by MystPi** [comment]
> If most of this addon's code and presets are being duplicated from dark-www why not just remove the option from dark-www?

I didn't take any code from dark-www, and the presets are from the default Scratch light mode.

**Comment by mxmou** [comment]
> > If most of this addon's code and presets are being duplicated from dark-www why not just remove the option from dark-www?
> 
> I didn't take any code from dark-www, and the presets are from the default Scratch light mode.

I think @Samq64 was replying to my post, where I said that the code and presets from dark-www should be used. The reason for not removing the option from there is to have good defaults for each dark mode preset.

**Comment by MystPi** [comment]
Bump.

**Comment by WorldLanguages** [comment]
@mxmou Could you remind me your stance on this PR as it is currently? Do you think this should be merged, and if not, what changes would you make, or should this not be a separate addon at all?

**Comment by mxmou** [comment]
> @mxmou Could you remind me your stance on this PR as it is currently? Do you think this should be merged, and if not, what changes would you make, or should this not be a separate addon at all?

It currently only affects three different banners - I think it should be extended to all of them using the stylesheet from dark-www.

**Comment by MystPi** [comment]
I'm finished with this addon, and it is ready to merge. It can customize the colors of the explore, ideas, and my stuff page banners.

**Comment by MystPi** [comment]
Any updates on this?

**Comment by MystPi** [comment]
Okay, thanks for the info. 😸

**Comment by WorldLanguages** [comment]
@mxmou Do you think this should be reopened? Or should we add a feature like this in the future?

**Comment by Secret-chest** [comment]
Any updates? Also, I don't think dark blue should be generated, because they have a different role, you don't necessarily want to have them darker.

**Pull request closed without merging**
