### PR TITLE
i prefer lowercase j

### PR DESCRIPTION
**Pull request by JeffaloBob**
**Resolves**

sad jeffalo

**Changes**

lower case j i prefer

**Reason for changes**
i prefer

**Tests**

no

### CODE REVIEW

**Comment by JeffaloBob** [comment]
this was definitely not so i can have 200th commit

**Comment by WorldLanguages** [comment]
lol no i had it

**Comment by JeffaloBob** [comment]
but like fr can you merge it

**Comment by WorldLanguages** [comment]
Your Scratch username has an uppercase J.

**Pull request closed without merging**
