### PR TITLE
New Addon: Fullscreen Project

### PR DESCRIPTION
**Pull request by e-coders**
New Addon: Fullscreen Project
Adds an option to let we get an button and click it to open in fullscreen ( Like https://scratch.mit.edu/projects/378507713/embed/
But If we clicks from an Project that is not containing "/" Forward Slash at the end, # 404 because the URL will be https://scratch.mit.edu/projects/378507713embed. help!!
Also help that after merging, In the addons.json file there my addon at top stops working others. Please Help!!

### CODE REVIEW

**Comment by RedGuy12** [comment]
this just adds another fullscreen button...we already have a fullscreen button

**Comment by e-coders** [comment]
No!! I've added another one button that is able to be load project as Embed. See https://scratch.mit.edu/projects/ProjectID/embed

**Comment by e-coders** [comment]
:`(

**Comment by RedGuy12** [comment]
not useful

**Comment by WorldLanguages** [comment]
@e-coders This is a good first PR tho

**Comment by CST1229** [comment]
Also, you can't put comments in JSON.
Don't modify the manifest (usually) - `__MSG_extensionName__` is automatically replaced by something else via localization stuff, and the version number is usually only changed on a "bump to `[version]`" PR.
New non-theme addons should be put above the themes (above `// NEW ADDONS ABOVE THIS ↑↑`).

**Pull request closed without merging**
